### ISSUE TITLE
Guardians has territoryShieldFactor applied to them.

### ISSUE THREAD

**Issue by TagCraftMC** [MassiveCraft/Factions#1000]
Hi Factions Team,

Not sure if this is intended, but it does seem like a bug. When being attacked by a guardian in enemy territory, you receive the message (often spammed) in chat that you're doing X damage less to them due to the territoryShieldFactor.
Screen shot below.
We're running 2.8.2 and Spigot 1.8.8.

Thanks!

![](https://i.gyazo.com/0b30731baad05e1a328954aade28063d.png)

**Comment by magnusulf** [comment]
Is this also the case for other mobs?

**Comment by TagCraftMC** [comment]
Hi magnusulf, sorry for the delay.

Yes, according to the player that reported it, he is able to confirm it's any hostile mob in the enemy faction which does not make too much sense :)

**Comment by magnusulf** [comment]
Fixed in https://github.com/magnusulf/Factions/commit/9335152dc118864eda7f906b5723b6ce9bc979a2
Will be a part of the next release.
