### ISSUE TITLE
Punctual errors on logs

### ISSUE THREAD

**Issue by MithrandirCraft** [MassiveCraft/Factions#1003]
Hi, I found this error on my logs today:

http://hastebin.com/pilusovige.avrasm

Edit: found this/these other error/s:
http://hastebin.com/texaxefoqu.avrasm

Just once though. I still thought I should report them.

----------------------
Factions & Mcore version: 2.8.2
Spigot: 1.8.8

**Comment by ulumulu1510** [comment]
Under what circumstances did this happen? It seems that the system wanted to get the sender entity of an NPC, but that is farely uncommon and I am wonder how that happend.

Please also state the usual: Version numbers of everything related and other info you might have @MithrandirCraft. You know the procedure ;).

**Comment by MithrandirCraft** [comment]
Hmmm I have no idea, there's nothing really on the logs which could give a hint.

Maybe we should just ignore this unless it happens again. If it happens more often I'll try to spot what's going on in the instant xD

**Comment by ulumulu1510** [comment]
Would you still be so nice and provide Factions, MassiveCore and spigot version? ^^

**Comment by MithrandirCraft** [comment]
It's done! stop harassing me dude!

Joke xD

**Comment by ulumulu1510** [comment]
Sorry, that might have been my site not updating your first message ^^

**Comment by MithrandirCraft** [comment]
Here's another one, found it today. Seemingly random errors pop every now and then:

http://hastebin.com/texaxefoqu.avrasm

Same versions. Updated ticket.

**Comment by magnusulf** [comment]
These logs are partially outdated because source code has been changed. Please seeif you can recreate with Factions 2.8.3
