### ISSUE TITLE
F list command and vanish

### ISSUE THREAD

**Issue by djtev** [MassiveCraft/Factions#1006]
issue: vanished players listed as online within the f list command

explanation: so the server Im a moderator on has it so that staff join vanished, so that they do not get harrassed upon joining. however online members can do the f list command and it shows the faction as having a member online, when tab doesnt show the member of staff as there.

request: hook into vanish protocol from essentials/vanish-no-packet (whichever is best and easier to use) to hide vanished players from the factions list command

**Comment by ulumulu1510** [comment]
This fix will be part of the next plugin version.

**Comment by djtev** [comment]
ok thanks for letting me know :)
