### ISSUE TITLE
usercache.json

### ISSUE THREAD

**Issue by Jnxd1** [MassiveCraft/Factions#1007]
Hello again, thanks for the fast responses guys rlly!
I wanted to ask you, i had some kind of a server crash which grew in a problem that i could not start the server (just if you want to see it here is the paste bin http://pastebin.com/zjMbJFuG ).I did a fast search on the web and i found a post at spigot that was saying to try and delete the "usercache.json" file.Before i delete it i checked it and it was empty so i did so and deleted it (i also save it at my pc).
Now after i joined the faction server i had my "nick" restarted (which i think its from the usercache.json) , but i also was not in the faction that i have created and i get this message in the console, http://pastebin.com/akUt2bxr . Btw i em running a offline server and when i created my faction i was in online mode.Is there chance that there was some kinda UDDI mess up there?And can i delete the file?And i also have a prob with /f s , command.It displays the users by the UDDI not theyr name :(
And one last thing, i tried to delete my faction that i have created but i get an internal error http://pastebin.com/rSh3h3Ft .
I have just downloaded the Factions 2.8.3 zip from Spigot and im running on it.I saw a new update and i will install it now.
Thank you again guys!

**Comment by MarkehMe** [comment]
```zjMbJFuG ``` & ```akUt2bxr```: your username cache is full. Incase ```user-cache-size``` in you ```spigot.yml``` file. 

```rSh3h3Ft ```: This is Gringotts. Since v2.4 they have supported Factions 2.7.5. We're now at 2.8.4, and after a quick look at their code they're not using ```FactionColls``` (a deprecated class) but your Gringotts is. There latest version is at v2.7, what version is yours?

**Comment by Jnxd1** [comment]
I em using the one at Spigot https://www.spigotmc.org/resources/1-8-7-gringotts-unofficial-release.3473/
The version is : [1.8.7]Gringotts+ (Unofficial Release) 2.7.6

**Comment by MarkehMe** [comment]
This plugin is actually out of date.. the source code itself has not been updated for over a year as you can see here: https://github.com/Adobes/Gringotts-/tree/master/src/main/java/org/gestern/gringotts

Please use the version from here: http://dev.bukkit.org/bukkit-plugins/gringotts/files/33-gringotts-v2-7/ 
I just had a look at the dev.bukkit version and it is more stable, and uses the new API.

**Comment by Jnxd1** [comment]
Thank you so much!!! I will try it.

**Comment by MarkehMe** [comment]
Good luck :)
