### ISSUE TITLE
Cant disband a faction + others

### ISSUE THREAD

**Issue by Jnxd1** [MassiveCraft/Factions#1009]
Hi again guys.I wanted to report few more things here.The auto disband is not working also the one by command(/f disband), and i get some errors.And the auto-disband is spaming it every 5-10 min in the chat, " The faction <name> was disbanded. ".
http://hastebin.com/rucofofoba.avrasm
http://hastebin.com/leliyexepa.sm
http://hastebin.com/voqefekeza.avrasm - /f show
Thanks again!

**Comment by magnusulf** [comment]
This is caused by Gringotts using an extremely outdated version of factions.

**Comment by Jnxd1** [comment]
Oh its the Gringotts again -,-
Okey thank you so much !!

**Comment by MarkehMe** [comment]
What Gringotts plugin are you using? The alternative version on Spigot is not maintained - do not use it. Use the original version of Gringotts, reports have said that version works. :)

**Comment by Jnxd1** [comment]
Yes i've converted yestoday to the Bukkit version of Gringotts 2.7 and everything works like a charm!
Thanks guys!

**Comment by Jnxd1** [comment]
Once i em writing now, i was trying to make so that the players can claim at the neter and in the end.But i just cant do it, i think ive tried everything and there still has an error popping up in the console,."Did you manually change the cofig, there is a mistake or the new JSON is wrong", something like that, i guess my syntax is wrong.Im not sure how to make it.Sorry for the question i gues you got a lot to do , but can you show me how it should the syntax be?If you cant now , its ok just ignore this massage i will ask/look elsewhere also.
Thx guys!

**Comment by ulumulu1510** [comment]
Mostly, this is because you copy and paste things into the json in my experience. Fill it out manually (by typing) and run it trough an issue checker:
http://jsonlint.com/

Just as a reminder to you, this is an issue forum, not a help-desk. If you have an issue, post it. But if you have a question, you might want to ask it on the spigot forums where loats of people are who might be able to answer your questions as well as we do.

**Comment by magnusulf** [comment]
Please keep issue comments on topic. Not all comments here were regarding the issue.
