### ISSUE TITLE
Problem with /f promote

### ISSUE THREAD

**Issue by Eduedw** [MassiveCraft/Factions#1010]
Hello,

I have just recently updated my server with the latest Factions build (Version 2.8.4). So far, I have encountered a problem with one of the commands -- /f promote. In the past, /f promote <Name> <Faction> would promote the desired user in a faction to a higher rank. However, after updating to 2.8.4, it seems that the command is no longer functioning as expected. Currently, when I execute /f promote, it returns /f promote <Name> <Faction>, but when I attempt to execute /f promote Eduedw, it returns me the error:

"No rank matches "promote".
All: Leader, officer, member, recruit, ally, truce, neutral."

I hope that this issue can be resolved as quickly as possible. Factions is an excellent plugin and it would be a shame if the problem was not rectified.

Thank you for your kind attention!

**Comment by Eduedw** [comment]
ally, truce, neutral."

I hope that this issue can be resolved as quickly as possible. Factions is an excellent plugin and it would be a shame if the problem was not rectified.

Thank you for your kind attention!

*** I misclicked and mistakenly pressed the "Comment" button before I could finish my comment above. Sincere apologies!

**Comment by magnusulf** [comment]
This was fixed earlier today in (this)[https://github.com/magnusulf/Factions/commit/0937e12b210cc6ba4445c9c73cfde98ef2be147b] commit. This will be a part of the next update.
