### ISSUE TITLE
java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PlayerInventory

### ISSUE THREAD

**Issue by djoveryde** [MassiveCraft/Factions#1013]
I'm running 1.7.10 Minecraft on the KCauldron loader. I am currently getting the below error constantly spamming console.
There was a suggestion to update however it appears that only version 2.7.2 works on KCauldron 1.7.10. All newer version factions fails to load up.

Is there a secret version of Factions/massivecraft that I should be using that supports 1.7.10?

http://pastebin.com/CnnuQUaQ

**Comment by magnusulf** [comment]
Cauldron is not officially supported.
