### ISSUE TITLE
Help, problem with factions, ./f claim

### ISSUE THREAD

**Issue by ZippOoO** [MassiveCraft/Factions#1016]
When I tried to zaprivatit territory, I came here such a mistake.  http://prntscr.com/9yvkzr

**Comment by ulumulu1510** [comment]
You are running an outdated version of factions because that message got replaced by a more descrptive one:
You are using Cauldron or KCauldron which is *not supported* by factions. They messed with some internals and broke the bukkit api at a few places.

**Comment by ZippOoO** [comment]
And what better to change the kernel?

**Comment by ulumulu1510** [comment]
Your problem is solvable, but it might not suit you. Running Spigot is the only possivility to run factions.
If you want to run mods as with cauldron, there is no option currently.

**Comment by ZippOoO** [comment]
Thank you. Prompt not a team. /f claim warzone
