### ISSUE TITLE
WorldPowerLossEnabled - Help

### ISSUE THREAD

**Issue by KotsosTrela** [MassiveCraft/Factions#1017]
Hello! I want to know how i can set up the worlds so the players can not lose their power when they die.
Let's say i have world1 and world2. I want in world1 to lose and in world2 not too lose. How i can set it in the config? I saw the factions configuration website, but can't deal with it. Pls help >.<
{
  "aliasesF": [
    "f"
  ],
  "worldsClaimingEnabled": {
    "standard": true,
    "exceptions": []
  },
  "worldsPowerLossEnabled": {
    "standard": true,
    "exceptions": []
  },
  "worldsPvpRulesEnabled": {
    "standard": true,
    "exceptions": []
  },

**Comment by ulumulu1510** [comment]
"Standard" is what applies to every world. The following list are the exceptions to the standard value.
So you have a few worlds and you want powerloss to be true on only two of them, you want to write
"standart": false,
"exceptions": [
"worldNameOne",
"worldNameTwo"
]
Into the worldsPowerLossEnabled like this. The names need to be the exact casing as in your world folders.

I hope this helped. As a general notice though, thid is a bug/issue tracker. For hrlp go to the comment section of Spigot.
