### ISSUE TITLE
Factions Issue with Chat

### ISSUE THREAD

**Issue by ProMiner10000** [MassiveCraft/Factions#1019]
So not sure if you know about the chat where it says "r" on your name like this http://www.minecraftforum.net/forums/support/server-support/server-administration/1931329-a-factiontag-r-username-faction-problem

Anyway, I fixed that problem by doing the [FACTION] thing editing the Essentials config. Although my server has multiple worlds so when I go to Spawn it'll say [FACTION] ProMiner10000 because I have another plugin called PerWorldPlugins so in Spawn you can't do faction commands, only in the faction world. I obviously don't want that. Is there a way to fix this?

**Comment by magnusulf** [comment]
It says "r" on your name, what exactly do you mean?
Which chat plugin are you using?
Have you tried a server only with MassiveCore and Factions, does the error still persist?

**Comment by ProMiner10000** [comment]
Thanks for trying to help ^^ But I forgot to close this, so sorry. I fixed it. Instead of using one server I'm now using BungeeCord with 3 different servers which fixed this issue.
