### ISSUE TITLE
Faction#get(MPlayer)#getId() returning null

### ISSUE THREAD

**Issue by grrocks** [MassiveCraft/Factions#1020]
Hi could you guys check out this issue I just upgraded to 2.8.5 from 2.8.3 and now my plugin isn't working and that is returning null, any help would be highly appreciated.

**Comment by ulumulu1510** [comment]
Could you provide us with more code please? Also, what have you expected to happen? It is surely not intended to return null, so I am interested in any error log or stacktrace you can provide.

Please do not forget to include MassiveCore / Factions and Spigot version.

**Comment by grrocks** [comment]
Thanks for the quick response!
MassiveCore version: Latest From spigot
Factions version: Latest from spigot (2.8.5)
Spigot version: PaperSpigot 1.8.7

Code:
http://hastebin.com/tizequmudi.avrasm

StackTrace:
http://hastebin.com/tefukesixi.avrasm

Erroring line (Line 64): .getId();

**Comment by ulumulu1510** [comment]
I just realized what you did wrong: ypu are tryig to get thr faction through Faction.get (oid), but an mplayer is not an oid (object ID) for a faction.

Please get the faction of a player through mplayer#getFaction() which never returns null. I hope this solves your issue.

**Comment by grrocks** [comment]
Thanks for the help, I am just using MPlayer#getFactionId() now
