### ISSUE TITLE
MCPC with Factions.

### ISSUE THREAD

**Issue by carelli99** [MassiveCraft/Factions#1021]
Hello, i'm having a problem, on my MCPC server 1.7.2, with mods and plugins, i put in plugins folder Factions and MassiveCore for 1.7.2. But in console i get: "GRAVE: Could not load 'plugins/Factions.jar' in folder 'plugins'"
Here the whole code: http://pastebin.com/eWZnVAsk
Same problem for MassiveCore: GRAVE: Could not load 'plugins/mcore.jar' in folder 'plugins'
Whole code: http://pastebin.com/kC73jwsS

I have java 7.

Hope in a reply. Thank You :).

**Comment by ulumulu1510** [comment]
We do not offer support for long outdated versions. It is however important to pick the right version of MassiveCore (named MCore in the versions you are using) for Factions, becuase what you are getting is an unkown dependancy exception, meaning it cannot find mcore.
