### ISSUE TITLE
Safezone message spam

### ISSUE THREAD

**Issue by xion87** [MassiveCraft/Factions#1022]
1. trow  a arrow upside a player head in safezone claim.
2. if player is afk you will receive a massive SPAM text "you can't do pvp in a safezone" until arrow disapear or player move

Is not really a bug but is pretty annoying

**Comment by MarkehMe** [comment]
This shouldn't happen, thanks for reporting.

**Comment by ulumulu1510** [comment]
I have fixed this issue by removing the arrow after its denied hit:
https://github.com/ulumulu1510/Factions/tree/spam

**Comment by ulumulu1510** [comment]
Resolved
