### ISSUE TITLE
Feature Request: Interact permission node

### ISSUE THREAD

**Issue by DraksterAU** [MassiveCraft/Factions#1023]
Hi All,

It would be awesome if we could get a permission node for interaction events in general.... to prevent opening guis and using computers on items in territory etc (I know computers are forge but you get the idea)..

Lever/Door etc are great... but another one to cover all right click on block events would be awesome!

**Comment by DraksterAU** [comment]
Not required really..... now that I'm not using a custom factions build :P

**Comment by MarkehMe** [comment]
My FactionsPerms plugin might be what you're after

**Comment by DraksterAU** [comment]
@MarkehMe I don't see how you can prevent right clicks using perms?

**Comment by MarkehMe** [comment]
Would you not be able to use permissions from a plugin like Modifyworld? e.g. ```modifyworld.blocks.interact.<blockid>```
