### ISSUE TITLE
Duplicate Territory Messages

### ISSUE THREAD

**Issue by DraksterAU** [MassiveCraft/Factions#1024]
Hi All,

I'm getting duplicate territory entry/exit messages whenever I switch between faction lands w/ Factions 2.8.5 and Kcauldron (I know you guys don't fully support it again..... yet :P ) 

Any chance someone could have a look at why this might be occurring or point me in the right direction so I can fix or even remove these messages in a custom build for now? Drives me nuts!

**Comment by magnusulf** [comment]
We don't officially support KCauldron and you are aware of that. Reproduce the bug on a Spigot server and we'll take a look.
