### ISSUE TITLE
Factions updated - no longer working

### ISSUE THREAD

**Issue by TheOtakuJames** [MassiveCraft/Factions#1025]
Hi,
I have had Factions and MassiveCore on my server for quite a few months now, but when I updated both plugins to version 2.8.5, Factions no longer works. It is not showing up in the /pl list, and no Faction commands work. It is still in my files though, and MassiveCore (also v. 2.8.5) works with in game commands. I am running Spigot 1.8.8.
Is there a way to fix this, as Factions is a massive part of my server and something needs to be done fast.
Thanks!

**Comment by DraksterAU** [comment]
@TheOtakuJames I highly recommend you include what server version you're using...

**Comment by oloflarsson** [comment]
Stating "it does not work" is not really a proper bug report. It works for loads of people so you are probably doing something wrong.

**Comment by TheOtakuJames** [comment]
I went into detail @oloflarsson and as I said, the problem only occurred after the update to 2.8.5, so something has obviously changed, and I would like to know what it was, and how to fix it.

**Comment by DraksterAU** [comment]
Spigot 1.8.8 with Factions 2.8.5 works fine for me in testing.

What Factions and Massive core version did you update from?

**Comment by DraksterAU** [comment]
Also if you can scan your server logs for errors that mention factions that would be great... 
(As this is likely not a plugin issue I thought I'd volunteer to help...)

**Comment by TheOtakuJames** [comment]
Thanks @DraksterAU ! I'm unable to check what version I used to have, but it was the previous update version. I can't find any errors containing Factions or MassiveCore. There's no errors in console either when I try performing a Factions command, such as /f. It just shows "unknown command, type /help for help" on my screen, and nothing on console.

**Comment by DraksterAU** [comment]
I think you've probably got an issue with the version of MassiveCore you have. Try deleting that and loading it again.

Can you type /mcore ingame?

**Comment by TheOtakuJames** [comment]
I can do /mcore, but none of the Factions ones, like /f [anything].

**Comment by DraksterAU** [comment]
Can you zip up your plugins/factions.jar, plugins/massivecore.jar and mstore/ directory for me and post a dropbox link here? 
Add logs to the zip while your at it if you like....

**Comment by TheOtakuJames** [comment]
@DraksterAU Sorry for the late reply, been working on other things! Here's the link: https://www.dropbox.com/sh/lg6kr20u1lkvnsq/AAAXYofp6NLNEwvLbgZyOjbCa?dl=0
I have attached some screenshots of my plugins list (the one that actually shows Factions there) in the folder too.

**Comment by DraksterAU** [comment]
@TheOtakuJames Can you send me your logs please. Your Factions jars + config load fine for me on spigot 1.8.8

**Comment by TheOtakuJames** [comment]
@DraksterAU I've added a zip folder called Logs that has the log from before and after upgrading the plugin

**Comment by DraksterAU** [comment]
Hi @TheOtakuJames 

Either:

1. Factions is not in the plugins directory (Make sure its not in a sub directory).
2. Factions.jar is not readable by your server.

Based on the l ogs you've sent me... you've updated Massivecore and deleted factions.jar...

**Comment by TheOtakuJames** [comment]
Ok, In the morning, I will uninstall and reinstall Factions and MassiveCore, and report back. Both the Factions and MassiveCore say they are running 2.8.5, but I will see how it goes in the morning. Thanks for the help today!

**Comment by DraksterAU** [comment]
Factions is not even mentioned in your logs at all after the update. It means it is not even attempting to load, **which means it is either not there or unreadable.**

**Comment by magnusulf** [comment]
Factions was not properly installed by reporter. Closing.

**Comment by DraksterAU** [comment]
Thanks @magnusulf :)
