### ISSUE TITLE
Interactions with spawners are not canceled

### ISSUE THREAD

**Issue by L4BORG** [MassiveCraft/Factions#1026]
https://github.com/MassiveCraft/Factions/blob/2bcd828e2bd52481c7c6b4ce6f297f741a8ac608/src/com/massivecraft/factions/engine/EngineMain.java#L1638

is bypassing checks for some blocks such as spawners... meaning Players are still able to interact with spawners in claimed land - claimed by enemy faction (they can change spawners with right-click with spawn eggs).

**Comment by L4BORG** [comment]
This could cause issues with all plugins that interact with entities or non-solid blocks.

**Comment by MarkehMe** [comment]
Can you confirm that they can indeed change enemy spawners?

**Comment by L4BORG** [comment]
Yes, got multiple reports, I've even tested this and players can change enemy enemy spawners (while at the same time they can't interact with doors inside of enemy land for example).

**Comment by ulumulu1510** [comment]
Changing enemy spawners is not a vanilla minecraft feature. You can however change the config here:
https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/entity/MConf.java#L510
So factions considers interacting with a spawner to be an action they need build rights for.

All further support should be asked for by the author of the spawner-changing-plugin.
