### ISSUE TITLE
Error Spamming in Console

### ISSUE THREAD

**Issue by SugarRealms** [MassiveCraft/Factions#1027]
It says something about NPCS (Using Citizens). Here is the error: http://pastebin.com/sbMrJ2Ds It is rather annoying.

**Comment by MarkehMe** [comment]
Please provide more clarification and information.

1. When does this issue occur? I'm assuming it's when someone attacks an NPC created by Citizens?
2. What version of Citizens are you using?
3. What plugins are you using and what are their versions? 
4. What server are you using? (e.g. Spigot / Bukkit / Cauldron / KCauldron). What version are you using?

**Comment by ulumulu1510** [comment]
Since this issue has arisen, we have changed rhe way we handle NPCs in our Colls. Update and you should no longer face any issues. If you do, make another bug report with the newly arisen Problem.
