### ISSUE TITLE
CommanderSender Link

### ISSUE THREAD

**Issue by sventus** [MassiveCraft/Factions#1028]
Hi, at first i'm french so i'm sorry for my english.

So i have a problem, my serveur is running on 1.7.10 with cauldron, but I need that my piston can push block in enemy territory, it's for it that I take the version 2.8.0  (for minecranidr 1.8.1)  but now i have some probleme when i try to /f claim ...

**Comment by ulumulu1510** [comment]
There is a config option for the denying pistons pushing into another territory.
handlePistonProtectionThroughDenyBuild

The other issue is known and being worked on.

**Comment by sventus** [comment]
i haven't this options on this version of Faction

**Comment by ulumulu1510** [comment]
We do not offer support for outdated versions. Update to the newest version to gain this option.

**Comment by sventus** [comment]
but i can't because my serveur is on 1.7.10  and i have the errors that i explain before when i take the version for 1.8      and the latest vesion don't work with cauldron server

**Comment by MarkehMe** [comment]
Duplicate of #940
