### ISSUE TITLE
PVP and Explosion Issues Factions Version 1.8.6 CraftBukkit 1.8.8

### ISSUE THREAD

**Issue by EHEBrandon** [MassiveCraft/Factions#1029]
Hello I'm having a issue with my server. I finally got monters to work after stopping the server.. But PVP and explosions don't work. I shouldn't say they don't work because they work. But I try setting certain areas to no pvp and no explosions but pvp and explosions are still some how enabled even with those flags set to no and I don't know how to fix it. I dont want my players to die at hub. .-.  Basically PVP is always enabled and explosions is to and I want them disabled. I only want PVP enabled in Wilderness and when someone creates a faction. I just don't want it in my areas and I tried setting them to no it just wont work. I'm not even using World Guard I'm using the Factions Plug-in only as far as PVP and explosions go. I'm using minecraft-hosting.pro as well for my server. Here is a screenshot of my plugins and settings on minecraft-hosting.pro

<img width="830" alt="untitled" src="https://cloud.githubusercontent.com/assets/17282326/13094773/3fa86540-d4ca-11e5-994c-d295598894b2.png">
<img width="343" alt="untitled1" src="https://cloud.githubusercontent.com/assets/17282326/13094775/45106550-d4ca-11e5-9285-b3e24a955a1e.png">
<img width="211" alt="untitled2" src="https://cloud.githubusercontent.com/assets/17282326/13094776/48536dca-d4ca-11e5-81a6-a9ffa17545fd.png">

**Comment by EHEBrandon** [comment]
Damn now monsters spawned back in claimed areas. .-. What is with these 3 flag errors and how can I officially fix these issues?

**Comment by ulumulu1510** [comment]
Your configuration will be wrong.

Flags can be set per faction (/f flag set) or modified generall in the mstore folder. Generally though, the base configuration should suffice your needs for PvP.

I would suggest claiming you spawn with SafeZone until you read through the configuration guide at www.massivecraft.com/factions .
SafeZone is automatically a non-PvP zone and a non Monster Zone.

Through flags you can make any Faction behave like this. But its obvious that you didn't read the guide first so please do that.
