### ISSUE TITLE
Issue with spy of Essentials

### ISSUE THREAD

**Issue by matcracker** [MassiveCraft/Factions#1035]
If a player have got the spy permission, he reads the tags without the real names of factions, roles etc...
Look at picture:
![2016-02-21_22 08 11](https://cloud.githubusercontent.com/assets/10587406/13205401/85afa230-d8e7-11e5-9463-8fdc6283859b.png)

**Comment by matcracker** [comment]
Any reply?

**Comment by magnusulf** [comment]
I am pretty sure that us a bug with whatever chat plugin you use.

**Comment by matcracker** [comment]
No, I tried only with Essentials, EssentialsChat and Factions. If I set a
radius <> 0 in essentials config, it gives me this problem, if a player is
in radius message the tag works else not.
Il 25/feb/2016 16:35, "Madus" <notifications@github.com> ha scritto:
