### ISSUE TITLE
Could not pass event PlayerMoveEvent to Factions v2.8.6

### ISSUE THREAD

**Issue by Flariine** [MassiveCraft/Factions#1036]
Hi !
I have an error who spam  the logs (4 578 583 lines)

pastebin: http://pastebin.com/i2XkBpVw

Thank's ! :)

**Comment by Flariine** [comment]
Can someone help me pls ? :(

**Comment by ulumulu1510** [comment]
Ah, yes. Sorry that I didn't respond,  but I am aware of the bug and have fixed it locally.

It's hvaing to go through quality assurance first, but we are possibly able to fix this issue with the next released version :).

**Comment by ulumulu1510** [comment]
https://github.com/ulumulu1510/Factions/commit/89cfce463a8c53eaf79fec7a2c5e52e402bfe3f1

Here is the commit, it's being processed.

**Comment by ulumulu1510** [comment]
Pulled into masterbranch
