### ISSUE TITLE
Bug truce + liquid flow ?

### ISSUE THREAD

**Issue by MisterFrans** [MassiveCraft/Factions#1037]
Hi, you added the liquid flow protection in version 2.8.3. Can we disable that and let liquid flow ? An option in the config ?
Or if that is already here, I didn't see, so where ? xD.
I think they is also a bug with the rel truce. The truce players can pvp.
Thank you .
Sorry for my bad english, this isn't my natural language.

**Comment by MarkehMe** [comment]
I think this is the event doing it: https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/engine/EngineMain.java#L1577

No, it isn't blocked. But this could easily be added.

**Comment by magnusulf** [comment]
What is it exactly you want?

**Comment by MisterFrans** [comment]
I'd like know if i'ts possible to add a option in the config file for the blockLiquidFlow protection.
Thank you .
Sorry for my bad english, this isn't my natural language.

**Comment by Gbtank** [comment]
I would like to bump this issue because I myself also want to turn off liquid flow protection for cobble-monstering. But I cannot find it anywhere. I would like to know where to find it or how to fix it. I am using Factions 2.8.7Beta

**Comment by Flariine** [comment]
Bump too, very important..

**Comment by TheEnderPrince** [comment]
I'm working on it, please be patient.

**Comment by Flariine** [comment]
Ok thanks ! :)

**Comment by TheEnderPrince** [comment]
Okay, so you want a config option that disables the flow of the lava and water right? Just confirming.

**Comment by ulumulu1510** [comment]
We are currently blocking waterflow between factions. As I understand it, they would like to be able to toggle this on and off.

**Comment by TheEnderPrince** [comment]
Alright, The config now has the option to toggle on/off the flow of water, I will upload it to GitHub in a bit.

**Comment by TheEnderPrince** [comment]
Alright, The config now has the option to toggle on/off the flow of water, It is now on GitHub. :)

**Comment by MarkehMe** [comment]
It would be a simple case of adding a configuration option under ```blockLiquidFlow```. I can quickly do this if no one else is working on it.

**Comment by TheEnderPrince** [comment]
Thanks, I'm a bit tied up upgrading MY plugins. :)
