### ISSUE TITLE
Config And Chat Ingame

### ISSUE THREAD

**Issue by Noodles0809** [MassiveCraft/Factions#1050]
When I load this plugin in the FTP I don't see a CONFIG and ingame when you chat it says this

<{Factions_relcolor}>***{factions_relcolor}

How do i fix this

**Comment by ItsMonkeyyy** [comment]
It's in your main server directory. There should be a folder called 'mstore'

**Comment by Noodles0809** [comment]
Found it thanks how do i fix the chat

**Comment by MarkehMe** [comment]
You need to modify the instance.json file in your mconf folder :) 

You can find detailed documentation here:
https://www.massivecraft.com/factions-configure

Search the page for:
 ```json 
"chatSetFormat"
```
And you will find the configuration options you're looking for.
