### ISSUE TITLE
Faction relation issues

### ISSUE THREAD

**Issue by MithrandirCraft** [MassiveCraft/Factions#1054]
Hello.
Some players are encountering problems with quick relation commands such as:

/f ally
/f truce

I am unsure as to if there are further issues with any other quick relation commands.
I have only experienced issues with /f ally myself, when testing.

Here's an image of the error message I got, when attempting to establish an alliance with the shown existing online faction:
http://i.imgur.com/NdS8YDZ.png

I am aware of the /f relation commands, however, players still like to use the quick relation ones.

---------------------
Factions version: 2.8.7Beta
Spigot: 1.8.8 (ALWAYS last build)

**Comment by magnusulf** [comment]
This has been fixed and will be a part of the next update.
