### ISSUE TITLE
Plugin not working on server w/ 50+ plugins

### ISSUE THREAD

**Issue by miguel456** [MassiveCraft/Factions#1056]
Okay, so I installed massivecore and factions in a clean installation of spigot, with 500MB of ram, and everything seems to be running fine. Factions' commands work both ingame and in the console. But, in my public server, ingame commands do not work, as I previously said (on the spigot thread). I was using the same version of MassiveCore and Factions that the public server is using. 
Factions' version: v2.8.7Beta
MassiveCore ver.: The same as factions
Spigot ver.: CraftBukkit version git-Spigot-23e921f-8b69bdd (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
In the public server I'm running Linux. Does that have anything to do with the plugin's malfunctioning?
I forgot: Yes, in the public server I have the permission "*" which lets me do everything I want. Still, commands do not work in game.
The chat plugin is working fine and is in no way interfering with Factions, besides that "Wilderness" thing in the chat. Do you have any suggestions on what plugin is clashing with Factions?
Attached you can find the test server's log.

[latest.txt](https://github.com/MassiveCraft/Factions/files/186519/latest.txt)

**Comment by MarkehMe** [comment]
50+ plugins? Your poor server! This is obviously a conflict with another plugin.

The way you work this out is by disabling 1 plugin at a time until the features that aren't working, are working. We unfortunately don't have the time to do this for you. 

If you work out what plugin it is, we can look into it and see what we can do. However, it may be up to the other plugin developer to make changes.
