### ISSUE TITLE
Wilderness PvP Bug

### ISSUE THREAD

**Issue by LaughNgamez** [MassiveCraft/Factions#1058]
Right now since the Friendlyfire flag now affects land it is impossible to have it so players in the default (wilderness faction) can pvp each other while not having friends be able to pvp each other in the wilderness.

Hopefully this can be fixed soon, right now I've had to flag the wilderness with friendlyfire yes so right now people in the same faction are able to hit each other.

This was fine before the 1.9 update but it broke since the flag changed.

**Comment by ulumulu1510** [comment]
The very concept of flags is that they can be set for each faction seperately OR for all at once.

If you (like you described) uncarefully change the friendlyfire.json to standart=true, it will affect all factions there are.
However, if you read the documentation carefully, you'd know that you can set flags for each faction differently through the /f flag commands.
[ to edit a wilderness flag, turn on admin/override mode and then do /f flag set friendlyfire yes wilderness ]

There is another ticket that covers exactly this topic, please search for your issue before posting a new one.

**Comment by tspierer2** [comment]
Will this disable friendly fire between wilderness members, or disable friendly fire in the wilderness faction LAND?
