### ISSUE TITLE
Tab Complete not working for usernames with /f f command

### ISSUE THREAD

**Issue by LaughNgamez** [MassiveCraft/Factions#1059]
Doing the command "/f f <name>" does not work with tab complete, other commands seem to work though.

**Comment by magnusulf** [comment]
You are supposed to specify a faction, not a player. This is not a bug.

**Comment by LaughNgamez** [comment]
It's possible to use /f f <playername> to find what faction a player is in.

**Comment by magnusulf** [comment]
That is true. But my first statement still applies.
