### ISSUE TITLE
[Request] Add methods to interact with the JSONAPI plugin

### ISSUE THREAD

**Issue by chasen** [MassiveCraft/Factions#106]
Im wondering how hard it would be to add 1 method for the api to use. It would be really nice to the f who command available through the API.

the docs on how to do it are here: https://github.com/alecgorge/jsonapi/wiki/How-to-create-custom-api-methods

Also if its not a high priority how much of a "donation" would it take to get this feature implemented?

**Comment by magnusulf** [comment]
We do now use the Minecraf json api. If you'd like it to be used at a specific place where we don't, make a ticket or pull request for that.
