### ISSUE TITLE
Can't claim land of faction weaker than mine.

### ISSUE THREAD

**Issue by WinstonChurchill** [MassiveCraft/Factions#1060]
https://gyazo.com/bcfdc771bbcb33ad49858598518ca5fa

Please help It hasn't worked in weeks.

**Comment by ulumulu1510** [comment]
Please state your:
* Factions
* MassiveCore 
* Spigot 
Versions.

Without these information we can't really help you.

**Comment by ulumulu1510** [comment]
Hasn't answered in months, closing.
