### ISSUE TITLE
Add MySQL driver

### ISSUE THREAD

**Issue by Botanistt** [MassiveCraft/Factions#1061]
Hello.
Would be nice if you added mysql support. Because why not? I'd like to create web stats for my server.

Thanks.

**Comment by magnusulf** [comment]
Because it takes time and then we should support another database format we don't even use and test ourselves. But why don't you add that support yourself?

**Comment by MarkehMe** [comment]
Unfortunately it is a bit of effort, however - MassiveCore does support MongoDB! 

Using MongoDB you can fetch all the same information. See here: http://php.net/manual/en/class.mongodb.php

**Comment by DraksterAU** [comment]
Most of the files can also be imported using PHPs json_decode method... it is messy and will require some filtering out the stuff you dont want, but it works and is simplistic from a coding point of view.

**Comment by MarkehMe** [comment]
Good thinking, I might write a quick little php library actually :stuck_out_tongue:

**Comment by DraksterAU** [comment]
No worries, I have some code that might help... will find it for you :)
I did a stats page for 1.7.2 with factions 2.5.. Might be a bit dated now tho

**Comment by MarkehMe** [comment]
I ended up spending some time this afternoon making this: https://github.com/MarkehMe/FactionsPHP

**Comment by DraksterAU** [comment]
Better than mine... By far...

**Comment by MarkehMe** [comment]
It was more of an experimental project :stuck_out_tongue:

**Comment by Botanistt** [comment]
@magnusulf because I'm not familier with java.
@DraksterAU I was thinking about something like that but since I'm rookie with PHP and I couldn't find a way how to get factions info from json since every faction has their own json file.
@MarkehMe Wow thanks, Is it laravel or something? :D

**Comment by DraksterAU** [comment]
@Botanistt If you were to do a glob("dir/*.json") and a foreach on that array ... you could jsonencode each item.

**Comment by Botanistt** [comment]
@DraksterAU I guess I have to try to insert everything in mysql database. Thanks for helping out.

**Comment by DraksterAU** [comment]
@Botanistt No worries... You don't have to import it into a MySQL Database, you could theoretically just render it in HTML using PHP.

**Comment by Botanistt** [comment]
@DraksterAU I think that would make page load slower. Could insert everything into mysql database from time to time with cronjob.

**Comment by MarkehMe** [comment]
It is a composer package - it can be used with Laravel :smiley: 

Reading JSON files is really a quick task so it should go alright! 

In the situation of uploading to a MySQL database, well, why wouldn't you just use their existing MongoDB driver? It's a lot faster than MySQL too if you're worried about speed!

**Comment by DraksterAU** [comment]
Just don't render every single claim on all worlds on the same page :P

Only time I ran into issues

**Comment by Botanistt** [comment]
@MarkehMe I'm not worried about speed, I have never worked with mongoDB before and mysql is more familier to me but I'll give it a shot.

**Comment by DaPhexion** [comment]
MySQL seems a bit heavy for a factions plugin. Why not use SQLite? It's serverless.

**Comment by DraksterAU** [comment]
Most database driven websites don't use SQLlite.

The purpose of this is to add an ability to harvest statistics for web view.

**Comment by oloflarsson** [comment]
The solution to this problem is to use MongoDB. We will not add MySQL support. It simply does not make sense to store Objects in a table database system. MongoDB is however fully supported and works just as well as the flatfile driver.
