### ISSUE TITLE
Faction Ally Home Teleport

### ISSUE THREAD

**Issue by DeJay6424** [MassiveCraft/Factions#1062]
How does one disable the ally of a faction teleporting to their home.
Example: FactionA is allied with FactionB
FactionB member runs command /f home FactionA
Server Owner and FactionA is sad that is possible.

I am running:
Factions 2.8.7Beta
Mcore 2.8.7Beta
Spigot git-Spigot-8ccef51-7528608 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Comment by ulumulu1510** [comment]
Every faction has the ability to control themselfs  whether or not allies or other relations can use their home. It's using the fperms ( /f perm ).

[If there only was a place where you could read about the configuration of factions.... ;)](https://www.massivecraft.com/factions#permissions)

**Comment by magnusulf** [comment]
You can open the files in server/mstore/factions_mperm where you can hide the flag as well as make it not editable and set the default value.
