### ISSUE TITLE
/f enemy isn't working.

### ISSUE THREAD

**Issue by plaincamron666** [MassiveCraft/Factions#1065]
Whenever I try to do /f enemy <faction name> I get the message 

"No Relation Matches <faction name>
All: Neutral  : Truce : Ally : Enemy"
Screenshot: https://gyazo.com/9f4728f8ca750e4b14b74229eba2a1e6

"Royals" In a faction on my server, I can use /f Neutral, /f Truce, and /f Ally. But not /f enemy.

I am using version 2.8.7Beta. I have massive core installed.

I need help ASAP
Thanks
- plaincamron666

**Comment by magnusulf** [comment]
This is fixed on GitHub, will be part of next release. Use /f rel, in the meanwhile.
