### ISSUE TITLE
Create Faction Manually?

### ISSUE THREAD

**Issue by benjaminhallock** [MassiveCraft/Factions#1067]
Just wondering if there's a way to create a JSON for a faction like a second warzone. I assume no because the `createdAtMillis` needs to be a number belonging to the database. So the only way to create a second warzone is to create a faction in-game, rename it accordingly, then claim the land and set the properties.

**Comment by magnusulf** [comment]
You can create a new file and call it `whateverid.json` and make the contents `{}` then the rest of the contents will fill out automatically, but you would still need to make it permanent to avoid it from disbanding and changing other things that need change..

**Comment by benjaminhallock** [comment]
Okay thx sorry for abusing github!
