### ISSUE TITLE
Could not pass event PlayerMoveEvent to Factions v2.8.7Beta

### ISSUE THREAD

**Issue by KelvinKam** [MassiveCraft/Factions#1068]
Hi Developers, 

Please help for this error, it keep spamming my console, thank you.
The error will not show for a short while after I use /pm reload Factions.
CraftBukkit version git-Spigot-76236cb-62a2169 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

http://pastebin.com/CiUfvGqY

**Comment by MarkehMe** [comment]
Thanks for reporting the issue! It's people like you that help keep the Factions plugin alive and healthy. Fortunately - this bug has been fixed. It will be available in the next version of the Factions plugin. 

You can safely ignore this error for now - even though its incredibly annoying. Your data is safe. 

If you have any other issues, please open another ticket. :smile: 

(by the way! reloading doesn't always work too well with plugins, and it's suggested that you don't do this)
