### ISSUE TITLE
Please add config option for disabled water and lava liquid protection in claim

### ISSUE THREAD

**Issue by iArkadia** [MassiveCraft/Factions#1069]
Because player can't attack base without usebug tp...

**Comment by iArkadia** [comment]
"protectionLiquidFlowEnabled": false,

don't work

**Comment by MarkehMe** [comment]
I'm not sure I understand what you mean. Do you mind giving this in a scenario? It might make it a bit easier to understand :smile:

**Comment by ulumulu1510** [comment]
Please state your versions of:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.

**Comment by iArkadia** [comment]
My players can't usebug base with teleportation because they can't use water bucket or lava bucket in order to flow in enemy claim because there are liquid protection and liquid can't flow in not owned claims ...

Sorry for bad english.

**Comment by MarkehMe** [comment]
A liquid flow protection toggle has been added (see #1037) and should be available if not in the current release, in the next release as ```protectionLiquidFlowEnabled```
