### ISSUE TITLE
Lingering potions and SafeZone

### ISSUE THREAD

**Issue by VerumUK** [MassiveCraft/Factions#1071]
Version 2.8.8
Spigot 1.9.2

It seems that lingering potions still take effect in SafeZones, this is including the poison one which causes damage to the player and allows me to kill people.

Now if I've simply missed something let me know.

**Comment by oloflarsson** [comment]
I think you are right. This is a feature we should implement.

**Comment by ulumulu1510** [comment]
This issue is fixed now and will be coming with the next version realeased.
