### ISSUE TITLE
factions.admin

### ISSUE THREAD

**Issue by TheBrianiac** [MassiveCraft/Factions#1074]
I've given my Staff usergroup factions.admin, but they aren't able to use /f admin.

I am running PermissionsEx 1.23.4, Factions 2.8.10 and Spigot for 1.8.8.

I have strong experience with configuring PEX, and I've tried all of the usual PEX-related solutions. Am I missing something?

**Comment by oloflarsson** [comment]
One thing could be that you are giving the wrong permission node. The /f admin command is actually called /f override now and admin is just an alias. The permission node you are looking for is `factions.override`.
