### ISSUE TITLE
"PlayersBypassWildernessTerritory" Config option

### ISSUE THREAD

**Issue by DraksterAU** [MassiveCraft/Factions#1075]
Hi All,

It would be great for a the "players bypass all protections" config to be replicated and have an additional 'players bypass unclaimed land' option.

This would mean that fakeplayers can be listed to only work in areas that are not protected, meaning  they cannot grief.

Regards
DraksterAU

**Comment by ulumulu1510** [comment]
I am not sure if I understand you correctly, but this is basically what factions is for:
Everyone can only edit territory of their own faction. Factionless can only edit wilderness. So to make this clear please state your versions of:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.

**Comment by MarkehMe** [comment]
Closing. If this is still an issue please let us know 😄

**Comment by DraksterAU** [comment]
This is still an issue.

The problem is that the setting currently in use doesn't allow for fake players to work in the wilderness but not bypass all claimed land.

This means an industrial miner from buildcraft or mekanism can always grief people.... Or not work at all.

There needs to be an option to allow certain fake players to break/place blocks in the wilderness ... so servers can adopt the "you must use industrial miners in unclaimed areas" guideline.

Seeing as you guys don't have plans to support cauldron don't worry about it - my perimeter plugin does this for those that want it.
