### ISSUE TITLE
Faction world problem.

### ISSUE THREAD

**Issue by ShewinBuurema** [MassiveCraft/Factions#1076]
Hello makers from factions,

Can you help with me problem so yes here is me problem.
On my server i have Factions but i have so Creative world but if i join me creative world i can use "/f claim one" how can i disable it with groupmanager?!?!?!

Regards: Shewin Buurema

**Comment by oloflarsson** [comment]
You can limit Factions claiming to a certain set of worlds by editing the main configuration file. It's all covered in our official documentation.

**Comment by ShewinBuurema** [comment]
Tynx
