### ISSUE TITLE
"You cant hurt people in your faction"

### ISSUE THREAD

**Issue by redhud** [MassiveCraft/Factions#1079]
Not sure how to fix this?
I am running a hub server!

HELP?

**Comment by ulumulu1510** [comment]
Please state your versions of:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.

**Comment by redhud** [comment]
Its the newest versions for all...

Ive done nothing... and its when I hit players on my minigames

**Comment by ulumulu1510** [comment]
Newest version is not a number.

**Comment by MarkehMe** [comment]
You can find your versions using ```/mcore version``` and ```/f version```

**Comment by kristiantomov** [comment]
I have the same problem, Im using factions - 2.8.13, mcore: 2.8.13 and paperspigot 1.8.8

**Comment by tuanjr** [comment]
i have the same problem, please fix it!

**Comment by MarkehMe** [comment]
Try enabling PVP and fiendlyfire?

```
/f flag wilderness PVP yes
/f flag wilderness FriendlyFire yes
```

**Comment by tuanjr** [comment]
when i try enable FriendlyFire in wilderness, factions of player also has FriendlyFire to.

**Comment by MarkehMe** [comment]
I don't quite understand what you mean, can you explain this a little further?

**Comment by tuanjr** [comment]
sorry my english bad, example:
player-A and player-B in faction named Bros, when i'm change   "friendlyfire": false, in to    "friendlyfire": true , (on factions_factions/none.json), so player-A can hurt player-B.

**Comment by kristiantomov** [comment]
Let me explain, you may understand me better. So when 2 players are in wilderness (dont have faction) they cant hurt each other (it says you cant hurt members in your faction) meanwhile PVP is set to true and FRIENDLYFIRE is set to False) Also if you set FRIENDLYFIRE to YES for Wilderness, it also makes it so faction members can hurt each other even if FRIENDLYFIRE is off.

**Comment by MarkehMe** [comment]
I think this issue is out of my scope of understanding unfortunately. A lot of developers are quite busy at the moment, but someone will get to this soon for you. 

For now consider setting disablePVPForFactionlessPlayers to true.

**Comment by xion87** [comment]
Same issue

**Comment by tspierer2** [comment]
PLEASE FIX THIS STUPID ISSUE

**Comment by ulumulu1510** [comment]
This issue has been dealt with in one of the recent versions
