### ISSUE TITLE
Removing Permissions

### ISSUE THREAD

**Issue by cometcaleb** [MassiveCraft/Factions#1080]
Hello.

So I am running a multiverse world and am trying to figure out how to do a per-permission world. I cannot figure out for the life of me how to remove factions permissions. I have PEX and I have tried removing the factions.kit.0 or factions.kit.rank0 but it seems like all of the permissions are already pre-assigned. Is there a way to fix this? I have researched this for so long and cannot find a solution. 

I have the 2.8.11 version. If anyone could help me with this you would be my best friend.
I am also using bukkit 1.9.2

**Comment by ulumulu1510** [comment]
kit rank 0 is the default, but removing that should be possible. We are however not responsible for the permissions plugins inability to remove permission-nodes.

If you want to stick with your plugin, you could also edit our plugin.yml and turn default: false on the very bottom.
