### ISSUE TITLE
Bug: PvP on faction lands always on

### ISSUE THREAD

**Issue by HeadlessJoey** [MassiveCraft/Factions#1081]
So I have this plugin that blocks pvp during daytime.
It used to work perfectly fine with factions but atfer the latest patches (I think the last 2 updates) people were suddenly able to hit each other during daytime but only inside of faction claimed areas.
In the wilderness people still cannot hit each other during daytime.
I haven't changed the other plugin and all that has changed was me updating factions and mcore (I think I updated it twice, maybe 3 times when this problem started to occur).

So did something change anywhere?
I checked all the flags and configs but everything is exactly the same as before and if I change the PvP Flag to False then people are no longer able to PvP at all even during nighttime. The only other thing I found in the config was that PvPRulesEnabled but if I enable that then the owner of the faction can still pvp during daytime, it just denies other players from pvping on his lands if they aren't enemies.

So in short: I have a plugin so people can only pvp during nighttime but after the recent updated people can suddenly pvp during daytime BUT only inside of faction claimed lands, the wilderness is still non pvpable during daytime (it's definitely not the other plugin but some mechanic with faction claims).

Version info:

02.05 16:44:32 [Server] INFO ________.[ Plugin Version & Information ].___________
02.05 16:44:32 [Server] INFO Name: MassiveCore
02.05 16:44:32 [Server] INFO Version: 2.8.11
02.05 16:44:32 [Server] INFO Website: https://www.massivecraft.com/massivecore
02.05 16:44:32 [Server] INFO Authors: Cayorion
02.05 16:44:32 [Server] INFO Description: MassiveCore is a plugin that contains libraries and features that other plugins make use of. Cayorion from the minecraft server MassiveCraft is the lead programmer. Feel free to visit us at https://www.massivecraft.com

02.05 16:44:33 [Server] INFO ________.[ Plugin Version & Information ].___________
02.05 16:44:33 [Server] INFO Name: Factions
02.05 16:44:33 [Server] INFO Version: 2.8.11
02.05 16:44:33 [Server] INFO Website: https://www.massivecraft.com/factions
02.05 16:44:33 [Server] INFO Authors: Cayorion, Madus, Ulumulu1510, MarkehMe and Brettflan
02.05 16:44:33 [Server] INFO Description: Factions allows the players to team up and claim land as their own and start wars with other factions. This way we hope to inspire politics, intrigue, and team spirit. Cayorion from the minecraft server MassiveCraft is the lead Factions programmer. Feel free to visit us at https://www.massivecraft.com

**Comment by HeadlessJoey** [comment]
Just updated to the newest version 2.8.12 for both factions and mcore but the problem is still occuring.

**Comment by DraksterAU** [comment]
What is your PVP Restriction plugin called?

**Comment by HeadlessJoey** [comment]
It's called PvPDiffTimer (Day/Night - PvP & Difficulty Cycle on Bukkit).

I can't really test if it's on their end (I doubt it since it worked fine with some older version of factions) but yeah if I remove the plugin then ofcourse people can PvP during daytime, so no real way for me to test and there are no errors in the console to be found.

**Comment by ulumulu1510** [comment]
We haven't changed the PvP handling in our plugins since what seems a long time. Most likely, they do not cancel the attack properly and factions still "listens" for the attack. I would suggest you reporting this issue to them and saying that they should lower their event priority for blocking PvP.
