### ISSUE TITLE
Arrows Unable To Strike Self

### ISSUE THREAD

**Issue by ghost** [MassiveCraft/Factions#1082]
Even if the friendlyfire flag is set to yes for a faction, it does not seem possible for a player to hit themselves with an arrow to gain velocity in a factions-enabled world (for instance, allowing continuous flight). Other worlds in a multiworld will allow it.

**Comment by ulumulu1510** [comment]
I am not sure whether this is a bug or a feature. In our opinion, one should not be able to hurt itself. In case of an arrow shot at yourself, Factions evaluates that you both are in the same faction (obviously) and are thus not able to hurt each other in the usual circumstances. If you want this to be possible, make sure to turn friendlyfire on.
