### ISSUE TITLE
ClaimsMustBeConnected does not work

### ISSUE THREAD

**Issue by ultimate255** [MassiveCraft/Factions#1084]
"claimsMustBeConnected": true,
  "claimsCanBeUnconnectedIfOwnedByOtherFaction": true,

I have both of these set to true, and any faction can still claim anywhere without being connected.
However if I set ClaimsCanBeUnconnectedIfOwnedByOtherFaction to false, it works properly but then they are unable to claim enemy territory.

How can I force faction claims to be connected and at the same time allow claiming enemy land?

**Comment by MarkehMe** [comment]
Please provide:

- Factions Version (use the command ```/f version ```)
- MassiveCore Version (use the command ```/mcore version```)
- Server type (Spigot/Bukkit/PaperSpigot) and version (use the command ```/version```)

**Comment by ultimate255** [comment]
Factions Version: 2.8.12
MassiveCore Version: 2.8.12
Spigot 1.9.2

**Comment by MarkehMe** [comment]
Closing. If this is still an issue please let us know 😄
