### ISSUE TITLE
Factions 2.7.5 bug

### ISSUE THREAD

**Issue by tehrenderr** [MassiveCraft/Factions#1085]
Wooden buttons/Others kinds of doors (dark oak) can be used in other people's territory even though I have buttons and doors limited to faction members in the factions_mperm

**Comment by MarkehMe** [comment]
Have you added them to ```materialsDoor``` in your mconf file? (```/mstore/factions_mconf/instance.json```)

**Comment by DraksterAU** [comment]
@tehrenderr What version of MC are you using?

**Comment by MarkehMe** [comment]
Close due to inactivity. If there is still an issue, simply respond to this issue ticket. 😄
