### ISSUE TITLE
Bug with /f ally command

### ISSUE THREAD

**Issue by boidy** [MassiveCraft/Factions#1086]
when doing /f ally NAME the command that pops up saying [ACCEPT] in chat runs an invalid command /set FACNAME ALLY shouldn't it be /f ally FACNAME?

**Comment by ulumulu1510** [comment]
This Bug has been fixed in a recent version, please upgrade.

**Comment by boidy** [comment]
-- Please reply above this line --


Hello,

We got your message! One of our customer support team will reply to
you as soon as possible.

Thanks!
