### ISSUE TITLE
Warzone is white on /f map

### ISSUE THREAD

**Issue by kristiantomov** [MassiveCraft/Factions#1087]
faction version: 2.8.13
mcore version: 2.8.13
version: paperspigot 1.8.8

By default Warzone is peaceful. When I claim something with Warzone and type /f map it shows it in pink (&d), but then, when I make it so its not peaceful faction it shows it in white (&f). In every other faction server the warzone is in dark red (&4). How do I fix it?

**Comment by ulumulu1510** [comment]
By default warzone is *not* peacefull.

But propably what you are searching for can be found here:
https://www.massivecraft.com/factions-configure

Read the lines 330 and onward, the section about colors. Edit to your liking.
