### ISSUE TITLE
EventFactionsCreate doesn't get cancelled

### ISSUE THREAD

**Issue by bennie3211** [MassiveCraft/Factions#1088]
Factions version: 2.8.5
MassiveCore version: 2.8.5
Spigot: 1.8.8

The 'EventFactionsCreate' event is called even if the the balance of the player is lower than needed.

**Comment by MarkehMe** [comment]
The create event for economy integration listens on ```EventPriority.HIGH``` so you will need to compensate for that.

See: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/EventPriority.html
