### ISSUE TITLE
permission "factions.admin" won't work.

### ISSUE THREAD

**Issue by tuanjr** [MassiveCraft/Factions#1090]
i have factions 2.8.13, zpermissions. On previous versions 2.7, permisson factions.admin work, but in 2.8, it wont work anymore. Please fix this!

**Comment by MarkehMe** [comment]
This has changed! It is now ```factions.override```. 

If you're ever curious, you can check permissions for plugins from their [plugin.yml](https://github.com/MassiveCraft/Factions/blob/master/plugin.yml) file.

**Comment by tuanjr** [comment]
Thank!
