### ISSUE TITLE
/f doesnt work

### ISSUE THREAD

**Issue by Tzzzt123** [MassiveCraft/Factions#1091]
Hi, i installed MassiveCore and Factions in my server. but if my players do /f or /faction there comes a message with: Unknown command. Type "/help" for help.
Can you help me or should i get the older version?
Thanks

**Comment by ulumulu1510** [comment]
Please state your versions of:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.

**Comment by Tzzzt123** [comment]
It works now, mabe version 2.8.13 of Factions wasn't compatible with Spigot 1.9.4
And when i typed /f it said: Unknown command, please type /help for help
But since 2.8.14 it works again so i close the thread
