### ISSUE TITLE
Containers ID

### ISSUE THREAD

**Issue by carelli99** [MassiveCraft/Factions#1092]
Hello, i have a  server MCPC with mods and plugins, with mod "Iron Chest", when a player open the chest of the mod as gold chest it is not a container. How can i add id of mods in config? example:
  "materialsContainer": [
    "DISPENSER",
    "CHEST",
    "ENDER_CHEST",
    "FURNACE",
    "BURNING_FURNACE",
    "JUKEBOX",
    "BREWING_STAND",
    "ENCHANTMENT_TABLE",
    "ANVIL",
    "BEACON",
    "TRAPPED_CHEST",
    "HOPPER",
    "DROPPER"
    "879" # id of iron chest.
  ],
I hope you understand me. Bye :)

**Comment by ulumulu1510** [comment]
This list is for adding Materials. You can't add id's there as this is not how bukkit works. SO in short, unless they hook into bukkit and add this material (then you could add its name to the list), you can't add protection for those modding items afaik.
