### ISSUE TITLE
Looking for a Sentry plugin that still supports Factions?

### ISSUE THREAD

**Issue by Jabelpeeps** [MassiveCraft/Factions#1093]
Hi,

If you are looking for a version of Sentry that still supports working with Factions, check out my fork on https://github.com/Jabelpeeps/Sentry . 

If you are interested, you can see - by looking at the closed pull requests - that I have done all I can to share my modifications with the original branch, but for some reason they were not accepted.

I originally posted this link against the pull request you sent to mcmonkey, but for some reason he has deleted it.  He seems to want everyone to use his new combat npc plugin, but afaik it doesn't support factions targets as it stands.

**Comment by MarkehMe** [comment]
I'm not sure this is the best place to advertise your plugin. 

Here are some suggestions:

- [spigotmc.org](http://spigotmc.org)
- [bukkit.org](http://bukkit.org)
- [minecraftforum.net](http://minecraftforum.net)

**Comment by Jabelpeeps** [comment]
I totally agree, and that was not my primary intention, my apologies if it appeared that way.

I just wanted to let you know as you appear to have some interest in Sentry, and also be a major contributor/owner to Factions.
