### ISSUE TITLE
Factions cluttering /baltop

### ISSUE THREAD

**Issue by AlHollandiyah** [MassiveCraft/Factions#1094]
I had an issue where factions, named as their UUID, were cluttering the baltop. Somewhere I read that disabling the econ setting in the factions config would fix that and indeed it did. For a short while. But now they are back. I would like to request an option to hide the factions in baltop, as IMHO baltop should only list players. I hope this is possible!

**Comment by tspierer2** [comment]
I am having this issue as well, please help.

**Comment by StillDupeGlitchLmao** [comment]
and me

**Comment by AlHollandiyah** [comment]
The large server I am mod on, running on 1.9.4 has it too!

**Comment by ulumulu1510** [comment]
I am actually not quite sure what you mean with /baltop.
This command is not something that Factions offers and as such, we are not responsible for it either.

These UUIDS are to recognize the factions bank account, if this plugin doesn't handle them properly it is not our fault. Please make a report to the creators of the other plugin (Essentials I believe) as they are responsible for the behavior of this command.

**Comment by AlHollandiyah** [comment]
Issue fixed by essentials, for the fix update essentials to build 366 or higher!

https://github.com/drtshock/Essentials/issues/686

**Comment by SupaHam** [comment]
Apologies for this issue.

This has been fixed in [EssentialsX e95fad0](https://github.com/drtshock/Essentials/commit/e95fad04539c4c97aa9f644cdad70e15173bed19). You can grab the fix from our [build 366](https://ci.drtshock.net/job/EssentialsX/366/).
