### ISSUE TITLE
Factions money add error

### ISSUE THREAD

**Issue by WilliamEstrela** [MassiveCraft/Factions#1096]
http://prntscr.com/b65c2u

**Comment by MarkehMe** [comment]
Factions hooks into [Vault](https://github.com/MilkBowl/Vault), so this could be an external issue. 

Could you state:
* Economy Plugin and Version
* Server type (Bukkit/Spigot/Forge-based) and version 
* Are there any error logs?

**Comment by WilliamEstrela** [comment]
Ok, tks
