### ISSUE TITLE
Loading Bug with EssentialsXChat

### ISSUE THREAD

**Issue by lapry34** [MassiveCraft/Factions#1099]
hello! when i insert "Factions" and "EssentialsXChat" in the same server EssentialsXChat needs a reload to start functionality, that not happens when factions is not present in the server

**Comment by ulumulu1510** [comment]
We are not responsible for mistakes made in other plugins. Most likely, EssentialsXChat hooks into Factions badly and needs to be loaded after Factions. I see the problem in the other plugin, as long as no errorlogs correct my assumption.
