### ISSUE TITLE
PvP not working

### ISSUE THREAD

**Issue by PurestMC** [MassiveCraft/Factions#1103]
Factions version 2.8.16
MassiveCore version 2.8.16
Minecraft version 1.10

PvP in factions does not work. You can't attack factionless players, players with a faction (both enemies and neutral), factionless players can't attack eachother, because "you can't attack players in your own faction".
PvP is true in the .properties and as far as we know there are no other plugins interfering with factions.

**Comment by ulumulu1510** [comment]
Describe detailed:
* What you did, which faction flags are on/off, which perms are on/off
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.
Please also try a clean install on a test server where only MassiveCore and Factions is running. After you have tried that, please return here and we can work towards a solution @PurestMC .

**Comment by MarkehMe** [comment]
Closing. If this is still an issue please let us know 😄
