### ISSUE TITLE
Creepers are not able to damage blocks

### ISSUE THREAD

**Issue by TehProgrammer** [MassiveCraft/Factions#1107]
I have been having an issue with factions 2.8.18 for minecraft 1.10.  I noticed TNT and Creeper explosions would not damage blocks.  After messing with the config for a while I decided to delete it and let it auto-generate an updated config file (just in case it was outdated), I did this with most of the other config files as well.  This has fixed TNT not damaging blocks, but not Creepers.  As it is right now, Creepers will explode and damage players and other mobs, but not the blocks around it.

**Comment by ulumulu1510** [comment]
ave you tried messing around with faction flags?
https://www.massivecraft.com/factions#flags
https://www.massivecraft.com/factions-configure#factions-flags

This should be what you are looking for. In case this information doesn't help you, please return with a detailed description:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.
