### ISSUE TITLE
Factions 2.8.18 Lag

### ISSUE THREAD

**Issue by plasmavngaming** [MassiveCraft/Factions#1108]
I found an error went the player use command /f claim o or /f claim one
Then the server very lag
I use PaperSpigot 1.8.8

**Comment by ulumulu1510** [comment]
Please state your versions of:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Please add screenshots/pastebins of any errors you have in console.

**Comment by MarkehMe** [comment]
Closing. If this is still an issue please let us know 😄
