### ISSUE TITLE
Where is the /f (main menu command) chat class location?

### ISSUE THREAD

**Issue by Redstone-Pro-73** [MassiveCraft/Factions#1112]
Hi, I'm trying to change the text displayed when a player types the command /f. All I simply am going to change is some color codes. Issue is I've been digging around the source code and searching the repository, finding nothing relating to the chat. If you could please tell me the class (or classes) which contain the Strings I can change to change the chat. Thank you in advance!

**Comment by MarkehMe** [comment]
I'd advise against using a custom build of MassiveCore. However, it's called from here:

https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/command/MassiveCommand.java#L1012-L1016

Which ends up here:
https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/command/MassiveCommandHelp.java#L39

Perhaps you should request a feature? Colour changes?

**Comment by Redstone-Pro-73** [comment]
How would I edit this line?
http://i.imgur.com/2TZREU4.png?1
In the second link you gave me, the only ChatColor.(color) was yellow, which is no where to be found on that title line in the picture above. I would like to change the gold to dark red and everything else bold white. Like this picture:
http://i.imgur.com/T66M97L.png?1
Or this:
&4__________.[ &f&lHelp for command "f" &8[<] &f&l1/5 &7[>] &4].__________

**Comment by ulumulu1510** [comment]
This is the line with text:
https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/command/MassiveCommandHelp.java#L62

it get's colored in Txt#getPage, which then again you need to go to Txt#titleize:
https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/util/Txt.java#L479

In this method, you can change the Chatcolors of the title, as you wished.

**Comment by Redstone-Pro-73** [comment]
Thank you so much! This method works perfectly!

**Comment by Redstone-Pro-73** [comment]
I have one last (and important) question. Is there a way to disable certain subcommands/completely remove them. I don't like players typing /f tax, /f version, or /f dynmap and having those links pop up. Is there a way to edit/remove the commands and removing them from showing up in the /f help menu. If you could please tell me where these classes are located that would be great! Thank you so much in advance!

**Comment by ulumulu1510** [comment]
Disabling them is easy, as you can remove the permission that is associated with this command. Most commands have a permissionnode which regulates whether someone can use it or not. Technically, you can also edit their visibility to Secret which would simply not make them pop up in a help menu.

Since /f tax and /f dynmap are not part of the opensource Factions, but rather payed extensions, you can't edit that however.

I would advice you going with the first method, remove their permission to use the command. As @MarkehMe I also highly advise against a custom build, as we are not offering support for such in any way.

**Comment by Redstone-Pro-73** [comment]
May you please tell me the permission nodes for /f tax and /f dynmap because I can't seem to find them. Also, I understand you don't provide support, but where is the class/way I can set their visibility to Secret? Thank you!

**Comment by MarkehMe** [comment]
You will find those commands are simply [placeholder commands](https://github.com/MassiveCraft/Factions/blob/799d931050b4935946ebdf17c39b3a33bc53f1d4/src/com/massivecraft/factions/cmd/CmdFactions.java#L65-L66).

You could remove them with this in an external plugin. Depend on Factions and put this in your onLoad:
```java
@Override
public void onEnable() {
    CmdFactions.get().removeChild(CmdFactions.get().cmdFactionsTax);
    CmdFactions.get().removeChild(CmdFactions.get().cmdFactionsDynmap);
}
```

.. you could do this for any command! 🎉 


Maybe in the future we can hide these from players who aren't server administrators?

**Comment by Redstone-Pro-73** [comment]
Imported Factions properly and added this to my onEnable() {}
http://i.imgur.com/TjtvS5p.png?1
It tells me to add a cast? What am I possibly doing wrong/what is the cast that I should use? What am I doing wrong? Thanks in advance!

**Comment by MarkehMe** [comment]
Casting should be fine. 

I don't have time to test, sorry.

**Comment by Redstone-Pro-73** [comment]
I don't know what to cast though? What should I put in the casting area. I really would love this feature and it would really help me out! Thank you so much in advance for responding.

**Comment by MarkehMe** [comment]
Try casting to ```MassiveCommand```, you really shouldn't have to though. Check your import is from ```com.massivecraft.factions.cmd.CmdFactions```. Ensure you are referencing both Factions and MassiveCore with your build. 

The following worked for me:

```java
	@Override
	public void onEnable() {
		CmdFactions.get().removeChild(CmdFactions.get().cmdFactionsTax);
		CmdFactions.get().removeChild(CmdFactions.get().cmdFactionsDynmap);
	}
```

**Comment by Redstone-Pro-73** [comment]
Thank you so much it worked perfectly! You're an amazing developer!

**Comment by MarkehMe** [comment]
Thanks for your kind worlds! 😁  ❤️ 

Enjoy, let us know if you need any more help.

**Comment by ulumulu1510** [comment]
I hope that you are aware that by removing this command from the Base command you are removing it for everyone. If that is your intention, go ahrad.  :)

**Comment by Redstone-Pro-73** [comment]
Yup! I want it removed completely since I want it gone from everyone including staff.
