### ISSUE TITLE
Tab complete for commands does not support multi-word faction names

### ISSUE THREAD

**Issue by Bysokar** [MassiveCraft/Factions#1113]
Tab completion at the moment does not add _ characters (or quote the name) instead of spaces. This makes Tab completing a /f join "Protected Territory" command fail.

Not even remotely a priority. Just thought I'd report it.

**Comment by magnusulf** [comment]
Does "Protected Territory" tap complete to "Protected" when "P" is typed and to "Protected Territory" when "Protected T" is typed?
If so then that is the best we can do, due to how Mojang implemented tab completion.

**Comment by MarkehMe** [comment]
I don't think spaces are allowed in Faction names at all, so I can't replicate this 

```
>f create "Some Name"
[22:21:56 INFO]: Faction name must be alphanumeric. " " is not allowed.
```

**Comment by Bysokar** [comment]
Thanks for the prompt response lol
Manually specify the safezone name "Protected Territory" via config files with 2.8.10 factions and you can reproduce the issue. All good though... ive stopped working on this stuff haha
