### ISSUE TITLE
The issue #940 does'nt work !!! HELP

### ISSUE THREAD

**Issue by Donitovan** [MassiveCraft/Factions#1114]
Faction does'nt work with CAULDRON : [Factions v1.6.9.5] GSON lib not found WITH ALL version of Faction same with  all version of CAULDRON, KCAULDRON and THERMOS (URGENT) ! Thanks !

**Comment by MarkehMe** [comment]
v1.6.9.5 is not supported by MassiveCraft, please upgrade! 😱

**Comment by Donitovan** [comment]
DUDE, ALL VERSION DOESN'T WORK

**Comment by ulumulu1510** [comment]
There is absolutely no need to be rude here @Donitovan . Please state the following so we can investage your issue:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.

Note that we do not support old versions and we highly urge you to update MassiveCore and Factions to the newest version possible. (Currently 2.8.19)
