### ISSUE TITLE
Faction doesn't work with Cauldron

### ISSUE THREAD

**Issue by Donitovan** [MassiveCraft/Factions#1115]
Hello, I have a big problem with Cauldron, kCauldron and THERMOS,  faction plugin  does not work and the error mean : 

"Could not load 'plugins/MassiveCore.jar' in folder 'plugins" 
"Could not load 'plugins/Factions (20).jar' in folder 'plugins'" 
and with the old version of faction :
 "GSON lib not found. Your CraftBukkit build is too old (< 1.3.2) or otherwise not"

 pls, It's urgent I need this plugin ! thanks !

**Comment by ulumulu1510** [comment]
Please state your versions of:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of the full errors you have in console.
Note that we only support the newest versions of Minecraft and MassiveCore/Factions.

**Comment by Donitovan** [comment]
I use Thermos 1.7.10-1614 with the last version of faction and I tested all version of faction and cauldron / thermos and nothing works  (srrry for my english)

**Comment by ulumulu1510** [comment]
As I already stated, we do not support Cauldron or Thermos, as they are running very outdated versions of Minecraft. Also, you ignored a full section of my above post.

Describe detailed:

*What you did --> Running Thermos with a range of versions?
*What you expected to happen --> You probably want it running, correct?
*What actually happened. --> Not loading, any error in the logs? There must be errors.
Also, add screenshots/pastebins of the full errors you have in console. <==Most important,

**Comment by Donitovan** [comment]
http://pastebin.com/eehn2xm4
Srry, i don't speak english aswell

**Comment by ulumulu1510** [comment]
Now that I have this screenshot, I recognise that this is actually an issue in MassiveCore:
https://github.com/MassiveCraft/MassiveCore/issues/262
Marking as duplicate, please track your issue there.

**Comment by Donitovan** [comment]
Version "Factions 2.6.0 for 1.7.10 and 1.8 patch" works !
