### ISSUE TITLE
"homes Teleport To On Death Priority"

### ISSUE THREAD

**Issue by Twonox** [MassiveCraft/Factions#1119]
I would Fhome teleporting on death only in Factions worlds because in same server I have a PvPBox world where on death we mustn't respawn on faction home but in PvPBox's lobby.

Also, I have set `homesTeleportToOnDeathPriority` to `LOW` but we still respawn at Fhome. The players with a Fhome must do `/warp PvPBox` after death, it's not praticale.

Could you do something please ?

**Comment by ulumulu1510** [comment]
Bukkit Event Priorities can be a bit misleading at times. They actually call Event priority LOWEST first,  then LOW, NORMAL, HIGH and lastly HIGHEST and MONITOR.

Most plugins operate at NORMAL, so you might want to try to set it to above that. Unless we know exactly what priority PvPBox listens too (NORMAL or below is my guess), just try HIGH or HIGHEST and see whether that works for you.

That should almost definitely solve your issue. If it doesn't, please report back with a proper bug report where you state your versions of MassiveCore,  Factions and Spigot / Bukkit.

**Comment by Twonox** [comment]
MassiveCore version: 2.8.19
Factions version: 2.8.19
Server version: PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest

When I set priority to `LOW`, `NORMAL`, `HIGH`, `HIGHEST`, or `MONITOR`, nothings change.
When I set priority to `LOWEST`, I respawn to Spawn if Essentials respawn priority is set to `HIGH`, or `HIGHEST`, and to Multiverse spawn if Essentials respawn priority is set to `LOWEST`.

Could you change priority system to `worldsHomeRespawnEnabled` like `worldsPvpRulesEnabled` ?

**Comment by ulumulu1510** [comment]
Yes, we could in fact do that.  I'll reopen the issue and mark it as a feature request.

**Comment by ulumulu1510** [comment]
I didn't see that you made a request already, I'll close this again.
