### ISSUE TITLE
Add NPC compatibility

### ISSUE THREAD

**Issue by tomcraft** [MassiveCraft/Factions#1124]
Hello, I use your plugin and CombatTagPlus (https://github.com/MinelinkNetwork/CombatTagPlus/) on my server, but I have a request for you. When you save UUID of players when they are killed or some other stuffs like this, can you add compatibility to use the real player's NPC UUID and not the fake UUID of the NPC ?

It could be very useful for many people (like me), for exemple on ranking plugins uuid based wich use Factions json files to create a player classification.

Thanks :D

**Comment by ulumulu1510** [comment]
Please elaborate in more words what specifically you want to do/request. It is not clear to me what your goal is.

Our player storage system is a bit more complex than symplectic storing a UUID and we generally exclude NPCs from any of our "Collections". You would have to figure a way around it and ithe probably would be best to store those information yourself.

**Comment by tomcraft** [comment]
In the plugin I linked, NPCs represents a player when he deconnects during some seconds to bring possibility to other players to kill him, but as you said you doesn't store nothing about NPC. This is what I'm requesting you to do about NPC created by this plugin. There is a method to know the real player uuid of the NPC. Can you make a support for it to link to the good player storage ? (for kill data)

(I'm french it's possible that I'm not very clear in my sentences, so ask me ^^)

**Comment by MarkehMe** [comment]
So simply you are asking us to add support for those "In-combat and logs out" plugins? 😄

**Comment by MarkehMe** [comment]
Looks like its already being done by the plugin author? 

https://github.com/MinelinkNetwork/CombatTagPlus/commit/eb9a4865dac1af1b456825413526d8b362ceeb90

**Comment by tomcraft** [comment]
I don't thinks it's the same thing, The author said me it's to you to add
compatibility :/

**Comment by tomcraft** [comment]
But yes, this is EXACTLY what I am asking for :D

**Comment by ulumulu1510** [comment]
I disagree, it is his responsibility to hook into us.

Generally,  when there is no universal solution to compatibility with other plugins, they will have to implement their addition by hooking into our API.
There are a lot of different NPC plugins out there and the information which NPC represents which player is not stored the same in all of them. Thus there is no universal solution and he has to take action.

**Comment by tomcraft** [comment]
Ok :c

thanks

**Comment by Techcable** [comment]
I'm going to add compatibility to CombatTagPlus

**Comment by MarkehMe** [comment]
Great! Thanks @Techcable - I will close this ticket now.

**Comment by Techcable** [comment]
@Byteflux [thinks its your responsibility to do this](https://korobi.io/network/spigot/channel/techcable/logs/2016/07/20/#L57-96), and is removing my integration code.
Since he won't allow integration in, is there anything I can do on my side to make this easier?

**Comment by Techcable** [comment]
I've received further clarification from the author.
He's worried about the complexity of checking if people can attack each other.

For example, FactionsUUID's attack-checking logic is hardwired against an EntityDamageByEntityEvent and even then, it assumes players are online.
I had to [rewrite their logic](https://github.com/MinelinkNetwork/CombatTagPlus/blob/4533c07ca237f0d0d20a67960e8181fa9844fdf3/CombatTagPlusFactions-v1_6/src/main/java/net/minelink/ctplus/factions/v1_6/Voodoo.java) to remove the dependence  on NPCS, and modify it to support checking for offline players.

How difficult would it be to do this check with your code?

**Comment by ulumulu1510** [comment]
It seems we are passing the integration ball back and forth. I stay on my opinion. We have discussed such matters many times among MassiveCraft's Developement Team and we have decided to only provide hooks to other plugins if there is a general solution for all such plugins. Here, this is not the case.

For your second comment:
After checking that code quickly, we actually haven't that much of a difference there. As you probably know, FactionsUUID is only a 1.6.x version of our Factions modified to work with newer server builds.
We do practically the same, we check against an EntityDamageByEntityEvent  aswell. You can find this code [here in EngineCombat](https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/engine/EngineCombat.java#L94)

**Comment by Techcable** [comment]
Would you be okay if I refactored that to support offline players and not tie itself to EntityDamageByEntityEvent?

**Comment by ulumulu1510** [comment]
The method you see there is used for other purposes as well,  as you might be able to see. So you'd have to be carefull and test your solution throughfully. 

We are gladly accepting PR's, with the condition of them following our coding style and standards, as well as all functionality being present and tested. Your PR would probably need an iteration or two, as it is sometimes hard to get all code-stype related things right the first time. You can find the standard's here:
http://www.massivecraft.com/tech-standards

I am not the lead Dev,  so maybe @oloflarsson wants to say a word or two on the matter. Usually however, a well formated/styled and functional PR is high in its acceptance rate.
