### ISSUE TITLE
[Factions]Water and lava flow

### ISSUE THREAD

**Issue by Eragon0xs** [MassiveCraft/Factions#1125]
Hello,

I have a problem, when i put lava or water outside a claim she doesn't flow in the claim.

http://www.hapshack.com/?v=uzhxr.png

Thank's for your help

Sorry for my english :(
@greatman @derenix @sp1ky @AEtherSurfer @oloflarsson

**Comment by MarkehMe** [comment]
The default setting is to stop water from flowing into territories 

The configuration option you want to change is ```protectionLiquidFlowEnabled```

**Comment by Eragon0xs** [comment]
Sorry but i don't find it in my instance.json

**Comment by MarkehMe** [comment]
Ensure your Factions is up to date, mstore/factions_mconf/instance.json has ```protectionLiquidFlowEnabled```
