### ISSUE TITLE
/home working in enemy territory

### ISSUE THREAD

**Issue by plaincamron666** [MassiveCraft/Factions#1129]
Hey

/sethome is disabled in enemy territory. However, if people /sethome just outside enemy territory, then wait until the faction expands over their home and /home into it.

Ways to reproduce
1) /sethome outside of enemy faction claim
2) Wait until enemy faction grows over your home
3) /home into the enemy faction base
OR
1) Be a member of the faction
2) /sethome inside the faction
3) Get kicked from the faction
4) /home into the faction

I am having this problem a lot on my server.
/home shouldn't work if it is set in another factions territory.

Thanks.

**Comment by ulumulu1510** [comment]
As far as we are concerned, we did as much as we could. We are in no control over the commands behaviour, we can only disable it's execution in certain teritorries.

I believe it is Essentials that implements this /home command. You would have to direct this wish to them, as they control the behaviour and only them could potentially implement such a block.
