### ISSUE TITLE
Error getting the uuid

### ISSUE THREAD

**Issue by alex55132** [MassiveCraft/Factions#1133]
When i use the code `mplayer = MPlayer.get(uuid);`  gives me this error: 

> Error:(29, 34) java: cannot access com.massivecraft.massivecore.store.SenderEntity
>   class file for com.massivecraft.massivecore.store.SenderEntity not found

All the stuff is correctly imported, so i suppose it's a bug

**Comment by ulumulu1510** [comment]
Did you import MassiveCore aswell? For all our developement you need to import MassiveCore, as it has many of the fundamental classes to our code. I suppose you only have imported Factions.

Please state exactly which of our plugins you have imported in your IDE and maybe show a whole class if it is needed further.

**Comment by alex55132** [comment]
Lol it was that, thanks :3
