### ISSUE TITLE
I need help with the plugin ''Factions version 1.6.9.5 for minecraft version 1.5.2

### ISSUE THREAD

**Issue by Gonza215** [MassiveCraft/Factions#1134]
Hello all, as the title says i have a problem with the configuration of the plugin.
The problem is that when i configure the plugin, it is saved, but when the server restarts any change in the configuration it restarted as was previously set. I enter again in the configuration and nevertheless the configuration stay like the default plugin. 

I have no idea why this plugin only look red letters on the notepad. As with the others looks normal.
I think this has to do.
Link of the photo 1 (Proof 1): http://i67.tinypic.com/ivwu37.jpg

Honestly i have not idea how to get here. But it seems strange.
Link of the photo 2 (Proof 2): http://i67.tinypic.com/11rszue.jpg

When i opened that file... all it's normal (as it should be) 
But that file on the server has nothing to do.
Link of the photo 3 (Proof 3): http://i65.tinypic.com/293g1eb.jpg 

How can i fix it? Please anyone can help me?

I have another question someone knows how to translate this plugin to other idiom?

Thanks for your attention!

**Comment by MarkehMe** [comment]
⚠️  **Warning:**
---
Factions 1.6 was last updated over 3 years ago and is no longer officially supported! 

----

Thanks for reaching out! None of your images are loading for me...  can you use imgur instead? 

I suggest you try stopping the server before modifying the configuration files.

However, as this version of Factions is no longer supported I really recommend you upgrade as soon as you can.
