### ISSUE TITLE
Team Factions

### ISSUE THREAD

**Issue by Dcastle789** [MassiveCraft/Factions#1138]
Hi, I am currently making a Star Wars server, and I think it would be nice if the players can join either Rebels or Empire, but still be able to create individual factions. I'm requesting a feature that would allow you to join a faction team so you would be automatically nationed with them. Something like ./f create (name) (team) maybe? I know that I could just use another teams plugin that would not allow pvp between the teams, but I also have a ships plugin that allows you to bomb other factions that aren't nationed or allied.

**Comment by oloflarsson** [comment]
Couldn't you solve this by declaring yourself an ally to the Rebels or Empire factions? A full fledged "empire" feature with subfactions is not planned any time soon I'm afraid.
