### ISSUE TITLE
[Factions Dynmap] Not registering

### ISSUE THREAD

**Issue by webb1234** [MassiveCraft/Factions#1140]
Hi there,
I recently purchased Factions Dynmap & Factions Tax from Spigot,
I installed Factions Tax with no problem, and it registered, however
I also added the file Dynmap in my plugins folder (same location as
the factions tax plugin) and restarted, and it didn't recognise I had
installed it in-game with the command /f dynmap

It says "The extension FactionsDynmap isn't installed."
"Learn more and download the extension here:"
"http://www.massivecraft.com/factionsdynmap"

The file name is the same, no spaces or (1) or anything in the file, its the
same as how it come in the ZIP archive. maybe factions is looking for the
wrong file name, or it could be another issue, I am very confused with this.

Many Thanks,
Kieran Webb
(webbcraft on spigot)

**Comment by oloflarsson** [comment]
Have you installed the Dynmap plugin itself?
http://dev.bukkit.org/bukkit-plugins/dynmap/

**Comment by webb1234** [comment]
Yes, I purchased it and downloaded it, and placed the jar files into my server directory,

**Comment by webb1234** [comment]
server plugin directory*

**Comment by oloflarsson** [comment]
Did you purchase Dynmap? Or did you purchase FactionsDynmap? Dynmap is free and can not be purchased.

Please read:
Have you installed the Dynmap plugin itself?
http://dev.bukkit.org/bukkit-plugins/dynmap/

**Comment by webb1234** [comment]
I purchased FactionsDynmap off of this link:
https://www.spigotmc.org/resources/factionsdynmap.1914/

**Comment by MarkehMe** [comment]
@webb1234 what plugins do you have installed? We're trying to work out if you have Dynmap installed 😃 

_Dynmap_ and _FactionsDynmap_ are seperate plugins. 

You require _both_:

- The original Dynmap: http://dev.bukkit.org/bukkit-plugins/dynmap/
- FactionsDynmap: https://www.spigotmc.org/resources/factionsdynmap.1914/

Could you also supply some more information too? This will allow us to have a better understanding of your environment. 

- Do you have the original Dynmap installed?
- Do you have FactionsDynmap installed?
- What is your Bukkit/Spigot version?
- What is your MassiveCore Version?
- What is your FactionsDynmap Version?
- What is your Factions Version?
- Please provide a list of other plugins installed
- Please provide your server startup log, throw it on pastebin or an alternative paste service

**Comment by MarkehMe** [comment]
No response has been made and that usually happens when people solve the issue themselves. So I will close this issue.
