### ISSUE TITLE
Bug Description: PVP not working in Warzone on 1.10.2

### ISSUE THREAD

**Issue by MiniCraft12** [MassiveCraft/Factions#1141]
I have never had problems with Factions/Warzone PvP since I have upgraded to 1.10.2. When PvP is disabled in worlds.yml config in Multiverse-Core folder nobody can fight(not ops or default players) when they are within the Warzone. When PvP is enabled in worlds.yml config in Mutiverse-Core folder everybody can fight even in Safezone. I am not sure if it is a problem with Factions or Multiverse.

**Comment by MarkehMe** [comment]
Any easy way to determine the cause of the issue would be to disable Multiverse. If you can still fight in Safezone then check the flags of the SafeZone using ```/f flag safezone [flag] [yes/no]```

https://www.massivecraft.com/factions#flags

**Comment by MiniCraft12** [comment]
Is there an easy way of disabling multiverse without loosing all of my portals, worlds and configs?

**Comment by MiniCraft12** [comment]
Ok I didn't disable Multiverse but here is the result after doing /f flag show
![screen shot 2016-08-08 at 9 32 06 am](https://cloud.githubusercontent.com/assets/20526108/17481487/797ab8e0-5d4b-11e6-9ad5-d9aeb2d7320d.png)
 safezone.

**Comment by MarkehMe** [comment]
I would suggest duplicating your current server environment and testing on that.

**Comment by MiniCraft12** [comment]
That would require purchasing a new server which is pricy.

**Comment by MarkehMe** [comment]
You can run it on your own local computer.

**Comment by MiniCraft12** [comment]
Is there any other way of finding a solution using my current server?
Here are the plugins I currently use.
![screen shot 2016-08-13 at 5 06 00 pm](https://cloud.githubusercontent.com/assets/20526108/17645593/3bc0f470-6178-11e6-99da-a9c954ad8442.png)

**Comment by MarkehMe** [comment]
You can simply make a copy and test locally, I can't do this for you unfortunately (and don't have time to)
