### ISSUE TITLE
/f help

### ISSUE THREAD

**Issue by DataPools** [MassiveCraft/Factions#1143]
Where is the code for the /f help command located? 

-Thanks

**Comment by MarkehMe** [comment]
Please advise what you are trying to achieve. By modify MassiveCore you will find your builds will be forever out of sync. What you're trying to doing may be achieved by creating your own addon.

https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/command/MassiveCommand.java#L1012-L1016

**Comment by DataPools** [comment]
Currently trying to add some extra text to it. I've had an addon developed for Factions and I simply wanted to add some of its commands to /f help.

**Comment by MarkehMe** [comment]
Assuming you've extended ```FactionsCommand```, in the construction of the class use the method 
```java
this.setDesc("some command help here");
```
and your command will be added to the help lines automatically

**Comment by DataPools** [comment]
It is coded in a way so that it is an alias but doesn't extend FactionsCommand. The addon simply detects for a certain command to be typed.

Is there a way to manually add such a thing?

**Comment by MarkehMe** [comment]
Do you mean using PlayerCommandPreProcess? Thats a very hacky way to do it.

A simpler way is to extend FactionsCommand and then add it using ```CmdFactions.get().addChild(yourNewCommand);```
