### ISSUE TITLE
Adding a new faction perm?

### ISSUE THREAD

**Issue by yonatandeneke1** [MassiveCraft/Factions#1157]
Been having a bit of a struggle trying to add my own faction permission (ex. CONTAINER) with a MPerm. I can not seem to figure out a way to implement it. Any help?

**Comment by MarkehMe** [comment]
Please show how you are currently doing it

**Comment by Bysokar** [comment]
Example of how to create it (or get it) : https://github.com/StargateMC/Perimeter/blob/master/com/draksterau/Perimeter.java#L63-L65
Example of how to see if the player has it: 
https://github.com/StargateMC/Perimeter/blob/master/com/draksterau/eventListener.java#L72

**Comment by yonatandeneke1** [comment]
Thank you Bysokar!
