### ISSUE TITLE
My own modifications you could include in Factions

### ISSUE THREAD

**Issue by Xefir** [MassiveCraft/Factions#116]
Hello

I modified your mod to add small things I need for my own server and I'll be glad to share with you.
The first modifications will restrict players in factions to declare multiples factions as enemy, only one war at time.

Add this line to Conf.java :
	public static boolean onlyOneWarAtTime = false;

In FRelationCommand.java :
After :
		if (myFaction.getRelationWish(them) == targetRelation)
		{
			msg("<b>You already have that relation wish set with %s.", them.getTag());
			return;
		}
Add this :
		if (Conf.onlyOneWarAtTime && targetRelation == Relation.ENEMY && !myFaction.getEnemies().isEmpty()) {
			msg("<b>You can declare only one war at time !");
			return;
		}

In Faction.java add :
	public List<Faction> getEnemies() {
		ArrayList<Faction> enemies = new ArrayList<Faction>();
		for (Entry<String, Relation> relations : this.relationWish.entrySet()) {
			if (relations.getValue() == Relation.ENEMY && Factions.i.exists(relations.getKey())) {
				enemies.add(Factions.i.get(relations.getKey()));
			}
		}
		return enemies;
	}

The second modifications is to warn player that someone has declare war with his faction when the player log on in the server.
It's just show a sentence after the motd.

In conf.java add :
	public static boolean warnWarsOnPlayerLogin = false;

In FactionsPlayerListener.java add at the end of onPlayerJoin :
		List<Faction> factionsEnemies = me.getFaction().getEnemies();
		
		if (Conf.warnWarsOnPlayerLogin && !factionsEnemies.isEmpty()) {
			String chatEnemies = "";
			for (Faction enemy : factionsEnemies) {
				chatEnemies += enemy.getTag() + ", ";
			}
			if (!chatEnemies.isEmpty()) {
				event.getPlayer().sendMessage(ChatColor.RED + "You are currently at war with " + chatEnemies.substring(0, chatEnemies.length() - 2));
			}
		}

And change the property to EventPriority.MONITOR to make it compatible with mod like Essentials

Do what you want with this, I juste want to share my mods ^^
Sincerly,
Xéfir Destiny

**Comment by MarkehMe** [comment]
Thanks for your suggestions, a lot has changed since 2012 when this issue was opened - if you think you can add anything else simply open a PR. :+1:
