### ISSUE TITLE
FriendlyFire Enabled, unable to disable it.

### ISSUE THREAD

**Issue by Laos1996** [MassiveCraft/Factions#1161]
So my problem is as tittle follows, suddenly, players can hit each other even if they are in same faction, for example below faction flags;
https://gyazo.com/f58bbd24470826d8667bfca9727ecff1

Yet I am unable to hit member of same faction as I am. This happened randomly, I have not edited any config file  prior to this issue, only I edited factions_mconf but that was week ago and after that friendlyfire worked turned off just fine.

List of my plugins;
https://gyazo.com/78dafb0c9d952b550f7a47699c385580

EDIT:
I've restarted server, suddenly it started working again. I checked, theres no any errors in server log.

**Comment by MarkehMe** [comment]
Odd issue, happy you sorted it. If it returns let us know :)
