### ISSUE TITLE
FactionsUUID

### ISSUE THREAD

**Issue by Fraksimus** [MassiveCraft/Factions#1166]
Hey basically when I grant a factions peaceful, then when the players in the peaceful fac go pvp at spawn the chat spams with "can not hurt player in peaceful fac"

**Comment by ulumulu1510** [comment]
This is not the repository of FactionsUUID, take it to them if you got an issue.

Besides, this is the feature of peaceful factions, they can't pvp and thus don't receive damage from others....even if they are nothe in their own territory.
