### ISSUE TITLE
After Installing Factions the Is <> Before And After Everyone Whole Name!

### ISSUE THREAD

**Issue by BovBox** [MassiveCraft/Factions#1167]
Hey so after installing factions i was left to realize when people talked there was <> before and after there names. I have went to essentials chat config and took the <> out of there and then went over the faction config and did the same Examples below. 

Whats it looks like

<[Owner]; BovBox:> WTF is goin on

chat:
  radius: 0
  format: '{DISPLAYNAME}: {MESSAGE}'

Faction config:
"chatSetFormatTo": "{factions_relcolor}{faction_name|rp}f%1$s %2$s",

Hope you can help me out.

**Comment by BovBox** [comment]
Bump

**Comment by ulumulu1510** [comment]
First: Don't bump your issues, we will answer them if we have time to and not because you bumped that.

And to the second point I will get if I actually have time to look at your issue.

**Comment by BovBox** [comment]
Man your support team should be working on shit! its not our fault your config is fucking up and not allowing it and now your not answering or helping lol

**Comment by ulumulu1510** [comment]
Even though I would technically be able to help you, your attitude let's me revoke your rights to any answers I would have for you.

Go read the main guide, the config is explained there and you should manage yourself.

And btw, there is no "support team" and you definitly shouldn't show such an atitude on a project that is provided to you for free and without charge.

**Comment by BovBox** [comment]
Attitude? Lol must not kniw that answer to my question only reason someone wouldn't wanna fix there own plugins lol
