### ISSUE TITLE
Factions Prefix / PermissionEX Prefix

### ISSUE THREAD

**Issue by ElementalRealm** [MassiveCraft/Factions#1168]
Factions prefix is messing with the server's prefix. I use PluginsPerWorld in hope to solve that but it doesn't work. How can I solve it?

Thansk for your attencion,
- Elemental Realm Inc.

**Comment by ulumulu1510** [comment]
Please state your versions of:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console or ingame.

Have you tried to configure the part of the MConf to your liking? Especially the part which is about chat format?

**Comment by ElementalRealm** [comment]
Now i dont have none. I had the latest versions of each one (7 December was the day that i downloaded)
I installed the plugin.
I expect to the prefix from factions stays just on one world or that be able to disable their prefixes. I saw many tutorials to try to fix tht. I have removes the prefix from factions but i doesnt let the server to display the rank's prefixes. And yes I tryed to config MConf.

**Comment by ElementalRealm** [comment]
Now I removed the plugin and the folder created by it and the prefixes came back

**Comment by ulumulu1510** [comment]
"The latest version"  is not accurate enough, but anyways:

Try to disable factions chat formating as a whole and see if that helps as a quick fix. Then I'd research the different chat plugins that are out there, hopefully one that supports your prefixes from both permissions and faction's.

**Comment by MarkehMe** [comment]
You have to configure this in Essentials not Factions. Set **format** in **plugins/Essentials/config.yml** to something like:

```{factions_relcolor}{factions_roleprefix}&r&f{factions_name} &r{DISPLAYNAME}&r&7:&r {MESSAGE}```

And reload Essentials `/ess reload`
