### ISSUE TITLE
Stacktrace on /f

### ISSUE THREAD

**Issue by Tikkle** [MassiveCraft/Factions#1171]
http://pastebin.com/fezZSu3f

**Comment by MarkehMe** [comment]
Thanks you for reporting but we need some more information to help you! 

**Please state the versions of:**
* Factions
* MassiveCore
* Spigot

**Describe in detail:**
* What did you do for this to happen? 
* What did you expect to happen?
* What actually happened?

**Comment by Tikkle** [comment]
Factions 2.9.0
MassiveCore 2.9.0
PaperSpigot 983 for MC 1.11.1

What did you do for this to happen?
Dropped factions in the plugins file, started the server, executed the /f command.

What did you expect to happen?
The factions help menu to show up in chat

What Actually happened?
http://pastebin.com/fezZSu3f

**Comment by Tikkle** [comment]
@MarkehMe

**Comment by MarkehMe** [comment]
Is this still an issue?

**Comment by Tikkle** [comment]
Yes

**Comment by MarkehMe** [comment]
Can you validate your server and plugin information? Please supply the output of these 3 commands (run from console):

```
/version
/version massivecore
/version factions
```

Please also show a full list of other plugins installed too:
```
/plugins
```

**Comment by xion87** [comment]
i got  the same issue 
This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

MassiveCore[0;37;1m version [0;32;1m2.8.21[m

Factions[0;37;1m version [0;32;1m2.8.21[m

**Comment by xion87** [comment]
any news?

**Comment by MarkehMe** [comment]
I'm confused as to why your server is returning 1.8.8 but your code reveals you're running a 1.11.1 API?

Can you please explain your setup. There is something funky going on here

**Comment by xion87** [comment]
I am using 1.8.8 with viaversion

**Comment by MarkehMe** [comment]
Factions should be able to run against the 1.8.8 API. Can you configure it to allow the plugin to use regular API? 

I'm assuming (just by quickly looking at the trace) that your server is being detected as 1.11, and we're trying to send the newer message format but the 1.8 API doesn't allow this.

However the new message format was introduced in 1.9 so perhaps you could try ViaVersion on a 1.9 server? That would help us confirm.
