### ISSUE TITLE
Monster spawning flag -bug?

### ISSUE THREAD

**Issue by Whimsy85** [MassiveCraft/Factions#1172]
Got monsters spawning false and still there r spawnin in faction area.. mostly zombies -havent seen others spawning.

**Comment by MarkehMe** [comment]
Thanks you for reporting but we need some more information to help you! 

**Please state the versions of:**
* Factions
* MassiveCore
* Spigot

**Describe in detail:**
* What did you do for this to happen? 
* What did you expect to happen?
* What actually happened?

**Comment by Whimsy85** [comment]
Sorry, i was in a hurry..
So. i got 1.11 spigot server and that newest version of MassiveCore and Factions, 
[Server thread/INFO]: [MassiveCore] Loading MassiveCore v2.9.0
[Server thread/INFO]: [Factions] Loading Factions v2.9.0
No errors, no other problems.
I got big faction area with some dark spaces and these new zombie groups r spawnin there. So, that monster flag wont work on those zombies.

**Comment by sbrock** [comment]
Hiya! I'm also seeing this problem, unfortunately. Also Spigot 1.11 with 2.9.0 of Factions and MassiveCore.
Seeing zombies and zombie villagers spawning in areas where they shouldn't be.
thanks!

**Comment by oloflarsson** [comment]
You need to allow the configuration file to recreate. Delete the whole config or just the fields with the entity types. They are lacking the new Minecraft 1.11 values since your config was generated before.
