### ISSUE TITLE
not working with the latest spigot

### ISSUE THREAD

**Issue by sidboy55555** [MassiveCraft/Factions#1173]
Hi, Since I updated spigot to the latest version Factions and Massivecore are not working anymore, logs:
http://pastebin.com/a93f0bNE

**Comment by MarkehMe** [comment]
```
java.lang.IllegalArgumentException: /home/pp-factio_k0taq/public/../../../mstore/massivecore_multiverse does not exist.
```

You may want to contact your provider and get support with this. As it seems your server can't find the mstore folder.
