### ISSUE TITLE
VentureChat support

### ISSUE THREAD

**Issue by zerafox** [MassiveCraft/Factions#1176]
Venture Chat has recently replaced Herochat on our server, and it functions the same way with the exception of enabled JSON tooltips and Bungee support (We are not a bungee server).
However, Factions doesn't support [Venturechat](https://www.spigotmc.org/resources/venturechat.771/) it seems.

It would be wonderful if this support could be added to Factions so we could continue to enjoy the seamless integration between Factions and our Chat system.
In the meantime, I couldn't find any information on Faction's built-in chat commands?

**Comment by ulumulu1510** [comment]
We offered (limited) HeroChat support sicne we once used it ourselves. We are not of the opinion anymore that we can support any or all of the chat plugins out there.

If you want VentureChat to integrate well with Factions, you should go and ask their development team to add Faction features to their plugin. If they already do, you should probably turn off all chat features built into Factions and let VentureChat handle it.

To your last question: there are no built in chat commands for Factions.

**Comment by zerafox** [comment]
There is no commands to use a Factions or Allies chat built into factions?
Then I guess I don't understand why that section allows for a 'true' or 'false' and changing it one way or the other allows HeroChat to take control.

So I guess by default then, what you're saying, is Factions isn't packaged with a Factions chat at all.. It's just capable of providing one if you have a compatible chat plugin?
That kind of sucks..

**Comment by ulumulu1510** [comment]
Options are a different pair of shops than  "commands".

There are rudimentary chat features built in, such as adding a prefix when you speak. But other than that, Factions offers no Allies- or Faction-chat features. 

We do our best to keep the API consistent,  so that other developers don't have to change often. But no, we can't add integration's to all other chat plugins. They should rather integrate with us and give you more than just a ally and faction chat.

**Comment by MarkehMe** [comment]
Hey @zerafox! If the Factions plugin was to support every chat plugin ever created that would be _pretty chaotic_ for the MassiveCraft team to keep up with - as of already, it's a pretty huge plugin.

However! Good news for you, [VentureChat](https://www.spigotmc.org/resources/venturechat.771/) has built in support for Factions already - you can see this under the **Features** section:

> Factions channel: If you have Factions installed, create a channel called Faction and it will become the faction channel. 

Hope this answers your question! 😄

**Comment by zerafox** [comment]
You know I probably saw that on install of Venture Chat, and completely
forgotten...
Thanks for pointing it out.

**Comment by MarkehMe** [comment]
Happy to help!
