### ISSUE TITLE
Disband doesn't fire FactionsChunksChange Event

### ISSUE THREAD

**Issue by HappyHarm** [MassiveCraft/Factions#1178]
Hi, I don't know wether this is a missing feature or a bug but when you disband your faction the ChunkChange event doesn't get fired even when the faction owns some chunks. I'm trying to regenerate the wilderness chunks so it would be nice if I could get the old chunks from the disbanded faction somehow.

**Comment by MarkehMe** [comment]
So with your ```EventFactionsDisband event``` the Faction still exists at the point it is called.

So you can grab the `Faction` entity using `event.getFaction()`

Then use `BoardColl.getChunks(faction)`

Make sure you're listening last incase it gets cancelled.
