### ISSUE TITLE
Every single command's help description is "do that", but the plugin otherwise functions fine? (compiling from source)

### ISSUE THREAD

**Issue by argoms** [MassiveCraft/Factions#1180]
using latest spigot build (#55)
plugins:
worldeddit 6.1.15
worldguard 6.2
massivecore 2.9

factions compiled from latest master (https://github.com/MassiveCraft/Factions/commit/ad4ad7307fcbbaf06624c66b9e5f880df253309b)

only change being
```
main: ${project.groupId}.${project.name}
name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [Cayorion, Madus, Ulumulu1510, MarkehMe, Brettflan]
```
changed to

```
main: com.massivecraft.factions.Factions
name: OverFactions
version: 2.90
website: hopefullyidontneedthis.com
description: messing with factions
authors: [Cayorion, Madus, Ulumulu1510, MarkehMe, Brettflan]
```

As far as I can tell, everything is working fine, *except* that when I type '/f help', the description for every command is "do that". /help worldguard and /help worldedit have their normal descriptions/help text. Searching through all the code, I can't find any instance of the string "do that", so unless it's some strange default value, I can't really tell why this is happening.

**Comment by magnusulf** [comment]
If you use the latest version of Factions compiled from GitHub you should do the same for MassiveCore. Those two versions are incompatible.

**Comment by Mikgreg** [comment]
Happens for me too. Downloaded latest zip from Spigot page.
https://vgy.me/lLohWv.png

**Comment by MarkehMe** [comment]
@Mikgreg is this still an issue? Your versions of Factions and MassiveCore should be the same as well.
