### ISSUE TITLE
Bug with hoppers

### ISSUE THREAD

**Issue by Neverlookbackgrg** [MassiveCraft/Factions#1183]
I am using version 2.8.0 for my 1.8.8 server the problem i am encountering is that if i put a hopper on a claimed land etc a players land,safezone,warzone the hopper won't work to drop items on chest only hopper to hopper.If i go to the wilderness it will work correctly do you have any idea why that is happening?

**Comment by MarkehMe** [comment]
Sorry for the slow response with this, there could have been a potential bug that wasn't picked up. But if it still exists in 2.10 we can take a look at it. 

Is this still an issue? 

If so, please provide more information - plugins, MassiveCore version, Factions version, etc
