### ISSUE TITLE
[Feature Request] Adding an "@" feature to allow only that faction to see your chat - Explained in comment.

### ISSUE THREAD

**Issue by Shlobdon** [MassiveCraft/Factions#1184]
Having an Ally chat is awesome! You can talk to all of your allies in one chat without spamming everyone else. However, there is one flaw.

If your allies are allied with one of your enemies, and they're having a convo, you only see your allies side...

So, we'll use the Faction name: Grandar for example.

Grandar and my allies are speaking. I'm seeing half of the conversation. But, if my allies used "@Grandar" before their text, like so: "@Grandar blablablabla" only Grandar and allies w/ Grandar will see their chat.

Thus, preventing X faction that is enemied w/ Y faction being left out of the chat carried on by the Z enemies. 

Hope this is possible?

**Comment by MarkehMe** [comment]
This is something that would have to be implemented into a chat manager (like VentureChat, or HeroChat). Unfortunately there is not much we can do here.
