### ISSUE TITLE
Teleportation for claim enemy

### ISSUE THREAD

**Issue by BigMrBad** [MassiveCraft/Factions#1186]
Is happening a bug, that, I hedge home in a neutral or ally terrítório. When the faction you claimed makes me an enemy, I can still teleport to my home, even the territory being an enemy. How to fix?

**Comment by ulumulu1510** [comment]
Please state your versions numbers of:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.

**Comment by MarkehMe** [comment]
This issue hasn't been responded to for 4 weeks, so I'm going to close it.

If there is still an issue you can let us know.
