### ISSUE TITLE
Claim bug

### ISSUE THREAD

**Issue by gamer4020** [MassiveCraft/Factions#1187]
Everytime i try to claim a land it says "can't afford 1$ to buy this land."

**Comment by ulumulu1510** [comment]
You have turned the economy feature on probably. Try turning it off and see if that helps.

If not, please make a detailed bug-report.
Please state your versions of:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console.

**Comment by MarkehMe** [comment]
This issue hasn't been responded to for 3 weeks, so I'm going to close it.

If there is still an issue you can let us know.
