### ISSUE TITLE
[Request] Renting land

### ISSUE THREAD

**Issue by edrocks4u** [MassiveCraft/Factions#119]
Well i would like you to add the renting of land for x days for x price and be able to set this per plot with something like "/f claim rent pricePerDay". I would also like this one two levels one for unclaimed land, and one for land a faction owns which it would be renting to its members which would give them /f owner for the land. Also possible if you don't mind it would be nice if you added a limit to how many pieces of land a faction could rent like + 1 for every member. This would help me for making a shopping district so people with lots of money can't rent the whole district.

**Comment by MarkehMe** [comment]
Check out https://www.massivecraft.com/factionstax
