### ISSUE TITLE
Feature: Per world command limitation

### ISSUE THREAD

**Issue by SlimeDog** [MassiveCraft/Factions#1192]
I would like to limit the worlds in which Factions commands are legal, without resorting to PerWorldPlugins.

**Comment by MarkehMe** [comment]
Hey! Sorry for the late response on this. 

You can do this with your permissions plugin, as Factions is heavily permission-based you can deny all commands or just some. 
You can actually [find them in the plugin.yml file](https://github.com/MassiveCraft/Factions/blob/master/plugin.yml#L9-L281).

If just just want to disable claiming you can alter `worldsClaimingEnabled`

**Comment by SlimeDog** [comment]
I was under the impression that factions permissions were handled in mstore/*. No?
