### ISSUE TITLE
Bug with the / f command

### ISSUE THREAD

**Issue by Acenox** [MassiveCraft/Factions#1194]
Hello,

I am a developer of a minecraft server and I noticed a bug with the command / F f, so we notice on the screen: https://www.noelshack.com/2017-08-1487711712-2017-02-21-22-10-48.png
That there is a pseudo with numbers, but I do not know if this is a bug or if this is normal? Can we solve it?

Thank you :)

Sincerely, Acenox

**Comment by ulumulu1510** [comment]
These "pseudo numbers" are actually the palyers id.

That is actually not a bug, but apparently this ids "resolve" data got wiped at some point (either manually or by error). It should resolve itself the next time this player logs on.

If this occurs often, please watch out for console errors and send them towards our way. If anything should indeed be wrong, the console will mention it.

Regards, Ulumulu1510
