### ISSUE TITLE
API ? 

### ISSUE THREAD

**Issue by Rocologo** [MassiveCraft/Factions#1195]
Hi, 

I'm the developer of [MobHunting](https://www.spigotmc.org/resources/mobhunting.3582/). I want to hook into Factions and deny the MobHunting users to get rewards when they are in a Faction SafeZone and protected against Mob attacks / player attacks.

I have been looking for an API but I didnt find any, but maybe you can help? 

When the EntityDeathEvent is fired I examine a lot of stuff to check if the kill should be rewarded. So I a way to detect if the player is in a SafeZone and if he is protected against attacks from mobs/pvp? 

I'm pretty sure you have the methods, I just need to find them? :-)

**Comment by ulumulu1510** [comment]
You can use the BoardColl to fetch the faction they are standing in:
https://www.massivecraft.com/factions-develop

Faction faction = BoardColl.get().getFactionAt(PS.valueOf(player));

From that you can check if this faction has the flags set like: 
faction.getFlag(MFlag.getFlagMonsters())
faction.getFlag(MFlag.getFlagPvp())

This will return a boolean, true means the flag is active, false means it is inactive.

**Comment by Rocologo** [comment]
Thank you, got it. 

I found the two flags. I hoped for a flag like WorldGuards "mob-damage". MFlag.Monsters is only if they spawn, not about if they can do damage. And the same is MFlag.PVP is not about the damage, only about if PVP is allowed.

**Comment by Rocologo** [comment]
I got to work now.  Thank you for your help.

Support for factions will be added in my next release of MobHunting.

**Comment by ulumulu1510** [comment]
Nice to hear that :). We are always happy if a plugin integrates with us well.
