### ISSUE TITLE
Factions Prefix Tag Not Working

### ISSUE THREAD

**Issue by XKPlayzYT** [MassiveCraft/Factions#1203]
Hello there! I am currently having trouble with making the factions name show in the chat when someone talks and I have EssentialsChat making the ranks talk in color chat. We are using Factions, FactionsChat, and EssentialsChat together.. Can I have some help please?

**Comment by MarkehMe** [comment]
Sadly, I don't have any experience with FactionsChat. But I'll put it on my list of things so I can provide better help in the future! 

If you want to use EssentialsChat you need to first disable it in the factions configuration first, change `chatSetFormat` to `false` - you only want this enabled if you're a small server with no chat manager. 

But from memory there are a few ways to add your tags. How are you currently formatting messages? With your permissions plugin, or through the Essentials plugin?

You should do it through your Essentials plugin by modifying the `plugins/Essentials/config.yml` file.

Set the default format by modifying the `format` variable. You can [find the tags here](https://www.massivecraft.com/factions-configure#chat-format-tags) under "**Chat Format Tags**"

See their documentation for more information:
http://wiki.mc-ess.net/wiki/Chat_Formatting#Chat_Formatting
