### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by caesar700** [MassiveCraft/Factions#1207]
faction format works on all world.. i want it on only factions world i tried per world plugins it worked.. but not the chat... PLEASE FIX THIS

**Comment by MarkehMe** [comment]
Hi! I'd love to help, but you have provided no information so I am really struggling to fully understand your issue. 

Are you using a chat plugin or the in-built formatting? It sounds like you want to use a chat plugin, as the in-built formatting is only for small scale servers that don't want complex options. 

What version of Factions and MassiveCore are you using ("latest" is not helpful, type **/version factions** and **/version massivecore** into your console).

Can you share your factions mconf? 

I would suggest using HeroChat or VentureChat  as chat plugins which both work very well.

**Comment by ulumulu1510** [comment]
No information has been provided for an entire month and no conversation was started. We can't help fixing issues when we are not talked with.
