### ISSUE TITLE
Raiding

### ISSUE THREAD

**Issue by Lion048** [MassiveCraft/Factions#1208]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.8
- **MassiveCore Version:** Latest

## Describe your environment

- **Spigot version:** CraftBukkit version git-Spigot-550ebac-7019900 (MC: 1.8)
- **Config pastebin:** 

## Steps to reproduce this bug

  1. First, I was raiding a base with my faction members. I couldn't destroy the land with tnt or creeper eggs.
  2. Next, I looked in the config and I saw nothing about this.
  3. Finally this happened.

**Observed results**

**Expected results**

I wanted to be able to use tnt and creeper eggs to destroy claimed land

**Comment by Legoman99573** [comment]
???
