### ISSUE TITLE
Dependences

### ISSUE THREAD

**Issue by BigMrBad** [MassiveCraft/Factions#1209]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.10
- **MassiveCore Version:** 2.10

## Describe your environment

- **Spigot version:** 1.8.8
- **Config pastebin:** 

## Steps to reproduce this bug

  1. I want translate this plugin for my linguage.
  2. I downloaded the code and put in the Eclipse to edit, but most classes have errors.
  3. I did not change anything, but there are the errors, probably some missing dependencies or something.
  4. I wanted to request the list of dependent plugins to be able to edit without errors for version 1.8.8 of minecraft.

**Observed results**
Prints: http://prntscr.com/ev79p9 , http://prntscr.com/ev79um , http://prntscr.com/ev7a2p , http://prntscr.com/ev7b74 , http://prntscr.com/ev7bib , http://prntscr.com/ev7cmg

I tried to use the JD-GUI to see if it was something to download the code but to no avail.

**Expected results**
I need it to be error-free so I can edit it.

**Comment by imaBASKET** [comment]
download the sources for massivesuper, massivecore along with factions

Look in pom.xml for massivesuper and you should see how it has commands listed to install dependencies, do those (you make have to surf the web too find the .jar file to download the dependency because a lot of the websites that those commands go to aren't there anymore :( )

then run "mvn clean install" in massivecore

change whatever you want in factions

mvn clean install in the factions folder.

**Comment by BigMrBad** [comment]
But this method is for Netbeans or Eclipse?

**Comment by imaBASKET** [comment]
it should work for either one. You need Maven installed to build and install it's dependencies.

To go into more detail with what I am talking about:

Inside the pom.xml for MassiveSuper it will have dependencies listed along with commands to install the dependencies

Like so:
mvn install:install-file -DgroupId=com.dthielke.herochat -DartifactId=Herochat -Dversion=5.6.7-SNAPSHOT -Dpackaging=jar -Dfile=HeroChat.jar

What you need to do is have a folder which has all of the dependent jar files (such as herochat) and run the commands needed to install them (in the folder which the jars are in)

There may be some dependancies which do not have a command listed. If that is the case you are going to need to create the command for yourself. For example, MassiveCore does not have it's install command listed. So what you are going to need to do is look at how it is listed as a dependancy.

```
            <dependency>
                <groupId>com.massivecraft.massivecore</groupId>
                <artifactId>MassiveCore</artifactId>
                <version>${project.version}</version>
                <scope>provided</scope>
            </dependency>
```

In this case we will use that herochat command as an example.

Just replace the information with MassiveCores, and for your information the version of MassiveCore currently is 2.11-SNAPSHOT. So what you will get is:

> mvn install:install-file -DgroupId=com.massivecraft.massivecore -DartifactId=MassiveCore -Dversion=2.11-SNAPSHOT -Dpackaging=jar -Dfile=MassiveCore.jar

Do this for ALL of the dependencies listed in factions pom.xml

**Comment by BigMrBad** [comment]
Is very complicated kkkk
But i believe.
I understand all, but this don't work: http://prntscr.com/evk3ze
I opened the cmd and run the command. I need have the plugin in the System32 folder?

Sorry for my bad English, I'm Brazilian :P 
If you want, add me on the skype for questions and answers more fast: live:mrbadxd

**Comment by imaBASKET** [comment]
dont put anything in your system32 folder. do this in a folder on your desktop or something.

**Comment by BigMrBad** [comment]
Let's go. I make it: http://prntscr.com/evowm2 less with the spigot.
A example:
`mvn install:install-file -DgroupId=com.sk89q.worldguard.bukkit.WorldGuardPlugin -DartifactId=Worldguard -Dversion=6.1-SNAPSHOT -Dpackaging=jar -Dfile=worldguard-6.1.jar`
Now, I need to put the MassiveCore, MassiveSuper and Factions all under one folder. Do I need to download the .jar of all or the src code? Does it need to be inside a folder or a .zip?

**Comment by imaBASKET** [comment]
You download the sources off here from github

You put each one in their individual folders however they need to be within the same folder (if that makes sense) For example, in your "Pls" folder you would also have a MassiveCore and Factions folder in it.

Once all your dependencies are installed (not MassiveCore yet) You need to build MassiveCore.
In the MassiveCore folder run this command:

> mvn clean package

Then once that is done you will need to install that MassiveCore, that can be done with one of the commands in my previous comments.

Please know that you MUST "install" the MassiveCore that you built yourself. Do not use a downloaded version from say spigot because it will not work.

If you did install a downloaded version of it, goto:
C:\Users\(username)\.m2\repository\com\massivecraft

And delete the MassiveCore folder, then reinstall it using the one you built!

Once that is done you should be able to simply run:
> mvn clean package
in the Factions folder, and that will build factions.

**Comment by BigMrBad** [comment]
Okay, to make sure I've downloaded the sources correctly, their names are "Factions-master" and "MassiveSuper-master"?
You just need those two?
I had installed MassiveCore and deleted it.
Look: http://prntscr.com/ew0c5o
Can I run the command?

**Comment by imaBASKET** [comment]
Looks like you should be good to go

**Comment by BigMrBad** [comment]
Failure: http://prntscr.com/exjll6

**Comment by imaBASKET** [comment]
You're suppose to run the command in the Factions folder.

**Comment by BigMrBad** [comment]
Another eeror: http://prntscr.com/eyvx3m
Can you send me this part already made for me?

**Comment by imaBASKET** [comment]
I can't make this part for you because you wouldn't be able to build the plugin with the changes you've made.

Send a screenshot that shows whats in the folder "pls"

**Comment by BigMrBad** [comment]
Ok.

Folder "Pls": http://prntscr.com/eywm2j
Under of the "Factions-master": http://prntscr.com/eywmf7
Under of the "MassiveSuper-master": http://prntscr.com/eywmmz

**Comment by imaBASKET** [comment]
Rename MassiveSuper-master to "MassiveSuper"

**Comment by BigMrBad** [comment]
On the beam.
http://prntscr.com/eyx8l6
I don't know now.

**Comment by imaBASKET** [comment]
You have to install the depencendies listed in that error.

**Comment by BigMrBad** [comment]
I maked. But, the same error: http://prntscr.com/eznjmt
I did the same process with the dependencies that were in print. But it did not work.
One of the mistakes is "MassiveCore", but we're creating it, right? I'm confused.

**Comment by imaBASKET** [comment]
Download these jars from somewhere online:
WorldEdit 6.1.5-TEMPFIX
LWC 1.7.9

Also download the latest MassiveCore source, put it in the folder where you have MassiveSuper, and MassiveCore and build it

Then run the install commands for all 3 of those.

**Comment by BigMrBad** [comment]
I found it: http://builds.enginehub.org/job/worldedit/9404 is the next of the "WorldEdit 6.1.5-TEMPFIX". I did not find "WorldEdit 6.1.5-TEMPFIX".
If you have, send me, please.

**Comment by imaBASKET** [comment]
You can use that, but change the world edit version in the pom.xml to point to worldedit 6.1.5

**Comment by BigMrBad** [comment]
Well, another error: http://prntscr.com/ezp1z2 is hard :/

**Comment by imaBASKET** [comment]
You need to be in the MassiveCore folder and run mvn clean install

Download the worldedit jar and rename it to WorldEdit 6.1.5-TEMPFIX

**Comment by BigMrBad** [comment]
Finally: http://prntscr.com/ezpo4e
And now? What to do?

**Comment by imaBASKET** [comment]
Make sure you are able to build factions without making any changes to it by running the "mvn clean package" command in the Factions folder.

If you are able to and it successfully builds then use a program like NotePad++ or an IDE to edit the .java files to your liking.

**Comment by BigMrBad** [comment]
Failure: http://prntscr.com/ezw3vq
What to do?

**Comment by imaBASKET** [comment]
Goto
C:\Users\USERNAME\.m2\repository\com\massivecraft

Delete the MassiveCore folder

Then go back to where you have MassiveCore.jar (The one which you BUILT)
Run this command

> mvn install:install-file -DgroupId=com.massivecraft.massivecore -DartifactId=MassiveCore -Dversion=2.11-SNAPSHOT -Dpackaging=jar -Dfile=MassiveCore.jar
Then go back to the Factions folder
run:

> mvn clean package

**Comment by BigMrBad** [comment]
`Goto
C:\Users\USERNAME.m2\repository\com\massivecraft

Delete the MassiveCore folder`
I did.

> Then go back to where you have MassiveCore.jar (The one which you BUILT)
Run this command

mvn install:install-file -DgroupId=com.massivecraft.massivecore -DartifactId=MassiveCore -Dversion=2.11-SNAPSHOT -Dpackaging=jar -Dfile=MassiveCore.jar
I did.

> Then go back to the Factions folder
run:
mvn clean package
I did.

The same error: https://hastebin.com/qaruxamone.tex

**Comment by imaBASKET** [comment]
Goto (If its there)
C:\Users\ username \ .m2\repository\com\sk89q

Delete the worldedit folder

Download this jar:
https://dev.bukkit.org/projects/worldedit/files/956525/download
Make sure the Jar file is named:
worldedit-bukkit-6.1.5.jar

Run this command while in the folder of the downloaded jar file

> mvn install:install-file -DgroupId=com.sk89q.worldedit -DartifactId=worldedit-bukkit -Dversion=6.1.5-TEMPFIX -Dpackaging=jar -Dfile=worldedit-bukkit-6.1.5.jar

Now run this command in factions folder:

> mvn clean package

**Comment by BigMrBad** [comment]
YEEEY!!!
http://prnt.sc/ezxscu
http://prnt.sc/ezxvpk
http://prnt.sc/ezxw3s
http://prnt.sc/ezxwvv
Working :)

Thx for patience!
Now, I'll translate it.

**Comment by imaBASKET** [comment]
No problem, if you need any help let me know.

**Comment by BigMrBad** [comment]
Sure, I'll keep open this Issue for future problems.

**Comment by BigMrBad** [comment]
How to translate the commands? In version 2.8 are easy.
And how to resolve the unicode? Look: http://prntscr.com/f01zli

**Comment by imaBASKET** [comment]
I'm not 100% on how to change the command names, I've never done that before but I believe you will have to rename them in CmdFactions.java

As for the unicode accents, I'm not 100% sure either. I did some research and found this:
https://stackoverflow.com/questions/11058470/composing-unicode-characters-in-java

> String s = "a" + "\u0300"; // latin lowercase letter a + combining grave accent
char combining_grave_accent = '\u0300';

**Comment by BigMrBad** [comment]
Thanks.
What happened here? http://prntscr.com/f08wx5

**Comment by MarkehMe** [comment]
The command names are automatically generated based on the class name. But you can override these, in the constructor use:

```java
this.setAliases("bunch", "of", "aliases");
```

**Comment by BigMrBad** [comment]
I got it!
Thanks for all who helped me!
