### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by mrblake213** [MassiveCraft/Factions#1210]
I only have one question.

We found a way to sell the /fly permission to users but it would be cheating if they can fly everywhere.
We would like it if they can only /fly in claimed lands.

Ex:
A player activates his /fly in his faction land and if he exits that land and enters another land/Safezone/Warzone and Wilderness then he will drop and his /fly will be disabled.

Is it possible?

**Comment by imaBASKET** [comment]
add it the list of blocked commands for other territories, however that wont make it so they loose fly if they leave their own territory.

My fork of factions (on my profile) has territory based fly.

**Comment by ulumulu1510** [comment]
You would need to create a little plugin that handles this behaviour. There is (as described) only a method to block commands in certain territory.
