### ISSUE TITLE
StackTraces | Factions

### ISSUE THREAD

**Issue by SnakeDaoust1232** [MassiveCraft/Factions#1211]
1) https://gyazo.com/c0f5e8790818bad419ea334b9e7c69e1
2) https://gyazo.com/2fb1100ba8fc0eb7ad58e712c4995e68
3) https://gyazo.com/5f3359d9055ed0c16b8390c79278a7ac

Factions v2.10.0
MassiveCore v2.10.0
Spigot Version: TacoSpigot 1.8.8 (https://tacospigot.github.io/)
Config: https://hastebin.com/ikiricokun.json

**Comment by ulumulu1510** [comment]
This issue seems similar to the one we encountered when filepaths included a space. This has been fixed in 2.12.1.

Please update to 2.13 and open a new report following the given format if the error persists.
