### ISSUE TITLE
Stacktraces From My Plugin

### ISSUE THREAD

**Issue by TidesVI** [MassiveCraft/Factions#1212]
## Affected Plugin

- **Affected Plugin Name:** Factions and My Custom ones
- **Affected Plugin Version:** 2.10.0
- **MassiveCore Version:** 2.10.0

## Describe your environment
- **Spigot version:**1.11.2

## Screenshots
- http://prntscr.com/f3w3ir
- http://prntscr.com/f3w3nh

## Steps to reproduce this bug

1. Basically when I try getting players from a faction, or a faction by fID/name it says whats at the bottom. or just throws a npe.

Another bug: (idk why but this shouldn't be happening)
1. Or it says it when I try getting online players in a faction. It says all the players are null. and yes I make sure the faction is not null.

it always says this ↓
[00:50:39] [Async Chat Thread - #0/INFO]: [Factions 2.10.0] Non existing factionId null requested. Cleaning all boards and mplayers.

**Comment by MarkehMe** [comment]
Sorry, third party forks are not supported by us. Please use the original jar.
