### ISSUE TITLE
Problem with relation colors - With DeluxeChat

### ISSUE THREAD

**Issue by Mikeyqwerty** [MassiveCraft/Factions#1213]
Hi, i am currently using both DeluxeChat with Factions 2.10.0. 
When the factions plugin has been hooked into DeluxeChat, i have used the placeholders as follows, http://prntscr.com/f5673p. Upon typing in chat with an Allied Faction, this happens, http://prntscr.com/f567gi. The allied factions name and role with be colored correctly, whereas my own faction will be left in the neutral color of white, whereas it should be colored green. I was wondering if you knew what the problem was, and if there was a way to fix it.

**Comment by ulumulu1510** [comment]
I highly suspect an issue in the chat plugin you are using, maybe they have used a non-standard method to determine the relation color? Please forward this issue (with a little more information to your setup) to the developer of DeluxeChat. If he needs any help, he can come back here and ask what is needed.
