### ISSUE TITLE
Modded Containers

### ISSUE THREAD

**Issue by Andrew2070** [MassiveCraft/Factions#1214]
Hi.

Before you decide to close this and refer me to a closed issue, i would like you to carefully read this. My problem relates to the main config file where the containers, doors and tools are listed.

I am using Thermos for my server which is basically a runoff from Kcauldron.
Thus I wish to use factions with mods, so that people can't run into claims and steal stuff.
However the problem lies in listing all these blocks into factions.

I have spent hours just listing each and every container, door and tool into the json file.

My confusion: 
1. Do i use bukkit names like this "OPENCOMPUTERS:TRANSPOSER"
2. Or do i use them like this "OPENCOMPUTERS_TRANSPOSER"

I got it to work before, i just forgot how.

**Comment by Andrew2070** [comment]
The 1st one returns nulls in all cases.
The 2nd one returns a null when the server is run without mods.

**Comment by ulumulu1510** [comment]
It really depends on how Thermos handles materials. Maybe it is only "TRANSPOSER".

The datastructure used allows you to use any material, even i it is not a bukkit material or a material for the matter. If that is not the case and you actually run into issues like this, you should make a full on report (with the provided structure) and we shall look into your problem.
