### ISSUE TITLE
I lose my faction after a relog or a /rl 

### ISSUE THREAD

**Issue by LicorneCosmique** [MassiveCraft/Factions#1217]
Hi guys,
When i reload the server or when i leave it and join it back i lose my faction. It's still in the /f list but i'm not in... 

Here is my logs :

https://pastebin.com/s87ah3bu

**Comment by MarkehMe** [comment]
There is this error message:

```User limit of inotify instances reached or too many open files```

You need to increase the "Open Files Limit": https://easyengine.io/tutorials/linux/increase-open-files-limit/

You should ask your system administrator or service provider how to do this

Also! Reloading can have bad consequences with most plugins.
