### ISSUE TITLE
I loose my faction everytime i logout

### ISSUE THREAD

**Issue by LicorneCosmique** [MassiveCraft/Factions#1218]
Hi,
Everything is in the title... 
Here is the error 
https://hastebin.com/evubijebul.swift

**Comment by LicorneCosmique** [comment]
https://hastebin.com/evubijebul.swift

**Comment by LicorneCosmique** [comment]
Any help please ?

**Comment by ulumulu1510** [comment]
Please use the appropriate form and include as much information as possible. Re-open the issue after you have collected that data.
