### ISSUE TITLE
Players can not open chests in other Factions' lands

### ISSUE THREAD

**Issue by Dakotaa** [MassiveCraft/Factions#1222]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.11.0
- **MassiveCore Version:** 2.11.0

## Describe your environment

- **Spigot version:** Paper version git-Paper-1104 MC 1.11.2-R0.1-SNAPSHOT
- **Config pastebin:** https://pastebin.com/NZbbZUPj

## Steps to reproduce this bug

  1. Join a faction
  2. Go into another Faction's land
  3. Try to open their chests, it tells you that they do not allow you to do that.

**Observed results**
When players try to open chests or any other container in other Faction's land, it tells them that they do not have permission for that. They were able to open these chests before I updated to the latest version of the plugin.

**Expected results**
I would like a change to this so that players can open chests in faction land as they could before.

**Comment by ncf1** [comment]
i dont know shit about coding or previous versions but i do know that there are permissions for things like this in /f perm

you could try to /f perm set container neu yes, which i believe would SET the permission for NEUTRAL factions to interact with that factions CONTAINERS. this should allow factions with the relation neutral to open containers of the faction whos perm you set to "container neu yes"

if this works as intended, you would then take this a step further by defining the appropriate settings in mstore/factions_mperm.json by adding 

"NEUTRAL",

to the standard. i believe this would give all neutral relation factions the permission by default to open  chests in newly created factions. i would test this for success. if it works as you desire, you could then add enemy or any other relation you wish to have access to chests in the same fashion

i hope this is helpful and correct and apologize if it isnt, here is how i believe your container.json would look before and after

{
  "priority": 6000,
  "name": "container",
  "desc": "use containers",
  "standard": [
    "LEADER",
    "OFFICER",
    "MEMBER"
  ],
  "territory": true,
  "editable": true,
  "visible": true
}

vs 


{
  "priority": 6000,
  "name": "container",
  "desc": "use containers",
  "standard": [
    "LEADER",
    "OFFICER",
    "MEMBER",
    "RECRUIT",
    "ALLY",
    "TRUCE",
    "NEUTRAL",
    "ENEMY"
  ],
  "territory": true,
  "editable": false,
  "visible": true
}

**Comment by Dakotaa** [comment]
I have done that, which kinda fixed the problem. Factions that are created can how have their chests opened, but old factions, that existed before the problem starts, still have their perms set to not allow chest opening. Is there a command to set a perm for all factions at once?

**Comment by ncf1** [comment]
that is beyond my knowledge level

as admin you can probably manually edit each, working slowly through the /f list but there very well could be a way to target all factions to save yourself that effort. good luck

**Comment by ulumulu1510** [comment]
There is indeed no command to set a perm for all factions at once, this is what the json configs are there for. 

Be carefull by changing the json configs for flags, making them uneditable is sometimes a good idea, but it really depends on what you are looking for. If the players should still be able to decide which relations they allow to build, you can't make uneditable=true.
