### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by chistian95** [MassiveCraft/Factions#1223]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.11.0
- **MassiveCore Version:** 2.11.0

## Describe your environment

- **Spigot version:** 1.12-R0.1-SNAPSHOT

## Steps to reproduce this bug

  1. Install the plugins and restart the server.
  2. Create a faction.
  3. Restart the server again.

**Observed results**
The plugin fails to load if there is any player data file in /mstore/factions_mplayer
If I delete all the json files in there, the plugin loads again.
Here is the error: https://pastebin.com/qAbLx2hy
MassiveCore prints an error too (does not matter if I have player data or not), but it seems to be working fine: https://pastebin.com/cPXY5Smd

**Comment by TheIntelloBox** [comment]
Factions isn't compatible with 1.12 right now.

**Comment by MarkehMe** [comment]
Stay with 1.11 for now.

**Comment by Dragorn421** [comment]
Someone (not me) is getting the same error when updating Factions to 1.12
https://pastebin.com/WR51Fhvz

**Comment by TheIntelloBox** [comment]
Yep.

**Comment by ulumulu1510** [comment]
Minecraft 1.12 compatibility has been added with MassiveCore 2.12. Please update to version 2.13 that has recently come out.
