### ISSUE TITLE
NPE @ string.replace

### ISSUE THREAD

**Issue by ncf1** [MassiveCraft/Factions#1224]
## Affected Plugin

- **Affected Plugin Name:** FactionsDynmap
- **Affected Plugin Version:** 2.11.0
- **MassiveCore Version:** 2.11.0

## Describe your environment

- **Spigot version:** This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
- **Config pastebin:** https://pastebin.com/ipyEwUXR
OS is linux centos 7
java version 1.8.0.131

## Steps to reproduce this bug

  1. First I set up server with all desired plugins and no issues.
  2. Next I added factionsdynmap as per instructions on massivecraft site.
  3. Finally this crashlog attached and git issue was created.

**Observed results**

plugin loads successfully, no further effect on game. repeats error every few seconds. does not terminate server. no visible factions on dynmap. 
error: http://i.imgur.com/mABUpjg.png
full log: https://pastebin.com/sJYz6k8i
plugin list: http://i.imgur.com/wCsZY61.png
all pastes above expire in 1 month

of note: running version in console notes that spigot is 45 versions out of date, and attempt to update yields a similar message, however 174 versions out of date. i have to assume i am on the most recent version for 1.11.2, and reverted back to the "45 versions out of date" the same error noted above occurs on the 174 version old spigot as the 45 version old spigot. unable to locate anything that would be less out of date for 1.11.2. 

**Expected results**

i assume factions should appear on the dynmap, and no error should occur in console

**Comment by ncf1** [comment]
this is caused by factions with no description

**Comment by ncf1** [comment]
https://github.com/MassiveCraft/Factions/blob/60b4472735801653b7270cb342f9296aa0e6d846/src/com/massivecraft/factions/entity/Faction.java#L113

**Comment by ulumulu1510** [comment]
For future reference, FactionsTax->EngineMain#getDescription (L745) should handle NullPointer.

**Comment by oloflarsson** [comment]
Do you get this issue on 2.13.0? I remember fixing a bug similar to this recently...

**Comment by ncf1** [comment]
my issue is resolved on 2.12.0, unsure about 2.13.0 but i would assume it would be fixed on that version as well.

**Comment by ulumulu1510** [comment]
Problem fixed in Version 2.12 and onwards.
