### ISSUE TITLE
MassiveCore Not Working

### ISSUE THREAD

**Issue by NerdyPacman** [MassiveCraft/Factions#1229]
MassiveCore and Factions

**Describe your environment**

* Affected Plugin version: 2.12.0
* MassiveCore version: 2.12.0
* Spigot version: 1.12
* Config pastebin: https://pastebin.com/uUYb3dkw

**Steps to reproduce this bug**

  1. Install Spigot 1.12.
  2. Add MassiveCore.jar to plugins.
  3. Read console.

**Observed results**

I created a new server to troubleshoot Factions. I start up Spigot, and it shows error messages with MassiveCore in them. I then deleted Factions so I know the error is from MassiveCore. Also, when Factions was installed, both plugins would show in /plugins as green. However, I could use no commands from them. No /f, nothing. So I came here for help.

server log on Pastebin: https://pastebin.com/zFhggmz6

No images needed, also the mstore folder is empty.

**Expected results**

I expect there to be /f, and for there to not be errors. This all happened when I updated.

**Comment by ulumulu1510** [comment]
The appended console log shows me that MassiveCore is not loading at all or is not present in the  plugins folder.

Please make sure to add both jars (MassiveCore and Factions) to your plugins folder properly before you start your server. 

Re-download the newest version (currently 2.13), unpack it properly if you get the zip with all plugins and put Factions and MassiveCore into your plugins folder. If you then still experience an issue, please attach screenshots of your plugins folder for me to troubleshoot and include (upload to a file sharing site) all the jars used (spigot, MassiveCore & Factions)
