### ISSUE TITLE
Massivecore does not work

### ISSUE THREAD

**Issue by Hyronymos** [MassiveCraft/Factions#1232]
Affected Plugin Name:  Factions
Affected Plugin Version: latest
MassiveCore Version:** latest

Spigot version: 1.8.8
Log: https://hastebin.com/eladiqojuz.md

Massivcore does not work on my server 2.11.0 and 2.12.0 (2.10.0 is still fine)

**Comment by Flavourized** [comment]
Psst, you may want to remove your IP from that paste..

**Comment by Hyronymos** [comment]
Psst, I have a dynamic IP-Adress

**Comment by MarkehMe** [comment]
1.8.8 appears to not have org/bukkit/scoreboard/Team$Option so 1.8.8 compatibility may be broken.

**Comment by Hyronymos** [comment]
pls add 1.8.8 compatibility back again

**Comment by ulumulu1510** [comment]
Compatibility has been restored, please update to 2.13
