### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by ncf1** [MassiveCraft/Factions#1234]
Environment: latest release of spigot 1.12, latest release of Massivecore, latest release of Factions, latest release of MassiveLag, latest release of FactionsDynmap

https://www.spigotmc.org/threads/factions.35746/page-46#post-2483484
https://www.spigotmc.org/threads/factions.35746/page-46#post-2487157

Assuming the following conditions: 

Console has /f admin enabled
The BUILD permission is UNEDITABLE
ENEMY is denied BUILD by default

How would I go about getting the command "/f ene [unique_faction_1]" to also have the console issue "/f perm set build ene yes [issuing_faction_of_relation]" while simultaneously maintaining that permission until the aforementioned issuing faction sets a NON-ENEMY relation to [unique_faction_1]

The reasoning behind this, is that I wish to add a deterrent/ disadvantage to an aggressive faction who would declare enemy, while not affecting the passive target. I want "declaring a 'specific targeted passive faction' as your enemy", to set /f perm build ene yes [aggressor], until the aggressor sets the relation of the same 'specific targeted passive faction' to a non enemy relation.

I desire this to combat players/factions who join and instantly enemy every existing faction for the sole purpose of griefing players in their own territory for no reason and with no drawbacks. I would be open to alternative means of punishing aggressive factions, that could be implemented without a need for physical administrative intervention. I can't just sit on the server all day and ban players who enemy without provocation, and the current implementation forces all players to live in ugly obsidian boxes covered with water. I am also concerned that players might be able to somehow circumvent this using the access system, but unsure if that would be the case. I want 'declaring a faction as your enemy' to be a dangerous and short term event, rather than the logical go-to relation for all aggressive players. How can I implement something like this?

**Comment by ulumulu1510** [comment]
The Perm system does currently only respect relations, not factions. You can't grant specific Factions a perm over the whole territory. Granted, with another plugin that manages all the data, adds all chunks to the access, blocks removing the access for said faction and so on, you could manage that.

But I fear that with the standard factions and its configuration you will not come far.
