### ISSUE TITLE
Massive Core not functioning on 1.12, causing factions not to load.

### ISSUE THREAD

**Issue by thebeast5268** [MassiveCraft/Factions#1235]
- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.12.0
- **MassiveCore Version:** 2.12.0

- **Spigot version:** This server is running CraftBukkit version git-Spigot-b78586d-f3356f1 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
- **Config pastebin:** Brand new config, no customization. 

https://pastebin.com/T6PzTqYr

**Comment by Apostolique2** [comment]
@thebeast5268 Just use Latest version ( 2.12.1 ) Should fix it

**Comment by ulumulu1510** [comment]
Please upgrade to 2.13, this will fix your issue.
