### ISSUE TITLE
Not working in game, but will work in console.

### ISSUE THREAD

**Issue by TheJxor** [MassiveCraft/Factions#1237]
## Affected Plugin

- **Affected Plugin Name:** Factions or MassiveCore
- **Affected Plugin Version:** 2.12.1
- **MassiveCore Version:** 2.12.1

## Describe your environment

- **Spigot version:** git-Spigot-23b6354-0481ae9 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
- **Config pastebin:** All the same, haven't messed with it.

## Steps to reproduce this bug

  1. First I installed latest version of spigot.
  2. Next I installed latest version of MassiveCore & Factions
  3. Finally once installed, the commands word in console, but not in game.

**Observed results**
 Commands work in console but not in game, there are 0 errors and I'm very confused.

**Expected results**

A fix, help fix, or something man, I just want to figure out why it's not working.

**Comment by ulumulu1510** [comment]
Can you please try to update to 2.13 and see if that helps? Also, try a server with only MassiveCore and Factions on it.

**Comment by TheJxor** [comment]
I updated to 2.13 both Massivecore & Factions, and it's still doing the same issue. 
I do not have another server to attempt to try this on. I appreciate the reply.

**Comment by ulumulu1510** [comment]
You could run one on your local machine, for testing purposes. Download a build of paperspigot for testing 
(https://ci.destroystokyo.com/job/PaperSpigot/) and run it like you would a usual bukkit server.

Then put only MassiveCore and Factions into your plugins folder. The reason behind this is, that it is likely that some other plugin blocks your users from using these commands. If there are no other plugins, the issue must be on our side, so I want you to make sure that it is actually a fault in our software.

Nevertheless, even though you don't think there are errors, can you post a full log file to pastebin or a similar service and link it here? IT would be interesting to see if anything goes wrong on startup.

**Comment by TheJxor** [comment]
I appreciate all the help. I really don't know how the problem was another plugin as all it did was change the unknown command message but once I deleted that, it works perfectly. Once again thanks for the help, odd issue but at least its fixed now.
