### ISSUE TITLE
Missing aliases?

### ISSUE THREAD

**Issue by L4BORG** [MassiveCraft/Factions#1241]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.13.0-SNAPSHOT
- **MassiveCore Version:** 2.13.0-SNAPSHOT

looks like with latest updates some aliases were broken...
/f p
/f s
/f w
...

**Comment by L4BORG** [comment]
Also same existing aliases are borken, for example /f who

**Comment by MarkehMe** [comment]
Does `/f f` work?

**Comment by oloflarsson** [comment]
Fixed in 2.13.1.
