### ISSUE TITLE
MASSIVE ISSUE - NEED HELP - FACTIONS ERROR

### ISSUE THREAD

**Issue by DevIPv2** [MassiveCraft/Factions#1243]
## Affected Plugin

- **Affected Plugin Name:** Factions ver v1.6.9.5-U0.1.20
- **Affected Plugin Version:**
- **MassiveCore Version:** 2.8.19

## Describe your environment

- **Spigot version:** ver 1.8.8
- **Config pastebin:** 

## Steps to reproduce this bug

  1. when into config and litteraly changed the and reloaded server it broken
  2. Next I did that.
  3. Finally this happened.

LOG 
 org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.20
07.07 20:16:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
07.07 20:16:34 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
07.07 20:16:34 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
07.07 20:16:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
07.07 20:16:34 [Server] INFO Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "com.massivecraft.factions.event.FPlayerJoinEvent.<init>(Lcom/massivecraft/factions/FPlayer;Lcom/massivecraft/factions/Faction;Lcom/massivecraft/factions/event/FPlayerJoinEvent$PlayerJoinReason;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/massivecraft/factions/cmd/CmdCreate, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/massivecraft/factions/event/FPlayerJoinEvent, have different Class objects for the type com/massivecraft/factions/event/FPlayerJoinEvent$PlayerJoinReason used in the signature
07.07 20:16:34 [Server] INFO at com.massivecraft.factions.cmd.CmdCreate.perform(CmdCreate.java:82) ~[?:?]
07.07 20:16:34 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
07.07 20:16:34 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
07.07 20:16:34 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
07.07 20:16:34 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
07.07 20:16:34 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
07.07 20:16:34 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:299) ~[?:?]
07.07 20:16:34 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:262) ~[?:?]
07.07 20:16:34 [Server] INFO at com.massivecraft.factions.P.handleCommand(P.java:189) ~[?:?]
07.07 20:16:34 [Server] INFO at com.massivecraft.factions.P.onCommand(P.java:200) ~[?:?]

/f looked good

**Comment by imaBASKET** [comment]
What is the purpose for using a version (or fork) of the plugin that is 4 years old?

**Comment by ulumulu1510** [comment]
We do not do support for outdated version, please update to a 2.13 off both MassiveCore and Factions,  if the issue persist's,  you can come back here for help.
