### ISSUE TITLE
Error on 1.12

### ISSUE THREAD

**Issue by bertek41** [MassiveCraft/Factions#1244]
- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** Latest
- **MassiveCore Version:** Latest

- **Spigot version:** 1.12

https://i.gyazo.com/c745159d750a9d04bb3a18e3d1cbd4f9.png

https://i.gyazo.com/e4dcadc9230cbe008ce0ecc3ec67c130.png

**Comment by MarkehMe** [comment]
We can't confirm or replicate this. You've also not given us any information "_latest_" is a nice buzzword but means nothing. 

Please return the results of:
```
/version
/version factions
/version massivecore
```

Otherwise we can't help you :)

**Comment by bertek41** [comment]
Factions and Massivecore's version 2.13.0
Spigot 1.12-R0.1

**Comment by oloflarsson** [comment]
Please update to 2.13.1. This should be fixed in that version. Also make sure you have no duplicate plugin jars.
