### ISSUE TITLE
It doesn't work in 1.12

### ISSUE THREAD

**Issue by Cagrimanoka** [MassiveCraft/Factions#1247]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.13.0
- **MassiveCore Version:** 2.13.0

## Describe your environment

- **Spigot version:** 1.12R0.1
- **Config pastebin: It did not get generated** 

## Steps to reproduce this bug

  1. I just tried to launch it, I got errors (in 1.12)

**Observed results**
Factions error, in pastebin: https://pastebin.com/EEZV44Uf
Factions error, in screenshot: https://i.gyazo.com/c745159d750a9d04bb3a18e3d1cbd4f9.png (It has been tried on previous snapshot of spigot)
MassiveCore error, in pastebin: https://pastebin.com/Yipthsyk
MassiveCore error, in screenshot: https://i.gyazo.com/e4dcadc9230cbe008ce0ecc3ec67c130.png (It has been tried on previous snapshot of spigot)

**Expected results**
Well, I was about to launch my server but factions doesnt work, so a fix can be pretty good

**Comment by oloflarsson** [comment]
Please update to 2.13.1 and make sure you have no duplicate jars for the plugins in the plugins folder. That should fix this issue you are having.
