### ISSUE TITLE
"Fireball able to ignite builds in SAFEZONE", Incorrect Answer!

### ISSUE THREAD

**Issue by publik** [MassiveCraft/Factions#125]
Following up on the topic i previously posted but was closed:
https://github.com/MassiveCraft/Factions/issues/124#issuecomment-5709130
I know i can do that but that still will not stop the fire,
Please understand that fireballs can be fired from a dispenser and used to burn things,
they have UNLIMITED range, meaning i could fire a fireball from a wilderness territory but it could burn my whole spawn building.
Please give me an answer that makes more sense, 
I do not want to block fireballs in dispensers since it could be useful during pvp

**Comment by MarkehMe** [comment]
I'm checking over old issues, I've tested this and it's no longer an issue (fire does not spread) although fireballs can be shot into territories they do nothing. I'll look into fixing that later though.
