### ISSUE TITLE
Explosions created by BlockExplodeEvent are not prevented

### ISSUE THREAD

**Issue by DerPavlov** [MassiveCraft/Factions#1254]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.13.1

## Describe your Environment

- **Server Version:** Craftbukkit 1.12-R0.1-SNAPSHOT

## Steps to Reproduce this Bug

1. Set up a safezone
2. Use any plugin that utilizes the bukkit method createExplosion (e.g. Cannons) to destroy blocks in the safezone
3. CreateExplosion fires a BlockExplodeEvent which is not prevented by Factions, which means the safezone was not protected

## Observed Results

Explosions which trigger the BlockExplodeEvent are currently not prevented by Factions. The most common explosion which triggers this event is world.createExplosion. These explosions bypass the Explosions flags and occur even when disabled in the configuration. The only fix I found was relaying the BlockExplodeEvent to the previous EntityExplodeEvent with entity null.

## Expected Results

BlockExplodeEvent should be implemented the same way as EntityExplodeEvent with a null as entity.

**Comment by oloflarsson** [comment]
Fixed in https://github.com/MassiveCraft/Factions/commit/72b7a6a4acea3515ad8c0b0b3b4c9c238280716e
