### ISSUE TITLE
Random error on console

### ISSUE THREAD

**Issue by MithrandirCraft** [MassiveCraft/Factions#1255]
- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.13.1
- **Server Version:** Spigot for mc 1.12.1

Getting this error regularly, currently without context:
https://hastebin.com/kuqexilula.md

**Comment by MarkehMe** [comment]
Factions does not use MySQL. 

Judging by the table name this is caused by Cannons:
https://github.com/DerPavlov/Cannons/blob/master/src/main/java/at/pavlov/cannons/Cannons.java#L69
