### ISSUE TITLE
Respawn suggestion

### ISSUE THREAD

**Issue by RainOfPain125** [MassiveCraft/Factions#1276]
Sorry if this is the wrong place to suggest things, but I didn't see anywhere else

You should add something to the config to disable a player from automagically spawning at their f home (ie disabling this setting would make you spawn at the world spawn, etc)

**Comment by TheComputerGeek2** [comment]
@RainOfPain125 there is already  a configuration option that does this: [homesTeleportToOnDeathActive](https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/entity/MConf.java#L278)
