### ISSUE TITLE
Request To Take Over Plugin Development

### ISSUE THREAD

**Issue by davidjpfeiffer** [MassiveCraft/Factions#1340]
Hello,

I have used the Factions plugin on various servers of mine for years. It is my favorite Bukkit plugin of all time, and I am so grateful for all the work the MassiveCraft team has put into developing it for the community.

Many problems have emerged since [Cayorion took a less active role in 2013](https://forums.massivecraft.com/threads/the-imminent-future-of-massivecraft.67842/page-4). MassiveCraft has struggled to keep the plugin up-to-date, the extensions of the plugin are poorly documented, many of the extensions are not available for download, many desirable features have been removed ([FactionChat](https://dev.bukkit.org/projects/factionchat)), and the future of MassiveCraft itself has been severely threatened.

I have years of software development experience, am a huge fan of both Minecraft and the Factions plugin, and am considering writing an improved version of the plugin myself. I would like to redesign the system to use modern best practices, clean up the user interface, simplify the user experience, improve the plugin performance, and offer a version of the new plugin which is kept up-to-date. I would also like to incorporate the chat and tax extensions as part of the plugin.

With the permission of the MassiveCraft team, I would like to fork the current [Factions repository](https://github.com/MassiveCraft/Factions) and begin working on the new plugin. If my plugin is successful, I would hope that the Factions project would be deprecated and would recommend using my plugin as an alternative for servers running newer versions of Minecraft. I would be willing to work with the MassiveCraft team to try and keep the features they need for the new version of the server.

I would plan to release the plugin to the public for free for the first few months / years after initial release. After the plugin became popular, I would consider charging $10 for each up-to-date download of the latest major release. Minor releases would be free after the purchase of a major release. This would ensure the stability and future development of the plugin, regardless of how long I continued to maintain it, as the development team maintaining the plugin would be compensated with these funds. I would not charge MassiveCraft for any updates to the plugin, ever.

I do not know who is authorized to sign off on this (if anyone at the moment) but I wanted to reach out and share my idea. I know this probably isn't the right place to make this request, but I did not know where else to make it.

Thank you for your time,

David J Pfeiffer

**Comment by markhughes** [comment]
@magnusulf has done this already

**Comment by magnusulf** [comment]
[Here](https://github.com/magnusulf/Factions) is the link, if anyone cares. Although I have only resumed Factions and MassiveCore development. I am not ruling it out, but I probably wont resume development of other public MassiveX plugins. If anyone wants to use my version of MassiveCore to resume development of other MassiveX, I will gladly help them get started.

**Comment by davidjpfeiffer** [comment]
Thank you for your responses. I was primarily interested in a re-write of the plugin which incorporated the features previously mentioned. After discussing this privately with contributors of the Factions plugin, I have decided to postpone this endeavor for the time being.
