### ISSUE TITLE
Setting to prevent people from igniting stuff on territory with fireballs

### ISSUE THREAD

**Issue by Clavus** [MassiveCraft/Factions#142]
I've tried adding FIREBALL to territoryDenyUseageMaterials(WhenOffline), but this only stops people from directly right-clicking with a fireball in hand in enemy territory. I also tried setting
  "territoryBlockFireballs": true,
  "territoryBlockFireballsWhenOffline": true.
Yet people can still use dispensers to shoot fireballs into other people's territory and ignite any flammable blocks. Is there an option to properly disable this?

**Comment by MarkehMe** [comment]
Duplicated of #125
