### ISSUE TITLE
Denying enemies claiming same chunk

### ISSUE THREAD

**Issue by mattwilson777** [MassiveCraft/Factions#157]
Brett or anyone else that might know, is there a way either in the config or in the source to make it where if an enemy faction member is in a Wildnerness chunk, another enemy faction member can't claim that chunk either through /f claim, /f autoclaim, or /f claim radius?  

For example, Warriors and Rebels are enemy factions.  KewlDood is in Warriors and LeetKiller is in Rebels.  KewlDood is in a wilderness chunk and suddenly LeetKiller drops in on him.  How do I make it so they can't claim that chunk for their faction?

**Comment by MarkehMe** [comment]
To do this you would just increase `claimMinimumChunksDistanceToOthers` which applies to players not in your Faction.
