### ISSUE TITLE
[REQUEST] Setting to disable Safezone protection after player goes into combat

### ISSUE THREAD

**Issue by Clavus** [MassiveCraft/Factions#214]
I usually build our faction spawn as a safezone with warzone around it, so players can fan out a bit but they won't be protected everywhere. Problem is that there's a ton of people that just camp at the border of the safezone to do damage to folk that are just outside. It'd be nice if the safezone protection could be disabled for those people once they damage another player. Just temporarily, until next rejoin or something.

**Comment by ulumulu1510** [comment]
This request is firstly really old and no one has asked for a similar feature in the 2.5 years that have passed since. Please open a new issue if you feel this is still an issue.
