### ISSUE TITLE
PluginChannel client information queries

### ISSUE THREAD

**Issue by riking** [MassiveCraft/Factions#236]
Task: Create a PluginChannel API such that a client mod can query information like so:
```
sendPacket250("REGISTER", "Factions")
sendPacket250("Factions", something_or_other)
listenPacket250("Factions");
```
Here's a list of possible query goals:
 * Relation of player/faction to me
 * Relation of each player on the playerlist to me
 * Formatted string for a player/faction
 * The faction of a player
 * Power/Land/Maxpower of a faction
 * Power/Maxpower of a player
 * The equivalent of /f map, except sent over this so that a client mod can display it in a custom manner
 * Getting the cape configs (/f cape or whatever it is), to be used with the playerlist relation query

Possible difficulties: 
 * Asking for so much information that it lags the server pipe

The Bukkit classes to do this are in `org.bukkit.plugin.messaging`.

**Comment by ulumulu1510** [comment]
This has essentially been created. All the described features are part of the current version of Factions and can be accessed. It is not it's own API, but it's part of it. If you are still interested in developing such an API, feel free to do so :)
