### ISSUE TITLE
Factions relations bug

### ISSUE THREAD

**Issue by NemesisMate** [MassiveCraft/Factions#248]
If you set an other faction as ally, they accept and then you set them as enemies and again allies you are again his ally without them accepting it.

So you can do lot of tricks with that.

I think the best way is to, once you put another one as enemy, on him you stay like enemy till they change it.
If you put them as neutral/enemy and after ally again, for them that must stay like neutral/enemy instead of becoming ally again.

Using: Factions 1.8.2, Bukkit 1.5.2-R.0.1

**Comment by MarkehMe** [comment]
@NemesisMate is this still an issue?

**Comment by NemesisMate** [comment]
I can't say, It have been a long time since the last time I used the game.
Sorry.

**Comment by magnusulf** [comment]
This is not a bug, but rather people not managing their relations properly.
