### ISSUE TITLE
For factionless newbies, "/f claim" is misleading

### ISSUE THREAD

**Issue by thejh** [MassiveCraft/Factions#274]
When a factionless player (usually a newbie) does "/f claim" on unclaimed land, as far as I have seen, he gets a message about his faction already owning the land (because technically, he belongs to the wilderness). This is misleading – how about adding a special-case message that tells the player to create or join a faction first?

**Comment by MarkehMe** [comment]
If this was set to a faction-only command then this could cause issues for claiming without a faction (i.e. server admins/ops). 

This could be implemented with a few changes to the internals, but I don't think it's a high priority currently. I'll discuss with the tech team to see if something could be done.
