### ISSUE TITLE
[Feature] Disable commands within a radius of enemy territory 

### ISSUE THREAD

**Issue by externo6** [MassiveCraft/Factions#281]
Sorry but i was not sure where to post this,

But is it possible to add disabled commands within a radius of enemy territory, like you cant teleport away if enemy are near by?

Thanks!

**Comment by ulumulu1510** [comment]
Although it is not exacly this feature, we feel that our current options:

  "homesTeleportAllowedFromEnemyTerritory",
  "homesTeleportAllowedEnemyDistance" and
  "denyCommandsTerritoryRelation"

will be suitable for your command disabling needs. If those are not suitable, please respond and I'll re-open this issue.
