### ISSUE TITLE
Worldguard intergration

### ISSUE THREAD

**Issue by externo6** [MassiveCraft/Factions#294]
Hello, in the new version of Factions (v2.0.3) I am unable to find an option to block people from claiming in worldguard regions like in the 1.6 versions of factions. ("worldGuardChecking": true,)

Am missing something? As in the plugin.yml worldguard is a softdepend.

Also, I have blocked /f autoclaim in a region, world guard notifies the player that they cant do that command but it still activates, allowing them to claim.

Thanks!

**Comment by externo6** [comment]
Hi issue is still open, has worldguard integration been put in? Need this as I now need to update.
Thanks

**Comment by MarkehMe** [comment]
@externo6 It's on the roadmap

**Comment by MarkehMe** [comment]
Implemented, will be in the next release
