### ISSUE TITLE
Essentials #Dev2.12.54 Chat Tags Not Working

### ISSUE THREAD

**Issue by Penteractr** [MassiveCraft/Factions#326]
Hello. We want setup a symbol for players dont have faction. We used {factions_roleprefixforce} but it didnt work. We are using Essentials #Dev2.12.54 and  Factions 2.0.4 MCore 6.5.X. Chat showed [{faction_roleprefixforce}] when we using {faction_roleprefixforce} in configuration.

**Comment by Mike1255** [comment]
For some reason this still happens, I am using it properly with {factions_roleprefixforce} yet it still breaks... basicly it just shows up as "{factions_roleprefixforce}"

**Comment by Mike1255** [comment]
For additional info, I'm using Spigot, Factions 2.7.4 and MassiveCore 2.7.4

**Comment by oloflarsson** [comment]
I guess we will continue this bug here: https://github.com/MassiveCraft/Factions/issues/814
