### ISSUE TITLE
Re-add econClaimAdditionalMultiplier

### ISSUE THREAD

**Issue by JohOply** [MassiveCraft/Factions#354]
Hi

I've write an issue a month ago ( https://github.com/MassiveCraft/Factions/issues/287 )

You said that it was an option too complex. But complex for who? For players or for you ?

Because it is an option very interessant that i, and probably a lots of others server's owners want use...

So, can you re-add this please ? Thanks !

**Comment by Xericore** [comment]
Any chance of getting this nice old feature back?

**Comment by ulumulu1510** [comment]
As I understand this feature, costs to claim a chunk a chunk will increase the more chunks are already claimed.

I would suggest buying yourself FactionsTax, as it offers this and much more features for economy driven server and faction gameplay.
