### ISSUE TITLE
Delayed relation change time

### ISSUE THREAD

**Issue by ChrisLane** [MassiveCraft/Factions#37]
Could you possibly add a feature where when you are allied to a faction you have a delayed enemy time. So that people can't just enemy an ally once they reach their base. 
You could have an option in the config like this:
Ally to Enemy Delay: 10m (10 minutes)

Ok thanks :D

**Comment by magnusulf** [comment]
So when an ally begins to grief my base (assuming they have the perms), I would have to wait 10 minutes before we are enemies. I believe this suggestion is hugely flawed.

**Comment by magnusulf** [comment]
Closed due to inactivity.
