### ISSUE TITLE
Wilderness Bugs

### ISSUE THREAD

**Issue by xsamboix** [MassiveCraft/Factions#373]
Hello, im having two very odd issues with factions ive been having a similar issue since Factions 2.0 and it doesn't seem to of been fixed yet.

Issue 1: A faction enemies wilderness this part is fine, then the faction cannot fall back into truce with wilderness as when they try to make peace by using /f truce, /f neutral, /f ally. Then when you try and truce a second time it says you already have that relation, now here is the odd part; when typing /f f i can see 2 wilderness factions (one in truce, the other in enemy)?

Issue 2: A player tries to join another faction from wilderness, the player in Q is called "natorai_shido" instead it adds "nateisawesome43", this is not just an error with 1 person i am getting multiple complaints about this error. The really odd part about this was i then created a faction to see if he could join and he could, i have checked the logs and the player was invited and typed /f join correctly. However i then asked him to use /f join <faction name> and the bug resolved.

The "error" when /f join was typed (nateisawesome43 had not been online for 10 days whilst this was happening)
[Factions: 2.0.5] postAttach added nateisawesome43 aka nateisawesome43 to d78704a2-2dba-4351-91bb-8e30cfec9254 aka Wilderness.

**Comment by MarkehMe** [comment]
This issue was from 2 years ago and theres been a lot of changes. Open a new issue ticket if it still exists please! :)
