### ISSUE TITLE
Factions Economy Disabled but Still Detected as a Player

### ISSUE THREAD

**Issue by omniptntruler** [MassiveCraft/Factions#385]
I have Essentials loaded an am using the builtin economy system. I also have Factions 2.0.5 loaded and within factions I have all economy features disabled per the default configuration. Before any factions were created, when running /baltop, it only showed players. After creating and disbanding a faction though, when running /baltop it shows the weird factionID listed on that screen and is also saved into the essentials/userdata folder as well. This seems to happen when the faction is disbanded with essentials immediately creating the player data yml file.

7:07:11 PM [INFO] [Factions 2.0.5] The faction test (981a8421-a954-4ae7-b1a9-4af40aec5c7d) was disbanded by Sparcticus.
7:07:11 PM [INFO] Creating empty config: D:\minecraft\plugins\Essentials\userdata\faction_981a8421_a954_4ae7_b1a9_4af40aec5c7d.yml

I'm posting this issue here as I already posted on the Essentials ticking system and was told to report it to Factions as leak instead. Link: https://essentials3.atlassian.net/browse/ESS-4706

**Comment by ulumulu1510** [comment]
I have taken the time to snoop through the code and see (to my supprise) it is an actual bug on our end as we never delete the faction account on disband.

Future reference:
https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/engine/EngineEcon.java#L83

**Comment by ulumulu1510** [comment]
This fix will be part of the next plugin version.

**Comment by NoopyyGaming** [comment]
I get the same too, when in disband a faction i get this message too.
