### ISSUE TITLE
Factions Tp Delay

### ISSUE THREAD

**Issue by ghost** [MassiveCraft/Factions#399]
Hi, I've had the old factions from before it required MCore for so long, and only updated tonight...I reclaimed all the safezone and warzone and changed all the settings as i liked with no errors, but i CANNOT find anyway to disable the 10 second tp wait when typing /f home
I've googled and everything but can't find how to fix this...I've also searched all the config files and such...
Please help!

**Comment by girlwizard** [comment]
Hey can you tell us where it is cuz i cant find it too?
