### ISSUE TITLE
Peaceful flag doesn't work.

### ISSUE THREAD

**Issue by Gnarusly** [MassiveCraft/Factions#429]
There is no error in the log or anything.

When I do /f flag factionname peaceful yes, no one can hurt them. However, they can still hurt people who are not in a faction (aka wilderness).

This is very damaging, how do I fix this?

Factions version 2.2.1
 This server is running CraftBukkit version git-Spigot-1112 (MC: 1.6.4) (Implementing API version 1.6.4-R0.1-SNAPSHOT)

**Comment by ulumulu1510** [comment]
The peaceful flag was not ment to be given to player run factions, but I see your issue none the less.

**Comment by ulumulu1510** [comment]
I have looked into this issue:
https://github.com/ulumulu1510/Factions/commit/d72756146b25fe37fd8f41d4060c14d27f89ef2b

We are working on resolving the issue.

**Comment by ulumulu1510** [comment]
Resolved
