### ISSUE TITLE
Players cant blow up others claimed land.

### ISSUE THREAD

**Issue by dondonleroy** [MassiveCraft/Factions#439]
My players are unable to blow up or do any damage to any blocks in others claim. Ive looked in the config but i cant find anything. Anyone know how I could change this? 

Thanks.

**Comment by oloflarsson** [comment]
Update to the latest version of Factions and MassiveCore.
Make sure you follow these update instructions:
http://www.massivecraft.com/factions-download#update

That should probably resolve your issues.
