### ISSUE TITLE
Cannot Ally As Peaceful Faction

### ISSUE THREAD

**Issue by dcrockwell** [MassiveCraft/Factions#462]
If you set a Faction to be Peaceful, then you send an ally request to another faction, they can send back request as well.. but no alliance is actually formed.

If you disable peaceful status, you'll immediately be allied.

We need the ability to be both Peaceful (nobody can claim your land if you're under-powered), and to be allied with others (so we can give them perms to build on our land, etc.)

**Comment by magnusulf** [comment]
The point of a peaceful fact is that they /cannot/ set relations to other factions. Closing.
