### ISSUE TITLE
Regening non-claimed land. 

### ISSUE THREAD

**Issue by Murdox1221** [MassiveCraft/Factions#494]
Hello,

This was a request I asked for earlier. However it was lost, (This being over 2 months ago) The idea is simple, a built in way for server owners to regenerate land that is not claimed. 

The way I would foresee this working is the command is executed, the feature would start looking at chunks, so it starts at the chunk 0,0 is in, then it sees if it is claimed, or safe/war zone, and preferably WG protected. If this is false then it regens that chunk, and moves to the next. 

This allows a minimal additional server load, as well as, less (hopefully) coding on your end. As far as the Regening it would need (in concept) World edit as a requirement. I know that Towney has something similar to this, but Im not 100% sure how it works. 

I know there research that this is in demand, especially to the larger non-whitelist Factions servers. I know for one, it would be a life saver. 

Thank you as always
Murdox

**Comment by ulumulu1510** [comment]
See this issue for the answer:
https://github.com/MassiveCraft/Factions/issues/993
