### ISSUE TITLE
Players with bonus power do NOT increase factions power.

### ISSUE THREAD

**Issue by TagCraftMC** [MassiveCraft/Factions#510]
Not sure if this is a mistake, if it isn't it kind of seems silly.

If a player is given bonus power (/f powerboost p Chalkie 100) when in a faction that bonus ONLY applys to the MaxPower not the Power and MaxPower which essentials makes the ability to give players bonus power useless as they can never over claim the amount in their faction from other players.

Example I am in a faction with 2 other people and we all have 10 power we're at 0/30/30, so the max we can claim is 30. If i give my self bonus 20 power we would be at 0/30/50 and still the max we could claim is 30.

This is not the case of you give the power to the faction itself (/f powerboost f ChalkieFaction 0) This applys to the Power and MaxPower.

Example I am in a faction with 2 other people and we all have 10 power we're at 0/30/30, so the max we can claim is 30. If i give the faction bonus 20 power we would be at 0/50/50 and the max we could claim is 50. 

I hope this made sense and could be fixed or explain why it is like this, if giving players bonus power is pointless why have it anyway, this was not an issue in factions 1.0 AFAIK (remember) bonus power on people did allow extra claiming in factions.

**Comment by ulumulu1510** [comment]
I have looked at this issue a very very long time ago and I believe we fixed it aswell during that time. This issue should not persist anymore.
