### ISSUE TITLE
Command blacklist - enemy distance

### ISSUE THREAD

**Issue by HotNachos** [MassiveCraft/Factions#520]
I requested this because I looked all through mstore and couldnt find it. If you know how please tell me.

There is a setting "homesTeleportAllowedEnemyDistance": 32.0,
In this players may not /f home within 32 blocks of an enemy but can still use /home or /spawn to teleport out of combat within 32 blocks of an enemy.

Request to add there be a 

"denyCommandsEnemyDistnace": { }, <--- or something like that were we can add deny commands

just like the 

"denyCommandsTerritoryRelation": {
    "ENEMY": [
      "home",
      "fhome",
      "spawn",

**Comment by MarkehMe** [comment]
Implemented in e84e8abba03b453d12e9865bf204a403938caa6d
