### ISSUE TITLE
[Request] - nopowergain

### ISSUE THREAD

**Issue by ashower** [MassiveCraft/Factions#526]
Hello, 

i'd like to see option in config / faction flag for "NoPowerGain" working similar to "NoPowerLoss" to be available. Any, but best all of below would be most than welcome:
config - worldsNoPowerGain: []
faction flag - powerGain: true/false

the idea is to prevent people abusing safezones and worlds with no pvp / no powerloss from gaining power in safezones (spawn) or arena worlds.

this would be a nice option to have available on few hardcore pvp faction servers

**Comment by MarkehMe** [comment]
@ashower is this still required? I could work on this.

**Comment by ashower** [comment]
We've got a temporary custom solution in place, but yes, it would still be most welcome addition. Thanks!

**Comment by ChrisLane** [comment]
@MarkehMe I'd still appreciate this!
I think it was in FactionsPlus at one point but obviously that plugin is no more :)

**Comment by MarkehMe** [comment]
This will be in the next version of Factions. 

Enjoy! 🎉
