### ISSUE TITLE
Commands not accessible from outside factions

### ISSUE THREAD

**Issue by rendezvousIY** [MassiveCraft/Factions#543]
Due to the implementation of faction permissions I noticed that it is possible to grant allies or other outside factions access to commands such as invite, kick, territory etc, however many of the commands do not work as expected or at all.

Examples:

Access: Works properly for other factions, outside factions with access permission are able to grant/remove access in specific chunks.

Container/button/lever: Works as expected

Territory (allies): Allows allies to claim/unclaim your faction's land at the expense of your faction. When overclaiming friendly land your faction is granted the pillage reward, granting nearly unlimited free money by repeatedly reclaiming land between the factions.
/f claim 5 
/f claim 5 otherfac
[repeat]

Invite: This permission for allies/truced factions should allow a faction to invite a player into a specific faction but defaults to your own faction, eg:
/f invite player secondfac -> should invite player into secondfac

Kick: same as invite

Disband: Haven't tried, may or may not default to own faction

**Comment by ulumulu1510** [comment]
We have reworked commands and command aliases in 2015 which lets me believe that these issues don't exist anymore. If some of them still cause you troubles, please open up a new Issue with the problems still existing.
