### ISSUE TITLE
Request: Permissions/groups recommendations

### ISSUE THREAD

**Issue by rendezvousIY** [MassiveCraft/Factions#544]
Being a factions player myself I have found that access to permissions gives a very high amount of control to factions, to the point I've been able to access/control the majority of the affairs of multiple factions with claim/unclaim/etc, but there are some limitations that I feel would be a useful addition and help prevent abuse with the wrong players.

Examples use the faction name Athens for own faction and Rome for another faction.

Suggestion 1: Sub-groups
If I allow /f perm Athens build all yes anybody in an an allied faction can build on my land, including their new recruits etc. I propose adding sub-groups to the current groups so that:
/f perm Athens build all.mem yes //allow allied faction's members to build
/f perm Athens access all.off yes //allow allied faction's officers to control access
...would work as expected.

Suggestion 2: Explicit Identifiers
In a similar way that other commands work for info, power, access, and others, allow a specific group to be granted permissions such as:

/f perm Athens build f.rome yes //allow the faction rome to build
/f perm Athens build all.f.rome yes //allow the *allied* faction rome to build
/f perm Athens perm p.aximilation yes //allows player aximilation to control permissions
/f perm Athens territory g.facmgmt yes //allows the group facmgmt to control territory (more on that below)

Suggestion 3: Permission Groups
Allow definition of groups which could be addressed in a similar manner to a party or faction. Groups may be used in multiple areas of factions such as for access, permissions, and potentially other areas.

Usage:
/f group create Architects //creates group Architects
/f group add Architects aximilation //adds player aximilation to the group
/f group kick Architects aximilation //removes player aximilation from the group
/f access g Architects //grants access to a chunk for the Architects group
/f perm Athens build g.Architects yes //allows the group Architects access to build on Athens land
/f perm Athens withdraw g.Bankers yes //allows the group Bankers access to Athens' money
/f group disband Architects //disbands the Architects group

Players leaving their current faction while in a group should be automatically removed from the group they are in. The group may have a flag to allow for group membership to persist when switching faction. (This would be to provide ability to prevent self faction betrayal while using access granted to a group a player is still in) This ability would be a flag called persist (up for change) and be used as follows:

/f group persist Architects no //Players leaving their current faction are removed from this group (default behaviour)
/f group persist Architects yes //allows players to roam cross-faction while remaining in this group

The abilities in these three suggestions can be used to add a much higher level of control to factions for both players and administrators, feel free to revise/adjust them as needed if they can be implemented into the factions project.

**Comment by ulumulu1510** [comment]
duplicate, but a very nice description: https://github.com/MassiveCraft/Factions/issues/443
