### ISSUE TITLE
Neutrals can't hurt me in my territory, even though I changed that setting

### ISSUE THREAD

**Issue by PlagueOfCats** [MassiveCraft/Factions#619]
The settings in question,

"disablePVPBetweenNeutralFactions": false,
"disablePVPForFactionlessPlayers": false,
"enablePVPAgainstFactionlessInAttackersLand": true,

My version of factions: 1.6.9.4. Version of minecraft/server: 1.6.4.

Yes, I reloaded / stopped and restarted the server to make sure that these 3 settings remained in place, and they did. Yet neutrals still CAN'T hurt me in my own territory. Is this a bug or is there a 4th setting I don't know about that I have to change, to make this work?

**Comment by bladextd** [comment]
Try reloading Factions by itself, not the whole server. That is all I can think of.

**Comment by oloflarsson** [comment]
Are you sure you are not using god mode or some sort of invincibility from an external plugin?

**Comment by bladextd** [comment]
... Such as Essentials

**Comment by magnusulf** [comment]
Inactive. Closing.
