### ISSUE TITLE
[Request] Time-in-vicinity capturing

### ISSUE THREAD

**Issue by Buddhano** [MassiveCraft/Factions#657]
Hi, I would like to suggest a new way to capture territories. I'm making a server that mainly focuses on the city, and was hoping to make certain areas in the city that factions can fight to capture to earn rewards. I was hoping to make it so these areas could be captured by standing in the area, the more people in the area the quicker it captures. If enemies or other factions are in the area, you capture slower and cannot fully capture the area if they're still there. I was also thinking Allies could boost the capture rate but at a slower rate than people of the faction would be if they were in the area.

It would also be nice if there was a way to use commands to select an area to set an area as a territory (like WorldEdit's //pos1 and //pos2).

Thank you for your time and consideration, have a nice day! Feel free to ask me any questions about this suggestion.

**Comment by drtshock** [comment]
This sounds more like a game of capture the territory or domination, not factions.

**Comment by Buddhano** [comment]
Dude this shit is like 6 months old

**Comment by drtshock** [comment]
Yes but it's still an open feature request.

**Comment by Buddhano** [comment]
I
