### ISSUE TITLE
Leader Promotion Cost

### ISSUE THREAD

**Issue by orkun1675** [MassiveCraft/Factions#660]
Please add an option so we can take money from players to execute this command

**Comment by bladextd** [comment]
Why? All you are doing is making someone leader...
However changing  your faction name is a different story.

**Comment by ulumulu1510** [comment]
If this is still your wish to be implemented, please state so. Otherwise we will close this issue in a few weeks.

**Comment by orkun1675** [comment]
We can close this issue.

**Comment by ulumulu1510** [comment]
Thank you for responding :).
