### ISSUE TITLE
suggestion, for econ setting's

### ISSUE THREAD

**Issue by Dv2236** [MassiveCraft/Factions#662]
first 2 ideas should be options each faction leader can pick the rest should be global default should prop be 0 & true if econ is turned on.

econMemberRent: x "x=money to stay in the faction or they get money if set to -x"
econMemberRentBank: true/false "true=money comes out bank, false=money comes from leader."
econMemberRentDays: x "how many days before a member pays or gets paid."
econMemberRentLate: x "how many days can u go before u are forced out of the faction."
econMemberRentFail: x "if a member fails to pay they perm lose x power & kicked from the faction or if faction fails to pay member it perm lose x power, or maybe another options to say if they perm lose power or not."

seeing how some ppl could scam ppl if this was all auto, i think ppl would have to type a command to pay, thats why i have the late option as a example & if u fail to pay u hurt ur rep/power

i think if u leave faction before u are force kicked for being late than u should be able to get out of it just encase someone jacked up rent to a stupid amount!

also maybe options to buy more faction power with all that incoming money to the bank or other bonues ;)

i was thinking if the members pay a rent thing dose not work out maybe rent land/rooms to members that goes right into faction leaders pocket or bank

anyways hop u guys like my suggestions

**Comment by drtshock** [comment]
There is the [FactionTax](http://www.spigotmc.org/resources/factionstax.1913/) addon that he charges $10 for despite [saying that he codes free software](https://github.com/MassiveCraft/Factions/issues/607#issuecomment-43135716) even though he also [gets money from BukkitDev](https://github.com/MassiveCraft/Factions/issues/607#issuecomment-43086306).

**Comment by magnusulf** [comment]
There is FactionsTax[https://www.spigotmc.org/resources/factionstax.1913/] which can do most of what you are asking.
