### ISSUE TITLE
Double Chat

### ISSUE THREAD

**Issue by dhannyjsb** [MassiveCraft/Factions#684]
Double chat with Herochat v5.6.7 and  Factions 2.5.0.
I'm using latest spigot 1.7.10. (for client 1.8)
and I've been following
{
    ...
    "chatSetFormat": false,
    ...
    "chatParseTags": true,
    ...  
}

![screenshot_50](https://cloud.githubusercontent.com/assets/6823218/4228315/0b432780-3959-11e4-8a60-36d80e672f0e.jpg)

thanks

**Comment by madtomic** [comment]
This on 2.7.3 I don't see the line.
