### ISSUE TITLE
Fire can be ignited in Safe Zone

### ISSUE THREAD

**Issue by SupaYoshi** [MassiveCraft/Factions#69]
Fire can be used in safezone, :) Patch please? :D
I mean not lighters but real fire, if players place it it will ignite in safezone.

**Comment by ulumulu1510** [comment]
"materialsEditTools": [
    "FIREBALL",
    "FLINT_AND_STEEL",
    "BUCKET",
    "WATER_BUCKET",
    "LAVA_BUCKET",
    "ARMOR_STAND"
  ],
Adding the Material to this list in your config is the solution to this problem. Since this is a very specific issue to your servers we won't add it to the config in our code.
