### ISSUE TITLE
Cannot claim enemy land if not connected

### ISSUE THREAD

**Issue by henryaustin404** [MassiveCraft/Factions#721]
Hi,

Thanks for your work on fix d23ac9d. Claiming now works. Unfortunately, in order for it to function, the requirement for land to be connected must be disabled.

Thanks,

Henry

**Comment by ulumulu1510** [comment]
@henryaustin404 Is this still an issue? It could be, but could you please answer so we have some todays evidence?

**Comment by ulumulu1510** [comment]
Since this hasn't been replied to in more than a month, I see the issue as resolved. If this is still an Issue, we can still re-open it later when more evidence has been brought up.
