### ISSUE TITLE
[Request] Editable tilde mark

### ISSUE THREAD

**Issue by ZombieAssassin** [MassiveCraft/Factions#740]
I have always wondered and wanted to edit the ~ character when entering the land of a faction... Is there anyway to do so? If not it would make a great addition
![mt8z6sr](https://cloud.githubusercontent.com/assets/9061465/5517110/f3c572ae-8893-11e4-9253-2da65dd9ad9e.png)

**Comment by oloflarsson** [comment]
Now implemented :smile_cat:

**Comment by ZombieAssassin** [comment]
=)
