### ISSUE TITLE
factions 2.7.5 \\ Exception when server enabled

### ISSUE THREAD

**Issue by ciroreed** [MassiveCraft/Factions#744]
SERVER VERSION: Cauldron-MCPC-Plus version 1.7.10-1.1236.06.212 (MC 1.7.10)

This error show after factions plugin initialization

net/minecraft/server/v1_7_R4/PlayerInventory
http://pastebin.com/gJU2Zwna

**Comment by oloflarsson** [comment]
https://github.com/MassiveCraft/Factions/issues/739
