### ISSUE TITLE
Factorization and Factions interfering. Config fix doesn't work (HELP)

### ISSUE THREAD

**Issue by arceus135579** [MassiveCraft/Factions#759]
I looked at the previous two issue reports and they have no use, since the doc page is removed. Currently on Minecraft version 1.7.10 on the modpack; ModSauce, the factorization plugin is interfering with the Factions plugin. I'm wondering with there's a way to fix the command for Factions and turn it from /f into another command, for example /fa or /fac. Factorization can also not be uninstalled since it is a client-side plugin/mod and cannot be removed. The config fix which was recommended here (https://github.com/MassiveCraft/Factions/issues/751) doesn't work, as it has been attempted multiple times, but with no success. Any help is welcome, but it would be nice if there was any other way to change /f into another command for the Factions plugin.

**Comment by oloflarsson** [comment]
I already told you there is a configuration option for this. You can change the factions /f command into whatever you want using the configuration file /mstore/factions_mconf/instance.json.

If you do not understand what I mean. Please read all of the plugin documentation.
