### ISSUE TITLE
Overclaiming issue

### ISSUE THREAD

**Issue by Asura35** [MassiveCraft/Factions#763]
My players have tried to overclaim other factons land however it displays no info and does not do anything. For example I do /f claim one in enemy territory and no information is displayed in chat, no errors in console at this point and generally nothing happens.
Please reply asap, this is a major issue. Thanks

**Comment by oloflarsson** [comment]
You need to supply much more information.
For example: What version of the server and plugins are you using?

**Comment by magnusulf** [comment]
Inactive and incomplete issue. Closing.
