### ISSUE TITLE
All factions unclaiming all land and removing faction bank.

### ISSUE THREAD

**Issue by kiammcquaid** [MassiveCraft/Factions#769]
I have factions 2.7.5 and Factions Tax 2.7.5 installed. When the server stopped earlier today, all of the factions were completely unclaimed. The factions still existed with the same players. This is causing a huge inconvenience.

**Comment by oloflarsson** [comment]
You are probably experiencing an intended feature in the plugin. Factions that can not afford their upkeep will get their land unclaimed as punishment.

http://www.massivecraft.com/factions-configure#factionstax-config
upkeepFailUnclaimall defaults to true. If you dislike the feature you can disable it by setting it to false.
