### ISSUE TITLE
Cannot map command using Essentials

### ISSUE THREAD

**Issue by Sorgrum** [MassiveCraft/Factions#770]
### Server Info
MassiveCore version: 2.7.5
Factions version: 2.7.5
Essentials version: 2.x, Build \#9, https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/lastSuccessfulBuild/ 
Plugins (11): PermissionsEx, WorldEdit, Essentials, Vault, EssentialsSpawn, WorldGuard, MassiveCore, Citizens, Factions, Sentry, PurpleIRC

### Issue Info
I have Factions installed, and on my quest to map the command /money to the factions command /f money b. However, I kept getting errors on my console saying 
`[23:54:52] [Server thread/WARN]: Could not register alias money because it contains commands that do not exist: f money b`
   
But the thing is, I could type /f money b ingame so I was thinking that it might have been an issue with Essentials. After removing it, I tried running the command again and now ingame I have the output 
`Faction economy features are disabled`
However, I have and have had ` "econEnabled": true,` during this entire process.
  
##### commands.yml
```
aliases:
  icanhasbukkit:
  - version $1-
  info:
  - einfo
  money:
  - f money b
```
##### instance.json (snippet)
```
  "econEnabled": true,
  "econLandReward": 0.0,
  "econUniverseAccount": "",
  "econChunkCost": {
    "BUY": 1.0,
    "SELL": 0.0,
    "CONQUER": 0.0,
    "PILLAGE": 0.0
  },
  "econCostCreate": 10.0,
  "econCostSethome": 0.0,
  "econCostJoin": 0.0,
  "econCostLeave": 0.0,
  "econCostKick": 0.0,
  "econCostInvite": 0.0,
  "econCostDeinvite": 0.0,
  "econCostHome": 0.0,
  "econCostName": 0.0,
  "econCostDescription": 0.0,
  "econCostTitle": 0.0,
  "econCostFlag": 0.0,
  "econRelCost": {
    "ENEMY": 0.0,
    "ALLY": 0.0,
    "TRUCE": 0.0,
    "NEUTRAL": 0.0
  },
  "bankEnabled": true,
  "bankFactionPaysCosts": true,
  "bankFactionPaysLandCosts": true
}
```

**Comment by oloflarsson** [comment]
Thank you for the first well written issue description I have seen in a long time! :smile_cat: Finally all information provided at once so I have what I need to help you :smile_cat: 

The solution in your case is to find an external plugin to create command aliases. I think commands.yml only works for top level commands. Anyhow my plugins register their commands in an unusual manner which may cause the commands.yml not to work for the factions commands.

The reasons you get `faction economy features are disabled` is because you were using the economy feature in Essentials were you not? You can put Essentials back in. I'd really doubt it's causing this issue.

And once again the solution is to use an external plugin with a better command alias system.

**Comment by Sorgrum** [comment]
> Thank you for the first well written issue description I have seen in a long time!

No problem! The way I look at it, the easier I make it for you to understand the issue, the easier it is for you to help

> The solution in your case is to find an external plugin to create command aliases

Understood. Semi-related question though: Would there be a way when listing available commands to change the root command from /f to something else like /faction? I already have `aliasesF` set, but it doesn't change the command description area (Example would be the listing in `/f help`)

> you were using the economy feature in Essentials were you not?

Are the economy features in Factions dependent on Essentials?

One last question. I'd like to make claiming plots of land a purely economical thing. Would there be a way to disregard the power aspect of Factions?

**Comment by oloflarsson** [comment]
`aliasesF` should do what you want. Just make sure it does not contain "f". The first command alias is used in the help listing.

Factions economy features depend on Vault which means it supports all economy plugins. Essentials is just one of many.
