### ISSUE TITLE
FactionsListenerMain

### ISSUE THREAD

**Issue by MrBretze** [MassiveCraft/Factions#774]
Wat is your new FactionsListenerMain ? i need for 				
if (!FactionsListenerMain.canPlayerBuildAt(player, PS.valueOf(loc.getBlock()), false)) {
					return true;
				}

**Comment by oloflarsson** [comment]
https://github.com/MassiveCraft/Factions/blob/master/src/main/java/com/massivecraft/factions/engine/EngineMain.java#L1285

**Comment by MrBretze** [comment]
Thanks
