### ISSUE TITLE
promote/demote don`t work with factions.kit.default permissions

### ISSUE THREAD

**Issue by komiss77** [MassiveCraft/Factions#775]
Server version: CraftBukkit version git-Spigot-13716d9-0 899683 (MC: 1.8)
Factions version: 2.7.5 lates build from Github
MassiveCore version: 2.7.5 from www.spigotmc.org/resources/massivecore.1901
PermissionsEx version: "1.23"

Player haw factions.kit.default permissions, they can create a factions, can to manage it. But leaders can not use command /f promote <player> and /f demote <player> (You don`t have permissions to do that). 
Add permissions factions.promote & factions.demote has no effect.
Use this command can only players with factions.* permission.

**Comment by magnusulf** [comment]
Did you add it in the plugin.yml (inside the jar) or the permissions settings for PEX, this should however not be an issue with the upcoming version of factions.

**Comment by komiss77** [comment]
I find the problem - incorrect translate. 
Sorry to disturb. 
Thank you for your work!
