### ISSUE TITLE
Can't Claim Safezone

### ISSUE THREAD

**Issue by driftkin23** [MassiveCraft/Factions#777]
Just started a new server yesterday and installed factions and massivecore all works fine everyone can create and claim land but when we try to do /f claim auto safezone we get an error and wont claim. what can I do to pass this msg.

**Comment by ulumulu1510** [comment]
You need to provide a lot more Information. Please post your Core-OS, MassiveCore and Factions versions.

Then, please post the error message as shown on your console.
