### ISSUE TITLE
Faction error ERROR Could not pass event PlayerMoveEvent to Factions v2.7.5

### ISSUE THREAD

**Issue by jojoran12** [MassiveCraft/Factions#780]
Hello  i got this error
17.01 21:11:24 [Multicraft] Skipped 3 lines due to rate limit (30/s)
17.01 21:11:24 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
17.01 21:11:24 [Server] INFO at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
17.01 21:11:24 [Server] INFO at com.massivecraft.factions.engine.EngineMain.chunkChangeDetect(EngineMain.java:676) ~[?:?]
17.01 21:11:24 [Server] INFO at com.massivecraft.factions.engine.EngineMain.chunkChangeTerritoryInfo(EngineMain.java:694) ~[?:?]
17.01 21:11:24 [Server] INFO Caused by: java.lang.NullPointerException
17.01 21:11:24 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
17.01 21:11:24 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
17.01 21:11:24 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
17.01 21:11:24 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInPosition.a(SourceFile:57) [spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:255) [spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-os7.jar:git-Spigot-f234263-2db3ea2]
17.01 21:11:24 [Server] INFO org.bukkit.event.EventException
17.01 21:11:24 [Server] ERROR Could not pass event PlayerMoveEvent to Factions v2.7.5
im using spigot 1.8.1
and massivecore 2.7.5

**Comment by oloflarsson** [comment]
`[Multicraft] Skipped 3 lines due to rate limit (30/s)`
Might have removed lines I need to see. I cant make any sense of this stack trace. It's probably cut off. Can you send me the full and uncut version please.
