### ISSUE TITLE
[Request] Protect cattle in protected lands

### ISSUE THREAD

**Issue by Sorgrum** [MassiveCraft/Factions#783]
In the case that a faction has a farm, their animals should be protected as their property, and horses in enemy territory should be allowed to be mounted.

**Comment by drtshock** [comment]
Isn't this counter intuitive? You raid someone but then you can't kill their cows, but you can steal their horses?

**Comment by Sorgrum** [comment]
I use Factions primarily for making teams amongst players as well as for land protection, not for the intended use that most servers use. It could be nice for server owners to have the option to allow for this.

**Comment by ulumulu1510** [comment]
In your case, it would make sense to code your own plugin extension for that. This is not a feature that will be part in Factions itself.
