### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by madtomic** [MassiveCraft/Factions#788]
<{factions_relcolor}§l{factions_roleprefix}§r{factions_relcolor}{factions_name|rp}§f%1$s> %2$s

How to format this so it only display faction name and nothing more.?I have **Faction_name now. how to get ride of **?

**Comment by oloflarsson** [comment]
This is a bug tracker. Not a support forum. Ask for help with configuring your server on the Bukkit or Spigot forums. This location is exclusively for software bugs.
