### ISSUE TITLE
TNT And Creeper not affecting Claimed regions!

### ISSUE THREAD

**Issue by Faller10** [MassiveCraft/Factions#790]
Hi, 
So in my server, when my players try to attack another faction, they use their creepers and tnts but somehow they don't affect the claimed land!
Can someone help me! Thanks!

**Comment by oloflarsson** [comment]
Please provide much more information.
What version of server, Factions and MassiveCore are you using?

**Comment by Faller10** [comment]
I'm using the protcol patch from spigot 1.7.X & 1.8.X, Massive Core v2.7.4 and Factions v2.7.3

**Comment by magnusulf** [comment]
Never use a different version of Factions and MassiveCore. 2.7.3 is designed to work with 2.7.3 and not 2.7.4 and vice versa. This issue might have something to do with faction flags, have you tried changing those?

**Comment by Faller10** [comment]
Ok I alredy fixed the version, but te error is still occuring! There is somehow a way to deactivate the flags?
Thanks!

**Comment by oloflarsson** [comment]
http://www.massivecraft.com/factions-configure
