### ISSUE TITLE
Factions are griefable

### ISSUE THREAD

**Issue by agentroop** [MassiveCraft/Factions#793]
Hello, I've downloaded the Factions and Massivecore plugins and they've been running fine, except for the fact that the faction's land can be griefed by anyone. This applies to SafeZone and Warzone as well. There are also no welcome messages when a person enters a faction's land. However, the faction is clearly there because of /f map. Any help would be much appreciated.

**Comment by agentroop** [comment]
I am using the most recent Faction and Massivecore plugins, as well as the latest Spigot 1.8 build.

**Comment by agentroop** [comment]
I also use PerWorldPlugins, but Factions is working for all worlds. I have that under control though, just mentioning.

**Comment by ulumulu1510** [comment]
Please never write the latest version of Factions, state your Factions and MassiveCore version-nr. (e.g 2.7.5) and the spigot core-Os version as well.

Aside from that, have you got any errors in your console, @agentroop ? If so, we need them too. (Please pastebin them if possible)

**Comment by magnusulf** [comment]
To extend on what @ulumulu1510 said. Spigot updates five times a day, so using the latest build is rare.
Have you tried on a server only with Factions and MassiveCore? If a problem still occurs it might be your configuration.
