### ISSUE TITLE
Banks stuck at 0

### ISSUE THREAD

**Issue by BlackBeltPanda** [MassiveCraft/Factions#799]
Factions version: 2.7.5
Spigot version: fa7cbf9-00eba53
Vault version: 1.5.2-b33

Using Coinage v0.2.3 for economy. (http://dev.bukkit.org/bukkit-plugins/coinage/)

Whenever players deposit money into their faction's bank, the money is withdrawn from the player but not deposited into the bank. All of the banks remain at 0. The config is default; haven't changed it. Started a fresh server with Factions 2.7.5, so haven't update from an earlier version. No errors in the logs or console.

![](http://i.gyazo.com/834f941346a570d84e5c2c2a3be96076.png)

**Comment by ulumulu1510** [comment]
Have you tried several cases with different permission groups and or different times?

Have you tried this on a test-server with just these plugins and is it still the case? Is something else maybe blocking you from putting it there?

Do any transactions with factionbanks work( f to f, f to p, ect)? If so, which ones?

**Comment by BlackBeltPanda** [comment]
I just asked the developer of Coinage and he stated that Coinage doesn't support virtual currency, though it integrates with Vault. Seems the two plugins simply aren't compatible. =/
