### ISSUE TITLE
Safezone Claiming Issues

### ISSUE THREAD

**Issue by nickrcole2** [MassiveCraft/Factions#800]
I'm running a 1.7.10 cauldron, with just Flan's Mod, a couple of expansion packs for it, Rei's Minimap, and Optifine. I'm not using any plugins that aren't really well known. (I can provide a full list of plugins if necessary).

I did /f join safezone, then I did /f claim auto to start claiming my Safezone, however it just gave me repeated CommandSender Link has been severed errors, and told me to report it here.

I relogged, and restarted, did nothing.

Let me know if you need anymore information. (I'm not a programmer so I wouldn't know :P)

**Comment by nickrcole2** [comment]
And just for the record I'm running Windows 8.1 64 bit, (That's the machine my server is hosted off of), I have the most recent version of Java 7. Also, I have the 1.8 versions of MassiveCore and Factions, almost positive they're the most recent as well.

**Comment by Badcholo** [comment]
I am also getting the CommandSender Link has been severed. But mine was while trying to /f claim square 1

**Comment by oloflarsson** [comment]
We currently don't support Cauldron. I'd like Cauldron support in Factions but have many other things we need to do as well.

**Comment by Badcholo** [comment]
what else is there to use other than cauldron for mods and plugins?

**Comment by magnusulf** [comment]
Cauldron is not supported.

**Comment by Badcholo** [comment]
Totally found something better a long time ago.
