### ISSUE TITLE
Request : Add admin features

### ISSUE THREAD

**Issue by dartasen** [MassiveCraft/Factions#801]
Hi, I post today to propose some useful additions to the administration of factions. First of all it would be convenient if the OP players could bypass the commands restrictions in the claims, and they could kick players with negative power (if blocked in the config).

It would also be very useful to add a command to restore the power to a player (no power boost), eg "/ f addpower <player> <number>", if PlayerEg has -2.34 power, an admin uses "/ f addpower PlayerEg 3", and PlayerEg will have 1.34 power.

PS: It would be really cool if the loss of power per day of inactivity and the pistons in claims could be back :3

Sorry for my bad english.

**Comment by oloflarsson** [comment]
The command `/f setpower <player> <power>` was added in a recent commit.
As for the other things you mention, are they not covered by `/f admin`?

**Comment by dartasen** [comment]
Nop, we can't kick a player with negative power event if /f admin is on (but for command restrictions i'm not sure, i would check.
