### ISSUE TITLE
Faction Bug - Enderchest - Duplicate

### ISSUE THREAD

**Issue by Retrinity** [MassiveCraft/Factions#803]
You can place enderchest in other territories and you do not lose it and give you an error message. Still it is placed.
Evidence: https://www.youtube.com/watch?v=8-lYZciNL0g&feature=youtu.be

**Comment by oloflarsson** [comment]
Supply more information. What version of server and software?

**Comment by Retrinity** [comment]
Faction: 2.7.5

Spigot 1.8 (This server is running CraftBukkit version git-Spigot-"609cd55" (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Comment by ulumulu1510** [comment]
I can't seem to be able to recreate this issue. Do you have the latest version of MassiveCore (2.7.5) installed? Are any error showing up on your logs?

Is this bug still occurring even?
