### ISSUE TITLE
Question: Factions and the Multiverse/Universe system

### ISSUE THREAD

**Issue by TagCraftMC** [MassiveCraft/Factions#804]
@Cayorion Hoping you could answer a (possibly stupid) question of mine.
With the Multiverse/Universe system is is possible to have different configs/settings for each one?
By settings I mean options located in instance.json.
Example:
MultiverseA > UnviverseA > WorldA > SettingsA
MultiverseA > UnviverseA > WorldB> SettingsB
Or
MultiverseA > UnviverseA > WorldA > SettingsA
MultiverseA > UnviverseB > WorldB> SettingsB

The reason is we're hoping to set up a few factions severs bungeecord with different levels of difficulty (Example; ServerA using claimsMustBeConnected: true but serverB using claimsMustBeConnected: false) yet still keep all the faction data together so when a player goes from ServerA to ServerB they are still in the same faction.

Thanks

Edit: This is concerning version 2.7+ as I have heard the Multiverse/Universe system has changed.

**Comment by oloflarsson** [comment]
The universe system has been removed since too few people used it, sorry.
