### ISSUE TITLE
Factions universe conf will not generate

### ISSUE THREAD

**Issue by killyouslow** [MassiveCraft/Factions#807]
Why isnt the lastest version of mcore and factions creating a factions_uconf@default file in the MStore folder @ server startup??? We all literally NEED it to disable factions perworld without jerking around with the mconf settings i.e Worldsnopowerloss etc

seriously without factions_uconf@default mcore LITERALLY has NO multiworld support !!!!

someone please help me / answer this post

PM me on bukkit or skype me @ kill_you_slow ty soo much for reading :)

**Comment by oloflarsson** [comment]
Duplicate.

**Comment by killyouslow** [comment]
WHAT kind of response is that???
i have no idea what your trying to say
But ill be patient with you anyway because i really need help,

Im using MCore version 2.7.5

Im using Factions version 2.7.5

Im Using Spigot Build Number 1649 (Minecraft 1.8.1 modified craft bukkit)

i start the server up and all files generate, massive core folder, and mstore folder

All files generate EXCEPT factions_uconf@default. which is suppose to generate @ server startup in the mstore folder

**Comment by killyouslow** [comment]
Oh never mind, i see you people made the ingenious choice to completely remove the universe config.

welp that's it for me, i wont be using mcore factions anymore
