### ISSUE TITLE
Help My Friend Cant Build

### ISSUE THREAD

**Issue by marekumas** [MassiveCraft/Factions#809]
WTF, when i played factions he cant open chests and build other too wtf hellp my

**Comment by ulumulu1510** [comment]
This is not a help forum for players. Contact your server administrator or as I think, you faction leader to resolce this issue.

**Comment by marekumas** [comment]
well im administrator and i dont know to fix it

**Comment by ulumulu1510** [comment]
Then you might want to read up on factions in its user documentation:
http://www.massivecraft.com/factions

I am pretty sure it will tell you everything you need  to run a faction succesfull. It'll tell you about all of the commands, including /f perm, rank setup in a faction and permission settings.

If you have read through thiss all, and still have questions not covered in there (which you shouldn't), you can come here again.
