### ISSUE TITLE
/f claim a gets CommandSender error

### ISSUE THREAD

**Issue by djoveryde** [MassiveCraft/Factions#811]
If i try to do /f claim a i get the following error

ERROR: Your " CommandSender Link" has been severed. This shouldn't happen.

Im using the latest version of factions. My server is a 1.7.10 server

**Comment by oloflarsson** [comment]
You are using Cauldron, right?

**Comment by oloflarsson** [comment]
https://github.com/MassiveCraft/Factions/issues/739

**Comment by Guen1982** [comment]
I am having the same issue, and so far see no fix anywhere for it. 
If you have any help you can offer it would be much appreciated. 

Guen

**Comment by djoveryde** [comment]
I had to revert to 2 versions back which fixed it for me
