### ISSUE TITLE
PvP not working for some players and "/f home" problem

### ISSUE THREAD

**Issue by 2spoopy4meh** [MassiveCraft/Factions#812]
Factions 2.7.5
Massivecore 2.7.5
Spigot 1.8 Build 27

There are currently a few players that can't be hit by anyone else. Their god is off, their mcmmo god is off, they are in no regions, they are in wilderness territory and pvp is allowed in the flags for wilderness, pvp is enabled in the world through multiverse, and pvp is enabled in the server.properties. Upon removing factions and massivecore, the players can be hit again. Upon adding them back, the players can still be hit, but eventually the glitch comes back to them and a few others. There are no errors in the console, and configs are all updated. Please attempt to recreate this event.

"/f home" does not work for me or any other players on my server. When the command is issued, players receive a message saying they will be tped to the home of their faction in 3s if they do not move. They do not move for about 20-30 seconds and nothing happens. They move and it tells them their teleportation has been cancelled due to movement. I have tested it myself, and it does not work. You can pop on mc.ptcruisercraft.com and test it out if you want as well. 

If anyone needs any other information, then I will provide it. Thanks.

**Comment by oloflarsson** [comment]
Please create a new server from scratch with only Factions and MassiveCore installed and see if the issues remains. It could be that another plugin is conflicting.

**Comment by oloflarsson** [comment]
Did you figure out what caused this issue?

**Comment by 2spoopy4meh** [comment]
Pvp problem wasn't a factions issue I think, but I have no idea what the /f home issue is. I closed the issue, because there was another /f home not teleporting issue opened (Issue 820).
