### ISSUE TITLE
DTR Factions?

### ISSUE THREAD

**Issue by LynchedAcoustics** [MassiveCraft/Factions#813]
Anyway for anyone to help out? i am looking for a DTR factions plugin mostly like Kohi's Faction plugin. (ip if you want to check it out: kohi.us) anyways if you can help out with finding a developer or if you have the plugin in hand that would help alot.

**Comment by oloflarsson** [comment]
This issue tracker is a place where you suggest features or more importantly report bugs within Factions itself. Since this seems to be neither a bug or feature request I suggest you go ask on the Spigot or Bukkit forums instead.
