### ISSUE TITLE
Cauldron 

### ISSUE THREAD

**Issue by iKays** [MassiveCraft/Factions#817]
Hey for some reason when I do /f claim a. It keep saying CommandSender Link.. has been servered. and NO error in console! :( Idk why! and also Im using Cauldron.

**Comment by iKays** [comment]
ERROR: [Factions] Plugin Factions v2.7.5 has failed to register events for class com.massivecraft.factions.spigot.EngineSpigot because org/bukkit/event/player/PlayerInteractAtEntityevent does not exist ?

**Comment by magnusulf** [comment]
Cauldron support is broken, you can however use Spigot.
