### ISSUE TITLE
Change this message when creating a new faction.

### ISSUE THREAD

**Issue by madtomic** [MassiveCraft/Factions#818]
You lost "100 Gold" since did create new faction.

This is bad English and please change this or make the all the faction related messages customizable.

Please change it to "You spent "100 Gold" to create a new faction."

Thanks,

**Comment by ulumulu1510** [comment]
I am working on this issue now. It is actually not that easy since this message is constructed dynamically and thus used for other purposes aswell. I have messaged my changes to Cayorion/oloflarsson and we will see how we want to resolve this issue.

**Comment by madtomic** [comment]
Thank you, finally. 😊

**Comment by madtomic** [comment]
Any news from the team?

**Comment by ulumulu1510** [comment]
The work ia being iterated over, but the changes are already at quality controle stage, so expect this change to come to github within the next week. :)

**Comment by ulumulu1510** [comment]
This has now been implemented. @oloflarsson , you can close this ticket.

**Comment by madtomic** [comment]
Exciting! Thank you again for working on this!
