### ISSUE TITLE
Editing messages displayed by factions

### ISSUE THREAD

**Issue by killyouslow** [MassiveCraft/Factions#821]
im writing this to ask, is there a way to change the color and format of most of the basic messages that factions puts out? maybe like a lang file or something?

any help is appreciated :D

**Comment by ulumulu1510** [comment]
As of currently, there is no Lang File and you cannot change the color or format of the messages.

Most messages are not static, but dynamic and thus change a lot while playing. Making these messages configurable would probably be more confusing than helpful to people who don't know coding.

**Comment by killyouslow** [comment]
would be nice to add a lang to edit the static messages, ty for the reply :)

**Comment by ulumulu1510** [comment]
We have added Mson messages (clickable/hoverable messages) this year, which makes it practically impossible to have well a constructed and working lang file. But on the other hand, it makes Factions much more intuitive to use. We should consider a Lang file in a total rework, but such is not planned.
