### ISSUE TITLE
Config option to manually add items to open blacklist

### ISSUE THREAD

**Issue by djoveryde** [MassiveCraft/Factions#822]
I have a factions server & currently im finding that a lot of the mods bypass protection (ie. Iron Chests being 1 that lets players access it). Is there a way of adding whole mods to a blacklist for factions or at least items so you can manually protect things?

Basically items like the ME Drive lets players outside faction/towny open them and remove the storage units inside. Same for armor stands and many other items. If you can add an area into factions that acts as a manual blacklist for opening items that would be great.

**Comment by ulumulu1510** [comment]
The plugins can write a factions integration, which is actually not that hard. It is not up to the Factions authors to do that, rather go and ask the plugin developer to do so :)

**Comment by djoveryde** [comment]
Which plugin developer would I ask? 

Adam Drury (Senior Workshop Engineer, West Wiltshire Micros)

**Comment by ulumulu1510** [comment]
You should ask all of the plugins authors of which plugin you want a faction integration for.

**Comment by djoveryde** [comment]
It's not for a plugin, it's to add mod items to factions protection as it's missing a lot of mods out protection wise, the towns plugin has an integrated blacklist which I'd love factions to have as its why people have been switching to towns. I'm more of a factions guy myself.

Date: Sun, 1 Mar 2015 06:57:26 -0800

**Comment by magnusulf** [comment]
There is a config option called materialsContainer, which is the materials considered containers. It has support for mods, just add the materials to that config.
