### ISSUE TITLE
Economy features will not enable

### ISSUE THREAD

**Issue by jdbeard10** [MassiveCraft/Factions#825]
We just downloaded Factions for our server. We have Vault, and should have all the necessary addons that go along with it. When we tried to use the /f money commands, we are given the message, "Faction economy features are disabled," when in the .yml files they are clearly enabled. Please help!

**Comment by ulumulu1510** [comment]
Is your server maybe lacking a real economy plugin? Vault doesn't replace having one, it serves as a brigde for multiple plugins to communicate more easy with each other. If you have one:

Please state the following version:

Massivecore ?
Factions ?
Spigot/bukkit?

**Comment by ulumulu1510** [comment]
No further information has been told in over 6 months.

**Comment by Tchekda** [comment]
I have the same, version of spigot : 1.8 ; version of Faction : 2.8.21; version of MassiveCore : 2.8.21
