### ISSUE TITLE
Essentials Chat / Prefix / color chat

### ISSUE THREAD

**Issue by JustGr00ve** [MassiveCraft/Factions#827]
Hello I've been trying to get essentials Chat to work with Prefix / Color chat and It hasn't been workings. So i thought maybe its a plugin blocking it, well I found out that its FACTIONS, 

I'm using R: Factions 2.7.5 for 1.8.1 Dec 19, 2014

If u can help me fix this problem please contact me.

**Comment by ulumulu1510** [comment]
Please provide us with more info:
MassiveCore version?
Factions version?
Bukkit/spigot version?

What is happening to your chat exactly? Please provide screenshots and eventual server logs, if an error occurs.

Out of the blue, I guess this bug has been fixed in a recent commit.
https://github.com/MassiveCraft/Factions/commit/29a4feeff69e25aee6d82c8273a6640ee86a65b8

**Comment by JustGr00ve** [comment]
MassiveCore version -  2.7.5
Factions Version - 2.7.5 for 1.8.1
Spigot version - 1.8.1

What is happening to your chat exactly? I'm trying to make prefixes and color chat  for my groups and they wont show with (essentials chat), But then i deleted factions and it started to work..

**Comment by ulumulu1510** [comment]
Alright then. If the issue disappeared, you can close this issue yourself.

**Comment by JustGr00ve** [comment]
No the issue is that i want factions, and the prefixes with color chat, But Faction wont let me unless i delete it. is there a way to get factions to stop messing with essentials chat

**Comment by ulumulu1510** [comment]
You can completely disable factions chat prefix in the MConf. "chatSetFormat" is the value you want to change to false I believe.

**Comment by JustGr00ve** [comment]
where can I find this MConf. "chatSetFormat"    I'm Kinda slow when it comes to faction plugin :(

**Comment by ulumulu1510** [comment]
http://www.massivecraft.com/factions-configure

Go read through it before you post another message. You should have done this before comming here, as it might already contain the answers you seek.
