### ISSUE TITLE
f flag monsters makes monster peaceful 

### ISSUE THREAD

**Issue by ashower** [MassiveCraft/Factions#833]
the flag monsters affects not only spawning of but also aggro of mobs 
 [Factions] Enabling Factions v2.7.5 , Massivecore 2.7.5
API version 1.8-R0.1-SNAPSHOT

basically whenever player is inside the faction with flag monsters set to "no" the aggroed mob / mob spawned with egg becomes peaceful to the player.

last i checked, the flag affects only spawning of mobs?

**Comment by ulumulu1510** [comment]
The flag does indeed also affect targeting. I am already looking into this issue, since it has been known.

I believe it is an intentional, so mobs couldn't attack players in peacefull factions.

But yes, the issue will be looked at in the near future.

**Comment by oloflarsson** [comment]
This issue should now be fixed. It will be published next time we release new plugins.
