### ISSUE TITLE
Piston-Claim Problems

### ISSUE THREAD

**Issue by MGNKylan** [MassiveCraft/Factions#839]
I want people to be able to use pistons to push blocks in claims, so I looked it up and I learned I needed to set pistonProtectionThroughDenyBuild to false, but I cant find it in the .json. Any way I can do it?

**Comment by ulumulu1510** [comment]
@MGNKylan
Inside of claims, people should have no problem to push blocks with pistons, given they have the build access (managed through f perm) in said area.

The mconf setting is present in our dev versions on github, but is not yet available through bukkitdev or spigot. Also, this completly removes this "do you havee build rights here" check, so please be carefull using this setting,.

Unless you compile MassiveCore and Factions yourself, there is no way currently to get this feature.

**Comment by MGNKylan** [comment]
I don't know if I didn't explain enough or I'm not understanding you, but
there's red stone-slimeblock contraptions that end up stopping as soon as
they hit a claim, that's what I want to fix, so people can raid with them.

**Comment by ulumulu1510** [comment]
For this purpose, you will need this mcond setting set  to false, your assumption is correct.

But the second part of my old message is still  true: It is not yet available through bukkitdev or spigot. If you can compile it yourself, you can use it already.
