### ISSUE TITLE
No TnT and Creeper explosions in claimed areas

### ISSUE THREAD

**Issue by RaaFkOnIjN** [MassiveCraft/Factions#840]
He there,

When my server bacame bigger and bigger and people want to raid bases, I found a weird bug. Creepers and tnt don't explode in claimed areas. I was looking in the config and tried everything I could but it still doesn't work.
Here are some config settings.

factions_mflag \ explosions.json

{
  "priority": 6000,
  "name": "explosions",
  "desc": "Can explosions occur in this territory?",
  "descYes": "Explosions can occur in this territory.",
  "descNo": "Explosions can NOT occur in this territory.",
  "standard": true,
  "editable": false,
  "visible": true
}

factions_mflag \ offlineexplosions.json

{
  "priority": 7000,
  "name": "offlineexplosions",
  "desc": "Can explosions occur if faction is offline?",
  "descYes": "Explosions can occur if faction is offline.",
  "descNo": "Explosions can NOT occur if faction is offline.",
  "standard": true,
  "editable": false,
  "visible": true
}

Is there something wrong in de config or is this a factions problem?

**Comment by oloflarsson** [comment]
It could also be another plugin is blocking explosions?
Have you tested setting up a server from scratch with only MassiveCore and Factions installed?

**Comment by Irule8** [comment]
This might help. https://www.youtube.com/watch?v=V5noV_8QFNQ

**Comment by oloflarsson** [comment]
Thanks!
