### ISSUE TITLE
Enemy a player and not a faction?

### ISSUE THREAD

**Issue by tunasushi** [MassiveCraft/Factions#841]
At the moment, someone can temporarily leave "Enemy" status by quickly disbanding then creating a new faction. This mainly applies to single-person factions, so is there a way to set a person as an enemy, and then all factions they are a part of to be set as an enemy too? Thanks!

**Comment by magnusulf** [comment]
No this is not currently possible. Since enemy is only useful when attacking someone, you can enemy them when attacking and this a player changing faction to avoid enemy status isn't a problem.
