### ISSUE TITLE
No One Can Claim Land

### ISSUE THREAD

**Issue by WolfvineGaming** [MassiveCraft/Factions#842]
No one on my server can claim land in factions, SafeZone, and WarZone. WTF is with this plugin!

**Comment by ulumulu1510** [comment]
@WolfvineGaming
I can get nothing out of your report. State your problem according to these question:
Have you read the userguide?
 - If not, follow the instructions in there.
Have you set up the permissions correctly?
 - If not, do so accord to the userguide.
Userguide:
http://www.massivecraft.com/factions

If you have done all this, please state the following:
What is your version for:
 - Factions
 - MassiveCore
 - Bukkit/Spigot

Only if you follow this I am willing to help you further.  Spite and anger will not get you your questions answered.

**Comment by oloflarsson** [comment]
Thank you @ulumulu1510! :smile_cat:
