### ISSUE TITLE
opening enderchests as member in safezone

### ISSUE THREAD

**Issue by phillgates2** [MassiveCraft/Factions#844]
im getting Hay! Sorry, but you can't use that here. in a safe zone when i try and open an enderchest with betterenderchest plugin and a hypermerchant plugin all perms are right and no errors come up in  console it used to work before just wondering what im missing using the latest factions masivecore and factionsdynmap that came with the factions dynmap folder
thanks 
phill
![mcp](https://cloud.githubusercontent.com/assets/3883076/6995318/0ad084ba-db83-11e4-8d61-f4b5d144a4a3.png)
![mcp2](https://cloud.githubusercontent.com/assets/3883076/6995321/65bc5c0a-db83-11e4-83b3-32fe7c06f02c.png)

**Comment by ulumulu1510** [comment]
This errormessage isn't sent by factions, but by Worldguard.Thus, I would look over the worldguard region and whether it is set up correctly.

**Comment by phillgates2** [comment]
thanks works now, not sure what was blocking it as there was one thing in global region and no other regions in those 2 areas
