### ISSUE TITLE
Unknown Command: Factions Plugin

### ISSUE THREAD

**Issue by Mario1733** [MassiveCraft/Factions#845]
So, this morning, my Co-Owner logged into Minechat, and players were complaining that the Factions Plugin was not working anymore. So, when I got on, I type /f (The alias) and it said "Unknown Command, type /help for help"

I don't know what happened for everything to go wrong, but the Factions plugin is still installed in the Bukkit Lists, and the configuration files are all intact, and they are in the exact place that they used to be in. If you need me to post the /mstore plugin files for everything I will, but for now, I wont unless needed too.

**Comment by oloflarsson** [comment]
Have you figured out what was wrong yet?
