### ISSUE TITLE
"CommandSender Link" has been severed.

### ISSUE THREAD

**Issue by Randomdude818** [MassiveCraft/Factions#847]
This is happening on the Wizard Academy official server. I was trying to claim land. I am using the technic launcher to play this modpack. This is the third time i've logged onto this server. Relogging is not fixing the issue. I tried to contact an admin, and they told me the problem is unfixable, so I came here for help. 

Claiming land in factions is obviously very important, and I would like this problem resolved.

**Comment by ulumulu1510** [comment]
Reference here:
https://github.com/MassiveCraft/Factions/issues/739

This post can be deleted as it is a duplicate.

**Comment by oloflarsson** [comment]
Cauldron is dead. We do not support Cauldron, sorry.
