### ISSUE TITLE
Territory message appearing twice.

### ISSUE THREAD

**Issue by Ionaru** [MassiveCraft/Factions#848]
Hello, I have an odd bug with Factions 2.7.3. The message that shows when you enter or leave faction territory, appears twice. 

![2015-04-15_23 52 42](https://cloud.githubusercontent.com/assets/3472373/7169994/b0ae346e-e3ca-11e4-8e33-26cc860cc166.png)

Running:
- Cauldron 1.7.10-1.1291.01.0
- Factions 2.7.3
- MassiveCore 2.7.3
- Enjin Minecraft Plugin 2.7.2
- Essentials 2.13.1
- Lagmeter 1.15.1
- WorldEdit 6.0
- WorldGuard 6.0.0 beta 05

**Comment by ulumulu1510** [comment]
We don't offer support for lower versions since the bug might be fixed already. I am well aware that Cauldron and version 2.7.5 don't work together nicely Because cauldron is stuck at 1.7.10

You might want to try a  clean server with only massivecore and Factions on it and see if the error persist.

**Comment by Ionaru** [comment]
Yes, the error still happens with just Factions and MassiveCore installed on the server.

**Comment by oloflarsson** [comment]
We do not support Cauldron, sorry.

**Comment by DraksterAU** [comment]
Considering Cauldron support seems to be removal of an if statement its a true shame.........

**Comment by ulumulu1510** [comment]
@DraksterAU

I told you in the other post that it will not be that easy. And if you are not willing to help us fix a problem, hold your spite back.

**Comment by DraksterAU** [comment]
It is... if you use this.getSender() in that portion of the code instead of the new commandSender, things work perfectly..
