### ISSUE TITLE
Renaming "Wilderness" faction

### ISSUE THREAD

**Issue by MedicinalSnacks** [MassiveCraft/Factions#850]
Hello,

Iv'e accidentally renamed the "Wilderness" faction. After accidentally re-naming it I changed it back to its  original name: 'Wilderness". However, the faction seems to of lost its dark green text seen upon entering wilderness. is there any way to fix this?

**Comment by cooperisdunn** [comment]
Bump.. Still looking for an answer

**Comment by oloflarsson** [comment]
You can delete it from the database and restart the server. It will be recreated.
