### ISSUE TITLE
Ar build error

### ISSUE THREAD

**Issue by Moocow9m** [MassiveCraft/Factions#851]
Downloaded then put into eclipse. Errors: Description	Resource	Path	Location	Type
AR cannot be resolved to a type	ARMPlayer.java	/Factions/src/com/massivecraft/factions/cmd/arg	line 13	Java Problem

**Comment by Moocow9m** [comment]
Using java 7 by the way

**Comment by ulumulu1510** [comment]
It looks to me, like you are trying to mix a released (factions)  and un-released build (MassiveCore).

We are heavily working on MassiveCore and thus, changes to the github repository occure often.
To stay updated in eclipse, you need to import both (MassiveCore and Factions) repositories into eclipse, preferably through cloning them through git. Only if both projects are at the latest commit, they will work together nicely.

Java 7 is completly fine.

If you run into other issues,  don't hesitate to ask but bare in mind, we are not teaching you how to use eclipse/git.

**Comment by Moocow9m** [comment]
I have imported massive-core jar file from the main site as a library is that a reason? Because I thought they where the same build as the master version of this.

**Comment by Moocow9m** [comment]
Sorry but it's beed a while sence i have built a jar in eclipse   much less spigot

**Comment by ulumulu1510** [comment]
Yes, this is the reason:
If you want two versions of Massivecore and factions which are working together, you need to use the released versions with the same version-nr or both absolute latest github builds. Otherwise, you will run into issues, espicially since we have made a lot of improvements internally lately.

**Comment by Moocow9m** [comment]
Thanks build successful!
