### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by titivermeesch** [MassiveCraft/Factions#856]
Can someone help me please,
I put the factions and massicore jar file in the plugins map.
I can only do the /f help command.
If I do /f create or other commands, he says "A internal error..."

Can you help me please

**Comment by ulumulu1510** [comment]
Please go and read our userguide at massivecraft.com/factions and follow all steps carefully. Further, If you still encounter the issue, you need to provide much more information:
MassiveCore version, Factions  version bukkit/spigot versions, error logs... basically all you can provide.
