### ISSUE TITLE
FactionChat - Console

### ISSUE THREAD

**Issue by farget92** [MassiveCraft/Factions#857]
Hello,

Today I discover interesting bug of FactionChat, and I don't know any solution.
I,as console, typed in command > fchat
And this is the error: http://hastebin.com/igosobacik.profile

And now, some information about server.
We are running it on Java 7SU75.
This server is running CraftBukkit version git-Spigot-9284e9b-7722428 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

If you want plugin list, just type me.
Thanks.

**Comment by ulumulu1510** [comment]
Please give this error to the FactionChat author (james137137), because we didn't write this plugin. I cannot help you here.
