### ISSUE TITLE
Offline Factions?

### ISSUE THREAD

**Issue by Malvagio87** [MassiveCraft/Factions#858]
I just came back after not playing for a year or so and I could've swore there was a config option to protect factions that were considered offline.  Does this still exist (did it ever) or was it abandoned in later builds?

If so would it be okay for me to write a plugin that does this and then sell it on Spigot like you sell FTax (which I bought) and FDynmap?

**Comment by oloflarsson** [comment]
You can read the documentation on http://www.massivecraft.com
