### ISSUE TITLE
Disabling were claim was claimed

### ISSUE THREAD

**Issue by griffen4** [MassiveCraft/Factions#860]
Hi quick question so I own a server and with the newest factions I need to disable when people do /f claim and it shows what chunk they claimed because people who make videos on my server are getting mad. If you know how to fix this please let me know thanks!

**Comment by oloflarsson** [comment]
Players on my server is not getting mad. I don't see an immediate need for this feature. There's a way to hide the chat if you are making videos. F2 or something.
