### ISSUE TITLE
Random particle Console Spam 

### ISSUE THREAD

**Issue by djoveryde** [MassiveCraft/Factions#864]
I've randomly started getting an error that spamming console. Im using 1.7.10 MC on Cauldron & Factions 2.7.2 (Newest Factions version I get an error when I type anything /f related.

Any ideas on what is going on. This only started today and server has been running for months.

http://pastebin.com/U886kvz9

**Comment by oloflarsson** [comment]
Cauldron is dead. We do not support Cauldron, sorry.

**Comment by djoveryde** [comment]
Actually cauldron was revived and Is now called kcauldron
