### ISSUE TITLE
Found error on console

### ISSUE THREAD

**Issue by MithrandirCraft** [MassiveCraft/Factions#865]
I was looking through my logs and found this:

http://pastebin.com/JM0zzA9w

**Comment by magnusulf** [comment]
Under which circumstances does this happen?

**Comment by MithrandirCraft** [comment]
No idea, it's been a really long time since I opened this...

I haven't seen this error any more. I just thought you guys might be interested in knowing.

I remember seeing this error quite often some time ago, but I can't attribute it to any specific situation.

**Comment by magnusulf** [comment]
This bug report is no longer happening and not reproducible. Closing.
