### ISSUE TITLE
Command problem

### ISSUE THREAD

**Issue by j3rma1n** [MassiveCraft/Factions#866]
Hello,
2 plugins that have a enourmes conflict is factions and enjin every command for factions like /espawn doesnt work anymore because enjin used /e as thier base command so its imposible to get out of a enemy teretory because you cant do /espawn or /etpa or any of those commands how do i fix this ?

**Comment by ulumulu1510** [comment]
The blocked commands can be configured/changed in your mstore files.

If you don't know what I am talking about, please read the userguide on massivecraft.com/factions
