### ISSUE TITLE
Player can overclaim any land

### ISSUE THREAD

**Issue by Endothelium** [MassiveCraft/Factions#869]
Hey guys.

I am actually using cauldron-1.7.10-1 so it's forge 1.7.10 + spigot.
I am trying to use your plugins but i have a lot of trouble:

-I tried to use 2.7.5 but it's not compatible with 1.7.10 cauldron ( ACACIA DOOR problem)
- I tried to use 2.7.4 but the plugin don't load at all, not even an error.
- I can use 2.3.0, but players on the server can claim any land even if they doesn't have enough power.

Here my plugin list : CratesPlus, ObsidianBreak, WorldEdit, MassiveCore, ColoredSigns, MassiveBooks, Vault, HealthBar, PermissionsEx, KillerMoney, WorldGuard, Lottery, iConomy, ClearLag, Modifyworld, ProtocolLib, AutoSaveWorld, Essentials, Jobs, Citizens, MassiveHat, ServerSigns, EssentialsSpawn, CreativeGates, LWC, Orebfuscator3, ChestShop, EssentialsChat, RandomTP

What should i do? I tried to recompile myself 2.7.5 to make it work with 1.7.10 cauldron but no success.
I can't upgrade my MC to 1.8 cause i use a lot of mod forge for 1.7.10.

Thank you

**Comment by magnusulf** [comment]
Cauldron is not supported by its author, and we do not support it either.
