### ISSUE TITLE
Config - Exceptions on Faction Member Limit

### ISSUE THREAD

**Issue by Danosaurous** [MassiveCraft/Factions#873]
Hello.
I'm wanting to have all factions to have a max player limit of 5. But then I would also like to have a few permanent factions that can have infinite players, how would I do this?

Thanks in advance,
Dan

**Comment by ulumulu1510** [comment]
You would likely code a little expansion to factions which takes care of this. Currently, with factions as it is, you cannot limit the players a faction can accept per config snd we are not likely to add this feature, but you may of course submit a PR if you wish so.

**Comment by Danosaurous** [comment]
Okay. Thank you.
