### ISSUE TITLE
disable these default factions

### ISSUE THREAD

**Issue by madtomic** [MassiveCraft/Factions#876]
![factions](https://cloud.githubusercontent.com/assets/6004542/7904720/7c7815a0-07d5-11e5-81ec-071313c1013a.png)

How to disable this? I don't need SafeZone and WarZone factions.

**Comment by madtomic** [comment]
I tired /f admin on

Then I join the factions and disband them but they come back after server restart.

Can someone help?

**Comment by oloflarsson** [comment]
They are system factions, not intended to be deleted.
