### ISSUE TITLE
Conflict with Factorization

### ISSUE THREAD

**Issue by spruill7716** [MassiveCraft/Factions#877]
I installed the Factorization mod lately and realized it had a /f command alignment that conflicted with factions. I saw some other posts about this issue but the links that were used to provide a "solution" were all dead. Any suggestion?

**Comment by magnusulf** [comment]
What exactly is your issue? Conflicting basecommand aliases?
You can change the basecommand aliases for factions in your mconf.

**Comment by spruill7716** [comment]
Sorry didn't even realize you could do that. Thanks a ton!
