### ISSUE TITLE
multiworld support

### ISSUE THREAD

**Issue by dodieboy** [MassiveCraft/Factions#879]
i have set this in my config:
{
  "aliasesF": [
    "F"
  ],
  "worldsClaimingEnabled": {
    "standard": false,
    "exceptions": [
      "world,world_nether"
    ]
  },
  "worldsPowerLossEnabled": {
    "standard": false,
    "exceptions": [
      "world,world_nether"
    ]
  },
  "worldsPvpRulesEnabled": {
    "standard": false,
    "exceptions": [
      "world,world_nether"
    ]
  },

but it still work on all world on my server (lastest bukkit 1.8.6 server)

**Comment by dodieboy** [comment]
i also diable disable aspects using the massivecore /usys u, but i still can claim land and other thing from faction in other world that i dont want it to enable

**Comment by magnusulf** [comment]
Do you have /f admin mode on? If yes then disable it.

**Comment by dodieboy** [comment]
I off /f admin and deop my myself and I still can claim at all world

**Comment by Enrux** [comment]
The ***worldsClaimingEnabled*** works fine, the problem is that even if you disable claiming in certain worlds they will be all wilderness, so it seems like there is no way of disabling Factions in certain worlds?

**Comment by oloflarsson** [comment]
This is wrong: "world,world_nether"
This is right: "world", "world_nether"
