### ISSUE TITLE
Two Errors (Console)

### ISSUE THREAD

**Issue by Ethan-OP** [MassiveCraft/Factions#884]
Here are three console errors I am experiencing running the latest version of Factions (2.75) and the latest of Spigot (1.8.7). I am unaware of what the physical consequences of the errors are (if that is the case at all):

Error 1: http://gyazo.com/761900f46e4aa1c5633856b8925b8fa9
Error 2: http://gyazo.com/0c66456303891f104a8b08af7c335872
Error 3: http://gyazo.com/7525ed1dadd732c037cea970a3b0e1c3

Thanks for the help in advance!

**Comment by ulumulu1510** [comment]
These are all Nullpointer, which makes it interesting in some of these cases.

All three errors say that a faction is null, but it should always be a faction present which makes me wonder under what circumstances and where this happens.

**Comment by Ethan-OP** [comment]
Hello,

Thank you for the response! These errors seem to occur after the faction board cleaner executes, so that is probably the root of the issue. Hopefully we can get them resolved!

**Comment by ulumulu1510** [comment]
I have not been able to track down this bug in all this time since the issue has shown the first time. Has it ever happend to you again @Ethan-OP? If so, we need to discuss the issue more deeply.

**Comment by ulumulu1510** [comment]
The OP has not posted since. If this is still an issue, please open  new issue with all the information needed.
