### ISSUE TITLE
Plugin translation

### ISSUE THREAD

**Issue by MithrandirCraft** [MassiveCraft/Factions#888]
Hello. I'm wondering how I could translate all of the plugin's messages to my own language.

If there is any efficient method, I would like to know. If not, I would like to suggest one to be implemented.

**Comment by AnonymousMW3** [comment]
You can decompile, translate and compile the plugin :)

**Comment by MithrandirCraft** [comment]
I guess I'll have to do that.

**Comment by ulumulu1510** [comment]
You can always work with us and make a pull request to create a way to translate the plugin.

We as the developement team don't have the time to do so, but I could surely guide you on how to do a proper PR.
