### ISSUE TITLE
Factions not recognising FE

### ISSUE THREAD

**Issue by mccallan8872** [MassiveCraft/Factions#890]
I have in the past and am currently using FE as my economy plugin, and factions to add some fun to my server. Unfortunately they seem to now be incompatible and I don't know why but it is vital that this is fixed asap as it's one of the best and only plugins usable for non-essentials servers...
https://www.spigotmc.org/resources/fe.723/

I have used /vault-info on my server and I can verify that it is recognising FE... but factions itself is not showing up at all... something is wrong but economy isn't recognising itself despite it being enabled with factions in the config.

**Comment by oloflarsson** [comment]
Try updating to 2.8.0. I improved support for "hot swapping" of economy plugins there.
