### ISSUE TITLE
Factions enemyed to wilderness

### ISSUE THREAD

**Issue by 50ouncebrew** [MassiveCraft/Factions#891]
Which folder is it in so i can make it so factions cant enemy wilderness? i looked at every folder i cant find it :/

**Comment by MithrandirCraft** [comment]
Hmm this happens on my server as well. I haven't been botheret to disactivate it, but I might be capable of finding it for you if you answer my questions:

Isn't enemying wilderness necesary for players to attack factionless players? (As factionless players are automatically Wilderness members.)

If not, why should we prevent players from enemying wilderness? Just so the faction prefixes don't show up red for wilderness players maybe?

**Comment by 50ouncebrew** [comment]
Its cause people enemied to that faction cant tp away or anything

**Comment by ulumulu1510** [comment]
Even if this is a very old issue, I perceive this as a feature rather than a bug. If a factions chooses to enemy wilderness to be able to attack its members any time, it has to live with the downside of not teleporting inside of it.
