### ISSUE TITLE
EngineEcon::takeOnLeave(EventFactionsMembershipChange) Lag Spike.

### ISSUE THREAD

**Issue by Exter62** [MassiveCraft/Factions#895]
Hi dude, 

I'm writing today for ask you about something (Sorry for my bad english).
So, I've a Server with Factions / Massive Core and One of My plugin using faction.
My problem is EngineEcon::takeOnLeave make my server lag ! D:.

   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event

       1.86%	1,121.49%	 17.94 s	   560.75 ms	 0.0	       0.0k	    

What i don't understand is why this Listener is enabled beacause i don't use econnomy :/
I hope you can help me. 
Thanks :+1:  :)

**Comment by oloflarsson** [comment]
You probably have an economy plugin installed without being aware. For example Essentials, which is an economy plugin. You should disable the economy features from within the Factions configuration to get rid of this lag spike.
