### ISSUE TITLE
Error? Much confused!

### ISSUE THREAD

**Issue by SugarRealms** [MassiveCraft/Factions#897]
We have a medium sized server that randomly stopped working, without a restart! We need this fixed ASAP, as our server isn't playable without this plugin. We did edit one thing, but I don't see why it would make a difference, we edited
  "worldsClaimingEnabled": {
    "standard": true,
    "exceptions": [MobArena]
And added the MobArena function, it was working perfectly for quite some time, and we didn't edit anything else. It then randomly disabled factions and stopped working, without a reload or restart. Any help would be nice.

Error:
http://pastebin.com/ZBAauGpv

**Comment by oloflarsson** [comment]
INFO com.massivecraft.massivecore.xlib.gson.JsonSyntaxException: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated string at line 425472 column 28 path $.-73,395

You have mistyped a file somewhere in the database?
