### ISSUE TITLE
Faction "balance" reset on server reboot?

### ISSUE THREAD

**Issue by OurSickStory** [MassiveCraft/Factions#899]
Where is the money store by default, 
mstore/massivecore_aspect/factions.json is empty, and i see no other files with any type of money in it.
After every reboot even after /save-all factions money is lost.

**Comment by oloflarsson** [comment]
You are looking in the wrong database location.
The Faction balances are not in that file and has never been.

**Comment by OurSickStory** [comment]
Then were is it stored?
 "default": "flatfile",
    "flatfile": "flatfile://mstore",
says /mstore, but there is no FILES in there anywhere that have faction
money in them.

**Comment by oloflarsson** [comment]
The Faction money is stored in the Economy plugin.
