### ISSUE TITLE
Issue with permissions

### ISSUE THREAD

**Issue by rewtie** [MassiveCraft/Factions#901]
Right now, everybody in my server has permissions for factions. I'm trying to make it so only a certain group has permissions to create and use factions, but it seems everybody has permissions by default. I have not added any permissions to any groups. How can I make it so only a certain group can use factions and so that everybody does NOT have the permissions by default.

**Comment by djtev** [comment]
deny this permission node - factions.kit.default - for those who you don't want having factions perms. then give the rank you want to have factions access that node

**Comment by oloflarsson** [comment]
Thank you @djtev.
