### ISSUE TITLE
 [Error] Error occurred while enabling Factions v2.8.0 (Is it up to date?)java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by robotnikthingy** [MassiveCraft/Factions#904]
I get the following error from factions during startup

http://pastebin.com/1YUgdkdN

using spigot 1.8.7

**Comment by ulumulu1510** [comment]
Whenever you post some error about factions,  also state the version of massivevore you are using. In this case, I believe that eother the versions of factions and massivecore are not the same or you don't have massivecore in your plugins folder at all.

**Comment by robotnikthingy** [comment]
ok, i think that was the problem, thanks
