### ISSUE TITLE
problem faction claim no possible

### ISSUE THREAD

**Issue by LeaDerzRS6** [MassiveCraft/Factions#905]
hello,

when i want claim, i look this : 

http://image.noelshack.com/fichiers/2015/29/1437146687-capture.png

who as the anwser for repare this problem ?

**Comment by ulumulu1510** [comment]
Please state your bukkit/massivecore and factions versions whenever you are creating an issue.

You are most probably still using a bukkit version which is a 1.7.x  cauldren file. We do not support cauldron since it is dead and developement does not continue.

**Comment by oloflarsson** [comment]
Yep, Cauldron is the issue. We do not support Cauldron, sorry.
