### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Jochee** [MassiveCraft/Factions#907]
how I can edit the code so that when someone enters enemy territory, you will remove the fly command, I'm new at this and I don't see very clear to code haha
if (player enters the enemy terrotorio) {
player.fly = false;
}
something like that! but not where they write that.
sorry for the English translation.

**Comment by ulumulu1510** [comment]
@Jochee 
In this code in EngineMain we detect a chunk change.
https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/engine/EngineMain.java#L663

You can then check the players faction relationship to the owner faction of the chunk he is walking into. If that equals to Enemy, you can set flying to false. I don't have the exact code for setting  the player non-flying, but the chunk change code is present there ;)
