### ISSUE TITLE
Can't edit enemy terrain without /f admin

### ISSUE THREAD

**Issue by darkwolf706** [MassiveCraft/Factions#908]
I can't destroy blocks on my enemy's territory without /f admin. I've looked in configs, asked my hosts, but I can't figure it out.

**Comment by ulumulu1510** [comment]
.... This is the way it is standart to be, unless your enemy has set his fperm otherwise. Any faction has the power to  set which relation can edit its territory, whether that be an enemy or ally buildpower can be set to yes or no for each relation.

**Comment by darkwolf706** [comment]
How can I change that? I want enemies to be able to destroy eachother's bases.How can I change that? I want enemies to be able to destroy eachother's bases.

**Comment by oloflarsson** [comment]
http://www.massivecraft.com/factions-configure#factions-perms

**Comment by darkwolf706** [comment]
Is there a way to set default perms for new factions?

**Comment by oloflarsson** [comment]
Yes. Read the documentation allready :smile_cat:.

**Comment by darkwolf706** [comment]
I don't know what I'm looking for. That's the problem.

**Comment by darkwolf706** [comment]
Oloflarsson, what setting am I looking for?

**Comment by oloflarsson** [comment]
This is not a support forum. It's an issue tracker where we fix bugs people find. Ask for help on spigot or bukkit forums, thank you.
