### ISSUE TITLE
f claim - pss is null

### ISSUE THREAD

**Issue by PabloMA98** [MassiveCraft/Factions#910]
I've received this error in my console: http://pastebin.com/7jtygDmZ and http://pastebin.com/NUvmVZ6y
I use Spigot 1.8.7 and Factions / MassiveCore 2.8.0

**Comment by magnusulf** [comment]
under which circumstances does this happen?

**Comment by MarkehMe** [comment]
After testing, this occurs when you claim more than the allowed amount.

**Comment by ulumulu1510** [comment]
@Markehme, can you make a commit where you research the right thing to do?

Find where pss is being set to null and rather throw a MassiveException instead maybe? :)

**Comment by MarkehMe** [comment]
Looking for time to fix this, will work on it in a few hours or a bit later tonight. 

Just did general testing to find this bug, but I'll go ahead and work it out soon enough.

**Comment by ulumulu1510** [comment]
Awesome! :) Glad to see that you are found it.

**Comment by ulumulu1510** [comment]
I have fixed this problem locally, it should not take too long till pull to the master-branch:
https://github.com/ulumulu1510/Factions/commit/965c023d4700ae46bc33799310507e7c0745fc67

**Comment by ulumulu1510** [comment]
Resolved
