### ISSUE TITLE
Issue with factions

### ISSUE THREAD

**Issue by vuurwerkPWN** [MassiveCraft/Factions#911]
For some reason some people in my server are having issues with claiming land. They receive this message: Oops, something went wrong! Please report this to an Admin.. (in red color)
Some people told me that this issue occurred whenever you unclaimed you faction land (but they are not sure). But the point is that they have to leave their faction and create a new one and that would be really annoying.
Can someone explain me if I did something wrong in my configuration or that this is a bug?

~vuurwerkPWN

**Comment by darkwolf706** [comment]
Try doing a clean reinstall of Factions. Delete the mstore folder, then
install the latest version. Then try again

On Fri, Jul 24, 2015 at 5:03 PM, vuurwerkPWN <notifications@github.com>
wrote:

> For some reason some people in my server are having issues with claiming
> land. They receive this message: Oops, something went wrong! Please report
> this to an Admin.. (in red color)
> Some people told me that this issue occurred whenever you unclaimed you
> faction land (but they are not sure). But the point is that they have to
> leave their faction and create a new one and that would be really annoying.
> Can someone explain me if I did something wrong in my configuration or
> that this is a bug?
>
> ~vuurwerkPWN
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MassiveCraft/Factions/issues/911>.
>



-- 
Thanks!
- Chris
=================
Cell: +1 706-832--9609
Home: 317-344-6197
=================

**Comment by ulumulu1510** [comment]
For every issue I need:
Your bukkit/massivecore and factions version, otherwise I cannot and will not help you.

**Comment by vuurwerkPWN** [comment]
@ulumulu1510 
http://gyazo.com/c9036f5e3ae9eb69560ca35baec0b406   (spigot version)
factions and massivecore are both: 2.8.0 (latest version)

**Comment by vuurwerkPWN** [comment]
@ulumulu1510 
Oh btw, the error sometimes disappear after several hours/days/minutes but that varies by faction

**Comment by oloflarsson** [comment]
Such an error message should be accompanied by an error in the server console. You need to post the console error, please.

**Comment by vuurwerkPWN** [comment]
@oloflarsson 

There are no errors in the console

**Comment by vuurwerkPWN** [comment]
@oloflarsson 
The only thing that I can find this this:
http://pastebin.com/PQLDGi1G
I dont think its really useful...

**Comment by ulumulu1510** [comment]
Thanks for the needed info.

I cannot find this message in our plugins, could it be that this is caused by a third party plugin? Do you get any errors along with it? Could you screenshot me the error message if it appears again eventually?

**Comment by ulumulu1510** [comment]
This is hardly an error, but more a log that you have changed factions from Wilderness to TheHelpers.
An error message looks different, a stacktrace is printed out an shown on the console ( which looks like this:
https://www.spigotmc.org/wiki/fixing-plugin-problems-easily-reading-stacktraces/ )

If that doesn't appear, we cannot further investigate the issue.

**Comment by vuurwerkPWN** [comment]
@ulumulu1510 
Thanks, we found the issue the problem is solved now (it was a third faction plugin)
