### ISSUE TITLE
CommandSender Link has been severed

### ISSUE THREAD

**Issue by Jayfeather311** [MassiveCraft/Factions#912]
When I try to do /f claim (any of them) i get an error about the following
"ERROR: Your "CommandSender Link" has been severed. This shouldn't happen." etc
I am on a server where I am opped and owner of, And have configured it properly, this is not my first time on the server and it is a newly created faction. I have relogged from the server and even restarted the server as well. The problem persists

**Comment by oloflarsson** [comment]
This is because you are using Cauldron. Cauldron is not getting updates anymore and thus we have decided to not support it.
