### ISSUE TITLE
/f claim error

### ISSUE THREAD

**Issue by TentedNine** [MassiveCraft/Factions#919]
hello, the problem in plugin factions its the command /f claim 
Here the error of the command

Error: Your "CommandSender Link"has been severed. This shouldn't happen. The the factions developers by reporting this at: https://github.com/massivecraft/factions/issues.
Describe what you were doing, what client you are usin, this is your firsst time on the server etc. The more better.

Relogging server should fix the issue.

**Comment by oloflarsson** [comment]
You are running Cauldron, right? Cauldron is not supported. Feel free to create a pull request adding Cauldron support since we do not have the time to develop that ourselves.
