### ISSUE TITLE
Faction relation chats

### ISSUE THREAD

**Issue by darkarrow** [MassiveCraft/Factions#923]
I am currently using factions and herochat together. I have the chat all setup with the two and noticed that factions doesn't create channels for truce or ally-truce chats. So there's currently no way for factions in a truce to communicate with only other factions in a truce, only ally chat and faction chat. If I'm simply missing the configuration for it I'm sorry, but if this isn't implemented it really should be so truce's can communicate.

**Comment by magnusulf** [comment]
I believe this was never an option.
I guess you should talk to the HeroChat authors, but I am not sure.

**Comment by darkarrow** [comment]
Since the faction channel and ally channel are both handled by the faction plugin I figured this would be the right place to ask.

**Comment by oloflarsson** [comment]
If someone is going to implement a truce chat for HeroChat it's probably us Factions developers. There has never been one. But it's a good feature request I suppose.
