### ISSUE TITLE
Factions Prefix Problem

### ISSUE THREAD

**Issue by ChocolateCake112** [MassiveCraft/Factions#924]
So I'm having this problem where when I and other players speak and they have a faction their faction prefix isn't showing. I also changed the price when people wanna make a faction they have to pay $100 but I made it free but it didn't change. Something's wrong with the folder "factions_mconf" can someone tell me how to fix this issue? Thanks

**Comment by MarkehMe** [comment]
What chat plugin are you using?

**Comment by MarkehMe** [comment]
Assuming a solution was found as no response for a month.
