### ISSUE TITLE
Armor stands can be placed in other's territories

### ISSUE THREAD

**Issue by ItsHarry** [MassiveCraft/Factions#925]
Using Factions 2.8.0 (latest version)

I searched but did not find any other bug reports mentioning this:

It is possible to place armor stands in other people's territory.

**Comment by oloflarsson** [comment]
OK! Thanks for the bug report. Did you let the configuration file regenerate? There are entries that must be present in the config for that protection to work.

**Comment by ItsHarry** [comment]
The bug still happens with a fresh configuration file. I believe the only way to block placing armor stands is through cancelling EntitySpawnEvent

**Comment by ulumulu1510** [comment]
With our current version, this issue should be resolved. Please report back if this is not the case.
