### ISSUE TITLE
Nether portal raiding optional disabling (Suggestion)

### ISSUE THREAD

**Issue by MithrandirCraft** [MassiveCraft/Factions#927]
The issue:
-------------
I will explain in case you are unaware:

It is currently possible to infiltrate phisical faction bases from the nether by using Nether Portals. And Factions Plugin has no optional configuration option to stop this.

How to reproduce:
-------------------------
►1.You know the objective faction's coordinates. (Lets say this objective faction is somewhere on the Overworld map naturally linked to a Nether world.)
►2.You visit the nether. (1 horizontal block in the Nether is 8 blocks in the Overworld, but vertical distances are still the same between the Nether and the Overworld).
►3.Divide the X & Z Overworld faction coordinates per 8, and add the same Overworld Y altitud to the result.
►4.In the nether, travel towards the resulting X,Y,Z, distance from nether 0,0 "center" coordinates.
►5.Build a nether portal in those coordinates.
►6.Enter the portal, and a new portal will generate inside the Overworld faction (if you calculated well, and actually wanted to appear inside the enemy faction structure)

With this method (which you may already know of), whole faction members can suddenly infiltrate inside enemy factions and raid them phisically from inside.

Oposing players are usually taken by surprise.

My suggestion:
-------------------

A new configuration option should be implemented, which enables the disabilitation of Nether portal generation inside factions from or towards the nether.

Nether portals should still be allowed to be created inside factions, but not generated inside, which would effectively block portals from being generated inside factions by activating a portal from another world.

**Comment by ulumulu1510** [comment]
We actually were unaware of this problem, as far as I know. On our server the nether portals are disabled by default. I can look into this issue and report back what our teams opinion is on this issue.

**Comment by MithrandirCraft** [comment]
@ulumulu1510 Of course this could be considered a normal raiding method, but it should be possible to be optionally disabled.

When I think of gameplay issues as this one, I also think about Faction gameplay balance...
What should be considered propper faction raiding elements? To what point can a faction be safe?

**Comment by ulumulu1510** [comment]
@MithrandirCraft 
Nether portals are somewhat strange and there are many cases. Portal generation happens upon a player teleporting to a destination where there is no portal yet.

 So I could block portal creation in an enemy territory but letting him teleport or blocking teleportation to an enemy territory fully or only let it generate by faction members or allies or what not.

This would not be one, but many options and to find the one who is pleasing to all servers is purely impossible. Coding the one solution where you simply block a portals creation, is not statisfying enough I believe and not enough thought through. 

Maybe the solution lies in an external portal plugin, like CreativeGates
(https://github.com/MassiveCraft/CreativeGates), which regulates this problem in a more natural way.

All in all, I probably should not spend time developing on a patch, where there are appropriate solutions already around. And you shouldn't have to wrap your head around it either. :)

**Comment by MithrandirCraft** [comment]
Only 3 things can be blocked regarding NetherPortals:
 - Nether Portal Generation In faction territory (When a portal naturally generates in a faction 
   territory because another portal in another world made it do so.)
 - Nether Portal Creation In faction territory (When a player makes a portal at their faction with 
   obsidian + fire)
 - Portal Teleportation In faction territory (Using a nether portal in Faction Territory)

I think the hability to block/permit these 3 events should be pleasing enough for any server who wants to control Nether Portal behaviour in faction territories.

**Comment by MithrandirCraft** [comment]
Seriously, this nether portal issue has transformed into a fever on my server. I am unsure as to if there is any way to manually stop it, but it's transforming into a habbit for the players who know how it works.

No faction is internally safe xD

**Comment by MithrandirCraft** [comment]
I've made an exaustive plugin research... My only option seems to be the blocking of nether portal creations, allthough there are already many portals made.

The ideal solution would be the blockage of either portal creation from the nether towards the Factions world, or natural portal generation blocking in faction territories.

As I previously said, I think enabling control over those 3 nether portal behaviour points should be enough to keep any server admin happy with nether portals.

**Comment by ulumulu1510** [comment]
Good that you found a solution well suited to you and your server.
