### ISSUE TITLE
Getting stuck in nether portals

### ISSUE THREAD

**Issue by MithrandirCraft** [MassiveCraft/Factions#928]
The issue:
-------------
Players can sometimes get stuck in nether portals when they casually find a Nether portal in the nether, and get teleported to a Overworld Faction base (whose owners presumibly created this easy to make "torture device").

Once the player enters the portal (from the nether in my server's case), and gets teleported to the corresponding Overworld Faction portal, the player is stuck, if the faction owners have completely blocked the portal's exits, reducing the inside portal space to only it's portal blocks.

The trapped player cannot return to the previous portal, because the portal cannot teleport the player twice without it leaving the portal first. And the player cannot type any commands to escape, because the nausea effect given by remaining inside the portal blocks disables the player's chat usage.

Possible solutions:
-----------------------
New Mcore/Factions configuration for teleporting players to spawn if they remain inside a nether portal for a determined ammount of seconds.

New Mcore/Factions configuration for disabling nausea effect given by nether portal towards a player who remains a determined ammount of seconds inside it. (That way the player will be capable of typing and will leave the area manually.)

New Mcore/Factions configuration for automatically killing a player who remains a determined ammound of seconds inside a faction portal without being teleported.

Your choice. :)

**Comment by ulumulu1510** [comment]
On our server, we took a different approach on not letting this situation arrise:
Our players are not allowed to make such death traps/torture devices with portal, punishable by warning/kick/ban.

Having everything regulated by a plugin only seems to be the way, where its not the most efficient. Many corner cases would never be regulated, what happens if:
- the player does fall down in a death trap and cannot teleport out
- the player lands in lava
- the player lands in room full of enemies
... and so on.

Thus, regulating this overall portal situation by a new rule to your server will do the job best, because we can only cover a minor part of the real issue: your players being nasty ;)

**Comment by MithrandirCraft** [comment]
@ulumulu1510 
"What happens if:

 - The player does fall down in a death trap and cannot teleport out:
     Players don't simply fall in these types of traps. Nether portals are Vertical, so you have to go 
     through them. Unless there was an actually well thought and extremely unlikely diabolic redstone 
     device with pistons for pushing the "unsuspecting" player inside the portal and not leting him/her 
     escape, the player is most likely going to enter and remain inside the portal voluntarily untill the 
     teleport occurs. 
     Therefore, the player knows danger could await on the other side. If the player was killed for 
     remaining inside the portal blocks for 10 seconds it would be an appropiate punishment, and it 
     would solve all issues to the cost of player inventory (Fair enough, think about it.). This kind of  
     thing could happen in any other situation, players would be more carefull when traversing portals 
     in the future, and no one would be asking me to unstuck them from portals (And I would also not 
     have to either destroy or punish the portal or creator).
  - The player lands in lava:
     I don't understand what you mean by this. When a player travels from nether portal to nether
     portal, it is impossible for him/she to fall into a lava pit, unless the portal is manually destroyed 
     and the obsidian beneath it removed to reveal lava... or some other manover which would 
     require the artificer of the trap to be present (which usually isn't the case, because players get 
     stuck in these traps sometimes without the artificer intending it).
     If by falling in lava you are maybe comparing the fact of a player getting stuck inside a closed
     portal to a player falling in lava... well I think the situations are quite diferent, because the player 
     will get stuck in the portal, but with lava he or she will die shortly and respawn.

I prefer not to take care of such incidents by setting up rules, especially when it's so easy to build such traps... but if it is my only option I will.

I still think the best solution is removing players from portals when they remain there for too long by either killing or teleporting them.

**Comment by MithrandirCraft** [comment]
I still think something should be done about this.

**Comment by MithrandirCraft** [comment]
This is sad... You can't call this a feature. You know it's your responsability.

https://www.youtube.com/watch?v=rr1BNlchr2g

**Comment by ulumulu1510** [comment]
First of all, I recognize there is an issue. Second, guilt tripping doesn't work.

I recognized the issue a month ago and presented you an applicable solution. I left the issue ticket open so eventually if anyone of our team has time, they can investigate a technical solution to this minor edge case problem.

I don't have the time and it seems neither of the others do. Work with the solutions provided or investigate in another plugin to take care of your teleporting needs, so this issue cannot arrise anymore.

**Comment by MithrandirCraft** [comment]
@ulumulu1510 Allright then I'll just close this issue. Further debate seems pointless.

**Comment by MarkehMe** [comment]
I'll investigate the issue further, I have a few ideas in mind.

**Comment by ulumulu1510** [comment]
I am glad you had time to investigate the issue @markehme :).

**Comment by MithrandirCraft** [comment]
Well, I think I should appollogize for my possible rudeness. You must understand how an admin hates to see these things happening on their server.

I'm glad @MarkehMe will revise this issue :)

**Comment by MarkehMe** [comment]
There is a new configuration option I've introduce ``handleNetherPortalTrap `` (enabled by default).

**It works like so**:
A player enters a portal and then arrives at the portal destination. If player can't build in the area, the portal blocks are then hidden (only to that player, not other players) until that player moves a few blocks from the portal, in which they are reverted back to their original portal blocks.

**Comment by MithrandirCraft** [comment]
Hello. I would like to request this ticket to be re-oppened.

  "handleNetherPortalTrap": true,

The function seems to be working to some degree (Players getting near portals sometimes notice how the portal dissapears.)

However, when the player gets stuck in a portal, Factions isn't helping the player leave.
