### ISSUE TITLE
No block damage inside Claimed land

### ISSUE THREAD

**Issue by joveice** [MassiveCraft/Factions#929]
So creepers / TnT does not do blockdamage inside claimed land.
what do i need to fix for this to work?

**Comment by MarkehMe** [comment]
You need to change the flag to default to false.

The flags are in ```mstore/factions_mflag/```, you're looking for ```mstore/factions_mflag/explosions.json```

Change ```standard``` to ```false```

If you want the same for offline explosions, do the same to offlineexplosions.json
