### ISSUE TITLE
I get this spigot dumb error! Massive craft all over it. 

### ISSUE THREAD

**Issue by Gregin** [MassiveCraft/Factions#936]
http://pastebin.com/f83SGLjg

**Comment by ulumulu1510** [comment]
Massivecraft is shown in one place only (our database thread). This log is not complete, if you want actual help, provide the full log to us.

**Comment by Gregin** [comment]
That is the full log, just randomly happens throughout the day. I has a problem earlier with combatlog not working with factions so I upgrades to combattagplus, it works but I still wonder if there is an ongoing problem. 

The rest of the log is players logging in/out, voting, etc. No startup errors.

**Comment by MarkehMe** [comment]
Please provide that information @Gregin - 25 lines each way would be helpful! 

Also provide your plugins, their versions, Spigot build, mconf, and OS information. 

"I get this spigot dumb error! Massive craft all over it" is also not a very good way to describe your issue.

**Comment by Gregin** [comment]
Its late so I'll get it the full log for you tomorrow. I meant "spigot thread dump". I need to learn how to type properly. 

I'm sorry if I'm coming off rude and immature, I have just been frustrated with the problems I have been having with the server and my hosts.

**Comment by ulumulu1510** [comment]
@Gregin is the issue still persisting?

**Comment by magnusulf** [comment]
Incomplete and inactive. Closing.
