### ISSUE TITLE
Faction Claims 

### ISSUE THREAD

**Issue by julesle123456789** [MassiveCraft/Factions#938]
Every time I restart  my server the factions claims reset but the factions stay intact

**Comment by MarkehMe** [comment]
Please provide more information!
* What does your log say, are there any error messages (also check startup and shutdown)? 
* What version of Spigot/Bukkit are you using?
* Factions version?
* MassiveCore version?
* What other plugins are you using?

**Comment by julesle123456789** [comment]
1. Log says nothing
2. spigot (can't find the versions)
3. 2.8.0
4. 2.8.0
5. MultiWorld, WorldEdit, AdminFun, Essentials, EssentialsProtect, EssentialsChat, Item namer, EssentialsAntiBuild, PermissionsEx, PluginManager, Buycraft, MagicCarpet, HoloDisplays, Lockette, Vault, CommandSigns, EssentialsSpawn, Commandspy, MassiveCore, WorldGuard, Factions, CreativeGates.

P.S sorry for the lateness.

**Comment by julesle123456789** [comment]
Can anyone help me please?

**Comment by MarkehMe** [comment]
We wont be able to help you until we can replicate it on our end. 

Are you sure it is *every* time you restart? Are you reloading?

**Comment by magnusulf** [comment]
Which database system are you using for MassiveCore?

**Comment by julesle123456789** [comment]
Yes it is every time I restart my server and no I am just pressing restart I will analyz the log to see if it does it automaticaly. What do youmean what database system?

**Comment by magnusulf** [comment]
I mean if you use a flatfile system or MongoDB.
Also does this error occur when you only have Factions and MassiveCore on the server?

**Comment by ulumulu1510** [comment]
Communication has obviously stopped here. If this issue is to be regarded as still open, please leave a message here.
