### ISSUE TITLE
F Status (Players showing offline, but they're online!)

### ISSUE THREAD

**Issue by BoxmanCaleb** [MassiveCraft/Factions#939]
Hello, so basically I'm having an issue were some of the players on my server are showing offline in "/f status", but in reality they are online. This happened after I had restarted my server this evening. I've been looking for any errors, but here's all I can find.

http://pastebin.com/RpMMK07J

Spigot 1.8.8 (https://gyazo.com/5e4532b6df45a2ce31eb5a777c636a06)
Latest Factions and MCore versions. (2.8.0)
Plugins (https://gyazo.com/4b376672393a69fd74d5eabaaf2c7c9d)

**Comment by MarkehMe** [comment]
What version of Java are you running?

**Comment by MarkehMe** [comment]
I believe ```java.lang.Double.isFinite``` is only available in Java 8, you may be running Java 7. Try upgrading to Java 8.

**Comment by ulumulu1510** [comment]
@BoxmanCaleb, has anything changed in the last days? You might also want to update to the newest version of both massivecore and factions, since the Double.isFinite Problem was solved there.

**Comment by ulumulu1510** [comment]
@BoxmanCaleb If the error is still persisting, please open a new ticket. And before you do that, please update all Massive plugins to 2.8.2 in beforehand.
