### ISSUE TITLE
Certain comands not working.

### ISSUE THREAD

**Issue by MithrandirCraft** [MassiveCraft/Factions#941]
Some crucial commands (I think the ones that where reworked on Factions 2.8.0) such as /f invite have stopped working even when the user has the appropiate permission.

I got a Factions error log on console which may be related to this issue, allthough I haven't been able to produce it twice.

Error log: http://hastebin.com/bebuhofeqi.avrasm

**Comment by MarkehMe** [comment]
Can you provide your MassiveCore version and list of other plugins?

**Comment by MithrandirCraft** [comment]
Solved. You have made changes with the command structure, I should have paid more attention, yet there where no indications about this change in the update.

**Comment by MarkehMe** [comment]
Awesome, happy to hear you solved it. 

You can always see noticeable improvements in the change logs:
* http://dev.bukkit.org/bukkit-plugins/factions/files/76-factions-2-8-0/
* https://www.massivecraft.com/category/weekly-changelog

You can always find more technical changes in the commit logs:
* https://github.com/MassiveCraft/MassiveCore/commits/master
* https://github.com/MassiveCraft/Factions/commits/master

**Comment by MithrandirCraft** [comment]
@MarkehMe Thanks man :+1: very usefull.
