### ISSUE TITLE
Disable being able to teleport to allys faction /f home [name]

### ISSUE THREAD

**Issue by 50ouncebrew** [MassiveCraft/Factions#942]
How can we disable this option? I dont see it anywhere in the configs

**Comment by MarkehMe** [comment]
Could add an option to the configuration to allow it be relationship based.

**Comment by ulumulu1510** [comment]
It is by default an option in your faction perms. Every faction can decide for themself who can teleport to their f home and who can't.

It is true, there is no config option to comletly disable that feature.

**Comment by magnusulf** [comment]
You can edit the mflag, the folder is something like mstore/factions/mflag you can set a standard and make it non-changeable.
