### ISSUE TITLE
Faction auto kick players help.

### ISSUE THREAD

**Issue by 50ouncebrew** [MassiveCraft/Factions#943]
"removePlayerMillisDefault": 2592000000,
  "removePlayerMillisPlayerAgeToBonus": {
    "1209600000": 2592000000
  },
  "removePlayerMillisFactionAgeToBonus": {
    "2419200000": 2592000000,
    "1209600000": 432000000
  },

So i have it set for it to kick them out after 30 days but then in game it says 
automatic removeal after 60 days of inactivity

**Comment by ulumulu1510** [comment]
Could you please elaborate when this message shows up?
