### ISSUE TITLE
No such Method error on craftbukkit 1.8.8

### ISSUE THREAD

**Issue by luniso** [MassiveCraft/Factions#945]
Error here:
http://pastebin.com/jZmmfuf2

**Comment by MarkehMe** [comment]
Try using Java 8.

https://docs.oracle.com/javase/8/docs/technotes/guides/install/install_overview.html

**Comment by luniso** [comment]
it's a remote server, don't really know about its version.

**Comment by MarkehMe** [comment]
It would be best to check with your provider and also checking that MassiveCore is up to date.

Good luck!

**Comment by ulumulu1510** [comment]
Update to the new version 2.8.1 where we fixed the problem. This will solve your issue.

**Comment by luniso** [comment]
In the new version that happens when i type /f list:
http://pastebin.com/hvEjNxaa
