### ISSUE TITLE
[Feature Request] Database Porting?

### ISSUE THREAD

**Issue by Coolaxer** [MassiveCraft/Factions#946]
Hello!
I was looking to move to MongoDB for three reasons -
1. Faster access times
2. Because I can?
3. Too much free time
Anyways, after looking around, I know that factions supports it, but there is no official documentation on database porting. If I use flatfile and change to mongo, will it atuomatically convert the .jsons to mongodb database? Is there an external method I have to use? Is this something that is not added yet?

**Comment by oloflarsson** [comment]
There is a command similar to `/mcore copydb`. I don't remember exactly. You can use that one to port.
