### ISSUE TITLE
Lag spikes (entity explode event)

### ISSUE THREAD

**Issue by Kira07** [MassiveCraft/Factions#947]
http://image.noelshack.com/fichiers/2015/40/1443824702-faction.png

This performance issue is really annoying and often cause big lag spikes

**Comment by ulumulu1510** [comment]
Could you give us the stacktrace of that lagspike? I see you are using Massivelag, would you send in a stacktrace of it please?

Also, please state your factions and massivecore version.

**Comment by Kira07** [comment]
Sure, I'm using the latest faction & massivecore versions, for the stacktrace I'll do screenshots, if there is an easier way to get it (like in the log or in a file) please tell me.

**Comment by Kira07** [comment]
Here it is: http://pastebin.com/LZSRQ0GW

**Comment by Kira07** [comment]
Anything new ? This bug is really killing my performance, you're a good
dev, I hope you'll manage to fix it asap..

2015-10-02 23:29 GMT+01:00 Benjamin <notifications@github.com>:

**Comment by ulumulu1510** [comment]
Well, the issue lies in our IdUtil in MassiveCore, it is testigng whether the players of that faction are online or not. We have never experienced said issue on our server before, so it comes unexpected.

It also wonders me, why you face such issues so much (on averege once every half a second).

To investigate this issue we nees further information about the circumstances:
What server version are you running? Which exact versions of massivecore and factions do you have installed?

Do you have any plugins installed which cause a lot of explosions? Do you know any other reason why this event ist triggered that much?

**Comment by Kira07** [comment]
I use paperspigot 1.7.10 protocolhack, I run factions 2.8.1 and massivecore
2.8.1

I have no idea why this event is triggered so much and don't have any
plugin installed which cause a lot of explosions, in my spigot.yml I
limited the max-tnt-per-tick to 10. Maybe you could add an option to
completely disable the whole online/offline functionnality since I don't
use it, I don't understand why it checks if the faction is online or not
since offlineexplosions flag is on "true" for every factions in the server..

2015-10-04 18:10 GMT+01:00 Benjamin <notifications@github.com>:

**Comment by ulumulu1510** [comment]
That is what the FlagExlposion is for. Its documentation describes it this way:
"Can explosions occur in this territory?"
But truth be told, I looked at the code and even with that flag to false, it will still evaluate the online state of the faction in question. I am looking into this with Cayorion, so i can give you an appropriate answer

**Comment by Kira07** [comment]
All right, thank you

2015-10-05 18:08 GMT+01:00 Benjamin <notifications@github.com>:

**Comment by ulumulu1510** [comment]
@Kira07 Could I eventually pay a visit to your server to take a look myself? And would it be possible to give me access to the MassiveLag commands?

**Comment by Kira07** [comment]
Sure, my server ip is play.bloodsymphony.com
Just tell me your name and I'll give you access to the commands

2015-10-05 18:26 GMT+01:00 Benjamin <notifications@github.com>:

**Comment by ulumulu1510** [comment]
Name is as github name: ulumulu1510

**Comment by Kira07** [comment]
Done :)

2015-10-06 5:57 GMT+01:00 Benjamin <notifications@github.com>:

**Comment by ulumulu1510** [comment]
Your fix has been worked on and improvements have been made. Expect the fix to come with the next version.

**Comment by Kira07** [comment]
Great, nice to know

2015-10-06 20:28 GMT+01:00 Benjamin <notifications@github.com>:
