### ISSUE TITLE
Faction Money Balance

### ISSUE THREAD

**Issue by WitherPlayMc** [MassiveCraft/Factions#953]
All money in the faction bank will delete after a restart.

**Comment by MarkehMe** [comment]
Please provide more information:

* Your Economy plugin
* Factions version
* MassiveCore version

Consider this case: 
* Do player balances stay when the server restarts?

**Comment by Echo4211** [comment]
Just a guess, do you have Vault to support Factions with processing the money?

**Comment by ulumulu1510** [comment]
Factions itself doesn't handle money, it lets Vault do practically everything @Echo4211

**Comment by sammei19021** [comment]
Economy plugin is Essentials.

Latest Version of Vault, Factions, and MassiveCore.

PLayer balances do not reset when server restarts. I also have vault btw.

**Comment by Deiscorides** [comment]
I've seen this happen on a server I frequent. The server will start lagging badly then crash-restart. It wipes Factions Banks, but not all of them, it does not affect player balances. It happens often enough that the admin turned off the Factions disband penalty when they can't pay their taxes.

**Comment by MarkehMe** [comment]
Maybe consider having the team at https://github.com/MilkBowl/Vault take a look at it.

**Comment by ulumulu1510** [comment]
I second what @MarkehMe said. Either Team Vault or Essentials is the root of this problem, as we do not store the money in our plugin. Closing.
