### ISSUE TITLE
NullPointerException in factions 2.8.1

### ISSUE THREAD

**Issue by luniso** [MassiveCraft/Factions#959]
I found that error in my console, any idea?
http://pastebin.com/XEgQPHYW

**Comment by ulumulu1510** [comment]
Please state your versions of:
* MassiveCore 
* Factions
* spigot/bukkit

**Comment by luniso** [comment]
MassiveCore 2.8.1
Factions 2.8.1
spigot 1.8.8

**Comment by ulumulu1510** [comment]
Could you update to the latest version 2.8.2? That would help with searching for the nullpointer.

Under which circumstances has this error happened? Because it seems that somehow we got a nullpointer exception when it is very unlikely to have one.

**Comment by magnusulf** [comment]
You should first of all update to Factions 2.8.2.
It seems the issue is caused because of an invalid MConf. Try and delete your MConf (then reconfigure where necessary).

**Comment by ulumulu1510** [comment]
As the issue has been found and not been reported back, I assume the issue is resolved. Closing.
