### ISSUE TITLE
Integration with vanish-plugins

### ISSUE THREAD

**Issue by MyzelYam** [MassiveCraft/Factions#961]
Hey there!
Would be really cool if you could make the /f f command hide vanished players so it's harder for players to figure out who's vanished and who's actually offline. I personally recommend hooking into Essentials' hidden players api since my vanish-plugin and pretty much every other one hooks into Essentials, or just checking with Player#canSee(Player.class).
Thanks for reading, I really hope that you'll implement vanish-support since it would make vanish-plugins more powerful and server owners happier!

Original request: https://www.spigotmc.org/resources/supervanish.1331/reviews#review-46330-75348
My vanish-plugin: https://www.spigotmc.org/resources/supervanish.1331/

**Comment by ulumulu1510** [comment]
This is actually already a feature in the very latest version 2.8.2. You can read it in the commits on github (it is not really visible on the changelog on spigot).

**Comment by MyzelYam** [comment]
Ok thanks a lot!
