### ISSUE TITLE
SafeZone and WarZone

### ISSUE THREAD

**Issue by madtomic** [MassiveCraft/Factions#964]
Is there a way to remove the default factions? I tried deleting the safezone.json and warzone.json

**Comment by ulumulu1510** [comment]
No, there is not. They will always recreate upon restarting your server. You don't need to use them, but they will exist at all times.

You can rename them, change their flags and perms, do everything you can do with a normal faction, but you can not get rid of them completly. (All of the named actions here are definitly not recommended to do, but they work).

**Comment by madtomic** [comment]
How about disabling the Power of these factions?

**Comment by magnusulf** [comment]
Since this was a question and not a feature request. I will go ahead and close it.
It also seems you real issue is stated in #965
