### ISSUE TITLE
Faction Invite

### ISSUE THREAD

**Issue by mads5434** [MassiveCraft/Factions#967]
Hey guys, they Faction invite /f invite dosent work for me,
( I am not good with plugins what so ever :P )
Factions: 2.8.2
Massivecore: 2.8.2
Can someone help me pls :)?

**Comment by mads5434** [comment]
i found out how to invite people now, any way i can change it so it isent /f i a [ name ] to just /f invite [ name ]? :)

**Comment by MarkehMe** [comment]
You can still use /f invite. ```i``` and ```inv``` are simply aliases.

**Comment by mads5434** [comment]
Basicly when i do /f invite it only says : do /F help
it only works when i do /f i a [ name ]
![udklip](https://cloud.githubusercontent.com/assets/15790988/11080984/50a10350-8819-11e5-9118-460be104f5ea.PNG)

**Comment by MarkehMe** [comment]
You have to pass 'add' or 'a' as well.

Like so, ```/f invite a/add mads5434```

This is so you can also do:
```/f invite l/list``` - list invied players, and
```/f invite r/remove mads5434``` - remove a player from the invite list 

This is documented here: http://www.massivecraft.com/factions#commands

**Comment by mads5434** [comment]
Any way to make this simple? so u you need to do /f invite and not add the add?

**Comment by MarkehMe** [comment]
I made a plugin that can do this. http://dev.bukkit.org/bukkit-plugins/factionsalias/

Create an alias for ```/f invite``` to ```/f invite a```

**Comment by mads5434** [comment]
Thank u so much man!!

**Comment by MarkehMe** [comment]
No problem. :smile: if another issues arises, please open a new issue ticket. For issues with FactionsAlias please put the issues into that issue tracker!
