### ISSUE TITLE
Tnt And Creepers 

### ISSUE THREAD

**Issue by 10natcla** [MassiveCraft/Factions#968]
Tnt and Creepers are doing no damage in claimed land I have edited the m_flag
{
  "priority": 6000,
  "name": "explosions",
  "desc": "Can explosions occur in this territory?",
  "descYes": "Explosions can occur in this territory.",
  "descNo": "Explosions can NOT occur in this territory.",
  "standard": false,
  "editable": true,
  "visible": true
}
and still no luck any ideas thanks :D

**Comment by MarkehMe** [comment]
You do not have to modify the m_flag files to disable explosions in a territory. Simply use the ```/f flag``` command. 

The documentation for flags is here:
http://www.massivecraft.com/factions#flags

**Comment by 10natcla** [comment]
I don't want to disable it i want to enable it xD
