### ISSUE TITLE
factions_mplayer

### ISSUE THREAD

**Issue by esbencramer1** [MassiveCraft/Factions#969]
How do I fix this Error?

08.11 14:38:08 [Server] INFO Error: Raw data was null. Is the file completely empty?
08.11 14:38:08 [Server] INFO Collection: factions_mplayer
08.11 14:38:08 [Server] INFO Entity: 79db4ee4-23f5-464f-96be-8940d0adc544
08.11 14:38:08 [Server] INFO Database could not load entity. You edited a file manually and made wrong JSON?

**Comment by ulumulu1510** [comment]
Remove the file 79db4ee4-23f5-464f-96be-8940d0adc544.json in your mstore/factions_mplayer folder.

This usually happens when you edit a file manually, which you should be carefull about.
