### ISSUE TITLE
Tnt And Creepers 

### ISSUE THREAD

**Issue by 10natcla** [MassiveCraft/Factions#970]
The problem I am having is with Offline explosions and online explosions so when a someone makes a new faction it cant be raided is there a way I can make it so it auto does /f flag set Offlineexplosions yes and /f flag set Explosions yes. automaticly when a new faction is made instead of me having to type it in for all new factions.

Thank You :D

**Comment by ulumulu1510** [comment]
Yes :) 
Look in your mstore folder, you will find a directory called factions_flag.

In there, search for the two flags and open them. There is an option called "standart". Set it to your liking and close the files again. This can be done during runtime and no restart is needed.

You could also have found this by reading the documentation though, so please read it first before asking another question.

http://www.massivecraft.com/factions-configure#factions-flags
