### ISSUE TITLE
Message Config for Translations

### ISSUE THREAD

**Issue by Kaesebutterbrot** [MassiveCraft/Factions#971]
Would be awesome, if you can easily translate the plugin into your own language over a simple config file! I would be rly thankfull when it would be added!

**Comment by magnusulf** [comment]
That has been requested before, and the conclusion is that it would be a lot of work to implemen (and we have more important things to do)t. Some messages are also generated dynamically, which makes it even harder (and a  configuration more confusing).
You are however welcome to make a pull request with this feature, that is the beauty of open source.
