### ISSUE TITLE
Error with factions 2.8.2

### ISSUE THREAD

**Issue by fabien91** [MassiveCraft/Factions#972]
Hello,

I've a few errors with the last version with your plugin.

First error :
http://pastebin.com/Vunmtr9Q

Second error :
http://pastebin.com/8XcD2yhW

Thank's

Edit : It's a 2.8.2 and no 1.8.2 ^^

Faction Version : 2.8.2
MassiveCore Version : 2.8.2
Spigot Version : This server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by magnusulf** [comment]
Please state your version of, also you don't use factions 1.8.2:
Spigot
MassiveCore
Factions

**Comment by fabien91** [comment]
It's not 1.8.2, it's 2.8.2

Faction Version : 2.8.2
MassiveCore Version : 2.8.2
Spigot Version : This server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by MarkehMe** [comment]
Could you upload your factions mconf file to www.pastebin.com (```mstore/factions_mconf/instance.json```)? This looks similar to #950

**Comment by magnusulf** [comment]
Pastebin is no longer available. Please reupload.

**Comment by ulumulu1510** [comment]
We have been requesting PasteBin information which has not been delivered in a month @fabien91. If your issue persists, please tag me an I will re-open this issue. But for now, with no information what so ever, we cannot process this issue.
