### ISSUE TITLE
Add an event for when perms change

### ISSUE THREAD

**Issue by Pokechu22** [MassiveCraft/Factions#974]
It would be useful to have an event that occurs when a faction's Perms change.  I can think of some uses for this involving some protection plugins.

I might be able to write this myself (though I'm not too familiar with the factions code).  I think I'd just need to insert event code on [line 69 of `CmdFactionsPermSet`](https://github.com/MassiveCraft/Factions/blob/482b75be70f4c2e9739228aedcdc898a5e5cd63a/src/com/massivecraft/factions/cmd/CmdFactionsPermSet.java#L69) similar to the event found at [CmdFactionsRelationAbstract](https://github.com/MassiveCraft/Factions/blob/1c6f3f28d1d31814fa94588c87a68dcbc2d49ce9/src/com/massivecraft/factions/cmd/CmdFactionsRelationAbstract.java#L71-L75).

**Comment by magnusulf** [comment]
If you have the ability to do so, please make a PR. Also, look over other places where perms might be modified.

**Comment by Pokechu22** [comment]
@magnusulf I did - #976

**Comment by magnusulf** [comment]
Whoops, my bad. Then I guess we can keep the discussion there.
