### ISSUE TITLE
Something wrong with the database of the players

### ISSUE THREAD

**Issue by luniso** [MassiveCraft/Factions#978]
http://pastebin.com/ZGnjFFC0 there is the error, i don't know what happened, i didn't touch anything from there. All the people lost their faction.

**Comment by magnusulf** [comment]
The database has been modified externally. Either by you or someone else.
It could be manually, it could be a failed restore (from a backup), a failed write to the drive, or even a harddrive error. I have never seen this occur where it wasn't because of an external error.

**Comment by luniso** [comment]
I have noticed that the error came from the hard disk, but now i have to clear the database to reset it?

**Comment by oloflarsson** [comment]
No just the broken file. Find the file `1m2f5118ae-1cd1-3d51-ab61-1acf541feca5.json` and delete it and you will be good to go.

**Comment by MarkehMe** [comment]
A good tip is to always backup your data. Consider daily backups, your provider should give you the option to do it. 

It's always a safe bet to store your backups on a seperate server!
