### ISSUE TITLE
Ranks Break When Installed

### ISSUE THREAD

**Issue by ark9026** [MassiveCraft/Factions#980]
Hello, 

My problem is that when I installed Factions, it broke my ranks. I use essentials for ranks, and the second I installed the plugin all ranks broke. When I uninstall it, the ranks return. Could this bug please be fixed?

Thanks!
-Ark

**Comment by ark9026** [comment]
Oops, sorry about that. 

My problem is that when I installed Factions, it broke my ranks. I use essentials for ranks, and the second I installed the plugin all ranks broke. When I uninstall it, the ranks return. Could this bug please be fixed? 

Thanks!
-Ark

**Comment by ulumulu1510** [comment]
https://www.massivecraft.com/factions-configure

**Comment by ark9026** [comment]
Thanks!
