### ISSUE TITLE
Wilderness/Warzone per world

### ISSUE THREAD

**Issue by CrazzyNava** [MassiveCraft/Factions#983]
Hello, I need to know if there is a way to have a world with WarZone and Wilderness in another, because I want to have a world survival and other factions, thanks!

**Comment by magnusulf** [comment]
So a world where everything is a war zone?

**Comment by CrazzyNava** [comment]
Yes magnusulf, a world where everything is a warzone and another world where everything is a wilderness. :)

**Comment by magnusulf** [comment]
You can put a world into the world exception set called "worldsPvpRulesEnabled" then factions will not enforce PvP rules there and PvP should be possible (otherwise make it possible through another plugin such as worldguard),

**Comment by CrazzyNava** [comment]
Not exactly what I need, what I want is one world with warzone called "factions" and can not be built until you claim land, and other world with wilderness or without factions called "world" can not be never claimed. If is necessary worldguard, explain me, because I have installed this :D

**Comment by CrazzyNava** [comment]
anyone help?

**Comment by MarkehMe** [comment]
The "Wilderness" faction can actually be renamed and it's flags can be changed. Maybe this is something you want to do?

**Comment by magnusulf** [comment]
Since this was actually a question and not a feature request. I will go ahead and close it.
