### ISSUE TITLE
start faction

### ISSUE THREAD

**Issue by flo025** [MassiveCraft/Factions#984]
[Erreur Java]	java.lang.Thread.run(Thread.java:722) [?:1.7.0]
[Erreur Java]	net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	java.util.concurrent.FutureTask.run(FutureTask.java:166) [?:1.7.0]
[Erreur Java]	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [?:1.7.0]
[Erreur Java]	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0]
[Erreur Java]	net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:742) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
[Erreur Java]	com.massivecraft.factions.Factions.onEnable(Factions.java:131) ~[?:?]
[Erreur Java]	com.massivecraft.factions.entity.MConfColl.init(MConfColl.java:39) ~[?:?]
[Erreur Java]	com.massivecraft.massivecore.store.Coll.init(Coll.java:868) ~[?:?]
[Erreur Java]	com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:794) ~[?:?]
[Erreur Java]	com.massivecraft.massivecore.store.Coll.loadFromRemoteFixed(Coll.java:567) ~[?:?]
[Erreur Java]	com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:848) ~[?:?]
[Erreur Java]	com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:875) ~[?:?]
[Erreur Java]	com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:810) ~[?:?]
[Erreur Java]	com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:197) ~[?:?]
[Erreur Java]	com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:104) ~[?:?]
[Erreur Java]	com.massivecraft.massivecore.xlib.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:1) ~[?:?]
[Erreur Java]	com.massivecraft.massivecore.xlib.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:191) ~[?:?]
com.massivecraft.massivecore.xlib.gson.JsonSyntaxException:	duplicate key: null
[14:04:42]	[Server thread/ERROR] : Error occurred while enabling Factions v2.8.2 (Is it up to date?)
[14:04:42]	[Server thread/INFO] : [0;36;22m[[0;36;1mFactions 2.8.2[0;36;22m] [0;33;1m=== ENABLE START ===

**Comment by magnusulf** [comment]
Put this into a pastern, it is impossible to read on GitHub.

**Comment by magnusulf** [comment]
It seems your MConf is "bad" try deleting it and let it regenerate. Also don't do /reload we don't support that.
