### ISSUE TITLE
Factions /invite Not Working

### ISSUE THREAD

**Issue by iMember** [MassiveCraft/Factions#985]
When i type /faction invite it says that the command is not found, what's the deal with that?

**Comment by magnusulf** [comment]
In your MConf you haven't set "faction" as an alias. Add "faction" as alias and it should work.

**Comment by iMember** [comment]
That didn't work, it says 
Couldn't find the command /faction i,inv,invite
Maybe you could try /faction i,inv,invite

**Comment by TheWesternComic** [comment]
I am having the same problem.

**Comment by MarkehMe** [comment]
Have you tried restarting the server? Can you put your mconf on pastebin for us?

**Comment by TheWesternComic** [comment]
I have an active player base but I will restart it very soon and paste the log and the mconf.

**Comment by iMember** [comment]
Restarting has no effect on fixing it, here is the pastebin

http://pastebin.com/M3SUH7ic

**Comment by iMember** [comment]
Does it have something to do with me making the hero chat shortcuts False instead of true?

**Comment by TheWesternComic** [comment]
Think I did this right XD. Log:  http://pastebin.com/b6wCkaT7  MCONF: http://pastebin.com/XCWsTY2e

**Comment by MarkehMe** [comment]
```
  "aliasesF": [
    "f"
  ],
```

You both have not specified additional aliases.. so only ```/f``` can be used.

```
  "aliasesF": [
    "f",
    "faction" 
  ],
```

That will allow you to use ```/f```, and ```/faction```.

```
  "aliasesF": [
    "f",
    "potato",
    "watermelon"
  ],
```

That will allow you to use ```/f```, ```/potato```, and ```/watermelon```.

**Comment by TheWesternComic** [comment]
Will this fix my problem? Or is it just a helpful tip for the future?  Either way thanks!

**Comment by MarkehMe** [comment]
@TheWesternComic your error seems to be something different ```java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PlayerInventory``` is in relation to your server version not matching up with something we're looking for. I suggest opening a new issue ticket. However if you're using KCauldron or some alternative that isn't Spigot then that may be the reason it's having issues!

**Comment by iMember** [comment]
No, that still didn't fix the problem i'm getting, still says the same thing when i try to do the command

**Comment by iMember** [comment]
Log Pastebin

http://pastebin.com/gpr2M7t4

**Comment by iMember** [comment]
Bumping because i'm still having this problem and need help fixing it

**Comment by MarkehMe** [comment]
@iMember in your log, there is no note of any errors are invalid command executions in relation to MassiveCraft plugins.

**Comment by iMember** [comment]
No, the /f or /faction alias does not work, either one i try i still get the same response

Couldn't find the command /faction i,inv,invite
Maybe you could try /faction i,inv,invite

**Comment by ulumulu1510** [comment]
I am guessing here, but are you using the invite command like this? : /f invite  <player>

Because that us not how the command works and our system tries to tell you that.

If you want to add someone to your invites do /f invite add <player>.

With this new arrangement you are now also able to deinvite and even get a list of already invited people: /f invite list.

As said, this is a guess here since your console is fine, the mconf doesn't seem to be the problem either, so it must be something completly else.

**Comment by iMember** [comment]
.......really? That was the problem, jesus. i was using /f invite instead of /f invite add
it gets changed around alot....but thanks, nothing was wrong just wasn't putting in the right command and when it was telling me that it wasn't the right command just confused me because it was confusing me on trying to tell me what command i was supposed to use

**Comment by ulumulu1510** [comment]
It has changed once around 2.8, but that is some time ago. If you type /f invite, it tells you all its subcommands, which it wanted to sugfest you using. Anyhow,  glad we could help.
