### ISSUE TITLE
Issue with WorldGaurd

### ISSUE THREAD

**Issue by 13markan** [MassiveCraft/Factions#987]
Alright im trying to PREVENT players from claiming world guarded areas 

heres part of the config

  "worldguardCheckEnabled": true,
  "worldguardCheckWorldsEnabled": {
    "standard": true,
    "exceptions": []

But even with it like that they can STILL claim land can anyone assist me on this

**Comment by MarkehMe** [comment]
Have you assigned all permissions? e.g. ```factions.*``` or ```factions.allowregionclaim.*``` - this will allow the bypas. 

Try denying the permission for that region using it's id ```-factions.allowregionclaim.ID```

**Comment by 13markan** [comment]
i have not tampered with any perms, everything is at default, EXCEPT prices IE claiming land starting a faction ect

**Comment by MarkehMe** [comment]
Is this still an issue? I have not been able to replicate it, and I'm assuming for now it is bad configuration.
