### ISSUE TITLE
java.lang.NoClassDefFoundError: com/blahblahblah/RelationParticipator

### ISSUE THREAD

**Issue by Jason-FTW** [MassiveCraft/Factions#990]
![image](https://cloud.githubusercontent.com/assets/16409843/11971476/5e79955a-a8f3-11e5-839d-cd3953c2f69a.png)

**Comment by Jason-FTW** [comment]
Full Log:
![image](https://cloud.githubusercontent.com/assets/16409843/11971563/a6a8a216-a8f4-11e5-89a6-ce033c42906c.png)

**Comment by MarkehMe** [comment]
Your versions of MassiveCore and Factions should be matching. 

Please supply your Factions and MassiveCore version. But I'll assume thats the issue for now :smile:

**Comment by magnusulf** [comment]
That is not the issue, @MarkehMe.
If I am not mistaken this error sometimes occurs on old versions of java. Try and update to Java 8 and see if the error persists.

**Comment by Jason-FTW** [comment]
The problem was indeed incompatible/incorrect versions of MC and Factions.

Solved by downloading MassiveCore and Factions from dev.bukkit.org
(Factions: http://dev.bukkit.org/bukkit-plugins/factions/)
(MassiveCore: http://dev.bukkit.org/bukkit-plugins/mcore/)
