### ISSUE TITLE
Factions TAB

### ISSUE THREAD

**Issue by KriticalPvP1** [MassiveCraft/Factions#991]
Anyone know if you can go to create a faction members of another color on the tab?

**Comment by magnusulf** [comment]
What is TAB?

**Comment by KriticalPvP1** [comment]
TabList

**Comment by ulumulu1510** [comment]
Please try to reword your question, it currently is hard to decode.

By what I can guess, you'd like the names in a tablist to be colored according to their relationship to the sender. I am sorry to inform you, but the Tab-List does not allow any colors. We can only provide the words, but not any colors.

**Comment by KriticalPvP1** [comment]
Sorry my English is bad, I wanted to do something about it: https://gyazo.com/b3fb219b2a2adaea5955adcd58b14b8b

**Comment by magnusulf** [comment]
We (the Factions authors) does not try to manipulate the tablist in any way. If that is done, or should be done, on your server, it is not our responsibility.
