### ISSUE TITLE
ExplosionPrimeEvent not used?

### ISSUE THREAD

**Issue by Robotia** [MassiveCraft/Factions#992]
I have set the factions flag explosions to be false. However, Factions never uses the ExplosionsPrimeEvent, so explosions still go off.

Am I doing something wrong?

**Comment by magnusulf** [comment]
When explosions are disabled, they are supposed to not damage any blocks but still damage players and mobs. (Just stating in case you thought something else).
Remember there is also an offlineexplosions flag. (Just stating in case you didn't know)

You have disabled explosions by setting the explosions flag to false, but explosions still occur. Have I understood your issue correctly?
What do you mean by "occur", do explosions damage blocks, do they damage entities, what happens?
Under which circumsatnces do explosions still occur, I doubt it is all the time (but could be)?

**Comment by Robotia** [comment]
@magnusulf Sorry I wasn't being clear. I was just curious as to why ExplosionPrimeEvent was not used by Factions.
On a Cauldron server, explosions were bypassing Faction protection. I modified a Cauldron server to pass Forge's explosion event to Bukkit's ExplosionPrimeEvent. I just found it strange that Factions would not listen to this event.

**Comment by MarkehMe** [comment]
This would be an issue of the Cauldron server then, you should ask the developers to ensure all the original Bukkit events are still being called.
