### ISSUE TITLE
Revert Wilderness to Original World over time

### ISSUE THREAD

**Issue by DraksterAU** [MassiveCraft/Factions#993]
Nice feature idea..

Config option to set a timer from when a chunk becomes unclaimed to when it reverts (gradually) back to the original world state.

Could also do this so that if someone builds in an unclaimed area, the building is automatically disassembled after the timer too...

Great for helping out admins in the inevitable cleanup that follows a large explosion and a player abandoning the base...

PS: Towny does this, to some extent... its the final frontier toward perpetual worlds :)

**Comment by ulumulu1510** [comment]
Although I see your input as valuable (thank you for it), this is not the job of Factions to do. Factions is a player driven land distribution and management tool, not a restore tool for your unclaimed chunks.

We as the developers from MassiveCraft have created suh a plugin, but it is currently not (and might never be) for sale.

Unless @oloflarsson decides to do make it buyable, we will not implement this feature.

**Comment by DraksterAU** [comment]
@oloflarsson Sellll ittttt! :)
