### ISSUE TITLE
 bug plugin faction omgserv

### ISSUE THREAD

**Issue by hugoda57** [MassiveCraft/Factions#995]
Omgserv support my request to come because I have to install the plugin " faction" in the version of my game and the server but the controls are not avaialble in play and an error s playing in my golden console is a plugin essential to my server

**Comment by ulumulu1510** [comment]
Three things which help me to help you:
1) Your bukkit,  MassiveCore and Factions Version
2) The error showing on your console aswell as more detail to the problem as like when it occures etc.
3) Punctuation.

**Comment by hugoda57** [comment]
thank you to you we managed to solve the problem it was a problem venent the plugin version PLUSIEUR Version 1.7.10 was available but only one walked

**Comment by ulumulu1510** [comment]
Although I still not fully understand you, your problem seems to be solved. Closing.
