### ISSUE TITLE
FactionsUUID - dynmap dont work S/F

### ISSUE THREAD

**Issue by Educationals** [MassiveCraft/Factions#997]
I have a problem with changing colors for Warzone and SafeZone, so I know where the config but I do not know how it got changed for each faction got good or bad color, and not. Please help! simply factions are all the same color.
http://imgur.com/tNu9It2   <<-- check my conf.
http://82.208.17.11:30719/  <<-- dynmap

**Comment by Educationals** [comment]
and also do not see the flag f home

**Comment by ulumulu1510** [comment]
We arent FactionsUUID, please bother those authors since it is not our responsibility to fix their old patchy adaptions.

**Comment by Educationals** [comment]
I'm sorry, I mistook forum
