### ISSUE TITLE
Package com.massivecraft.massivecore.command

### ISSUE THREAD

**Issue by Plasticable** [MassiveCraft/Factions#999]
I imported all libs that was at "lib" folder to project but it can't find package "com.massivecraft.massivecore.command"

**Comment by Jason-FTW** [comment]
Same error.
I fixed it by importing the MassiveCore plugin from github, recompiling that, and then referencing the one you exported onto Factions.

**Comment by ulumulu1510** [comment]
If you are compiling the latest factions of github you also need to compile the corresponding latest version of MassiveCore from github.
We develope them simultaniously and we also release them in bundles to make sure all versions are compatible. But if for some reason you want to compile it now, you will need to compile MassiveCore first and then compile Factions (which depends on that just compiled version of MassiveCore)
